[fprime]
# Maximum duration to wait between downlink chunks before giving up on the downlink. Use 0s to wait forever
downlink-timeout = '10s'
# Size in bytes of the 'data' portion on file uplinks. Note packets will include additional overhead around the raw data.
uplink-chunk-size = 256
# Save uplink bandwidth by sending '/' instead of the real source path of a file.
uplink-truncate-source-path = true
# Uplink rate limit in bytes per second, use '0.0' to disable limiter.
uplink-rate-limit = 0.0
packet-descriptor-type = 'U32'
opcode-type = 'U32'
chan-id-type = 'U32'
event-id-type = 'U32'
prm-id-type = 'U32'
tlm-packetize-type = 'U16'
buff-size-type = 'U16'
enum-store-type = 'I32'
time-base-store-type = 'U16'
time-context-store-type = 'U8'
# Expect timebase to be encoded into timestamp values
use-time-base = true
# Expect time context to be encoded into timestamp values
use-time-context = true
# Binary to encode 'true' boolean values as
true-value = 255
# Binary to encode 'false' boolean values as
false-value = 0

# Time bases SCLK conversions. If no mapping is found UTC is assumed
[fprime.time-bases]
[fprime.time-bases.0]
# Time system type to convert SCLK times into UTC/Database times
# utc: UTC time (includes leap second skips)
# tai: TAI clock (atomic time scale)
# ephemeris: (ET, TDB) Similar to TAI with periodic relativistic deltas
# terrestrial: (TT, TDT) Same as TAI with constant offset
# spice: Load a .tsc SPICE kernel to convert between SCLK and UTC
# ert: The time an event is processed, similar to earth return time
time-system = 'utc'
# Base epoch time (0 time).
epoch = '1970-01-01T00:00:00Z'
# .tsc SPICE kernel to load if using time-system='spice'
spice-kernel = ''
# SCLK Parition index to use for input time (0 for absolute scaling/default)
spice-sclk-partition = 0
# Spacecraft ID to load from SPICE kernel file.
# hint: look for SCLK01_TIME_SYSTEM_[SCID] in .tsc SPICE kernel.
spice-scid = ''

[host]
# Path to store files downlinked from connected sources
downlink-root = '.'
# Root path to load profile configuration and dictionaries from
root-path = '.'
# Bind type gRPC. Options: 'tcp', 'tcp4', 'tcp6', 'unix' or 'unixpacket'
bind-type = 'tcp'
# Bind gRPC service to this address
bind-address = '0.0.0.0:6880'
# Start all profiles on backend startup
start-profiles = false
# Export logs, metrics, & traces to an OpenTelemetry gRPC Collector
otel-export = true
# Export flight-software emitted events as OpenTelemetry logs records
event-as-otel = true
# Export flight-software emitted channelized telemetry (numeric only) as OpenTelemetry metrics.
# Note: This logs all datapoints using wall-clock time instead of flight-software time
channel-as-otel = true
# Export file downlink events as OpenTelemetry log records
downlink-as-otel = true
# Export OpenTelemetry channels and events using Earth-Return-Time instead of FSW time
use-ert = true
