services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hermes
    ports:
      - 5432:5432/tcp
    volumes:
      - timescale-data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "https://github.com/nasa/hermes/releases/latest/download/nasa-hermes-datasource.zip;nasa-hermes-datasource"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: nasa-hermes-datasource
    depends_on:
      timescaledb:
        condition: service_started
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config:/etc/grafana/provisioning:ro
volumes:
  timescale-data:
  grafana-data:
