site_name: Hermes - Spacecraft Command & Telemetry
site_description: Documentation for the Hermes spacecraft command and telemetry system
site_author: NASA

theme:
  name: material
  logo: assets/hermes-light.svg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      logo: assets/hermes-dark.svg
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  version:
      provider: mike
      alias: true
  generator: false # removes "Made with Material for Mkdocs"
  homepage: https://hermes.jpl.nasa.gov/ # Forces homepage link not to include versioning info

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
