# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x06hermes\"\xae\x01\n\nFileHeader\x12\x13\n\x0bsource_path\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65stination_path\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x04\x12\x32\n\x08metadata\x18\x04 \x03(\x0b\x32 .hermes.FileHeader.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"P\n\x0fUplinkFileChunk\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x12.hermes.FileHeaderH\x00\x12\x0e\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x00\x42\x07\n\x05value\"\x89\x01\n\x10\x44ownlinkFileData\x12\x0e\n\x06offset\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12,\n\x02md\x18\x03 \x03(\x0b\x32 .hermes.DownlinkFileData.MdEntry\x1a)\n\x07MdEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"1\n\x14\x44ownlinkFileMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x18\n\x16\x44ownlinkFileValidation\"\xd4\x01\n\x11\x44ownlinkFileChunk\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x12.hermes.FileHeaderH\x00\x12(\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x18.hermes.DownlinkFileDataH\x00\x12\x30\n\x08metadata\x18\x03 \x01(\x0b\x32\x1c.hermes.DownlinkFileMetadataH\x00\x12\x34\n\nvalidation\x18\x04 \x01(\x0b\x32\x1e.hermes.DownlinkFileValidationH\x00\x42\x07\n\x05valueB\x1fZ\x1dgithub.com/nasa/hermes/pkg/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035github.com/nasa/hermes/pkg/pb'
  _globals['_FILEHEADER_METADATAENTRY']._loaded_options = None
  _globals['_FILEHEADER_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_DOWNLINKFILEDATA_MDENTRY']._loaded_options = None
  _globals['_DOWNLINKFILEDATA_MDENTRY']._serialized_options = b'8\001'
  _globals['_FILEHEADER']._serialized_start=23
  _globals['_FILEHEADER']._serialized_end=197
  _globals['_FILEHEADER_METADATAENTRY']._serialized_start=150
  _globals['_FILEHEADER_METADATAENTRY']._serialized_end=197
  _globals['_UPLINKFILECHUNK']._serialized_start=199
  _globals['_UPLINKFILECHUNK']._serialized_end=279
  _globals['_DOWNLINKFILEDATA']._serialized_start=282
  _globals['_DOWNLINKFILEDATA']._serialized_end=419
  _globals['_DOWNLINKFILEDATA_MDENTRY']._serialized_start=378
  _globals['_DOWNLINKFILEDATA_MDENTRY']._serialized_end=419
  _globals['_DOWNLINKFILEMETADATA']._serialized_start=421
  _globals['_DOWNLINKFILEMETADATA']._serialized_end=470
  _globals['_DOWNLINKFILEVALIDATION']._serialized_start=472
  _globals['_DOWNLINKFILEVALIDATION']._serialized_end=496
  _globals['_DOWNLINKFILECHUNK']._serialized_start=499
  _globals['_DOWNLINKFILECHUNK']._serialized_end=711
# @@protoc_insertion_point(module_scope)
