# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bus_pb2 as bus__pb2
import dictionary_pb2 as dictionary__pb2
import file_pb2 as file__pb2
import fsw_pb2 as fsw__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import msg_pb2 as msg__pb2
import profile_pb2 as profile__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hermes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sequence = channel.unary_unary(
                '/Api/Sequence',
                request_serializer=fsw__pb2.CommandSequence.SerializeToString,
                response_deserializer=msg__pb2.SequenceReply.FromString,
                _registered_method=True)
        self.RawSequence = channel.unary_unary(
                '/Api/RawSequence',
                request_serializer=fsw__pb2.RawCommandSequence.SerializeToString,
                response_deserializer=msg__pb2.SequenceReply.FromString,
                _registered_method=True)
        self.Command = channel.unary_unary(
                '/Api/Command',
                request_serializer=fsw__pb2.CommandValue.SerializeToString,
                response_deserializer=msg__pb2.Reply.FromString,
                _registered_method=True)
        self.Request = channel.unary_unary(
                '/Api/Request',
                request_serializer=fsw__pb2.RequestValue.SerializeToString,
                response_deserializer=fsw__pb2.RequestReply.FromString,
                _registered_method=True)
        self.RawCommand = channel.unary_unary(
                '/Api/RawCommand',
                request_serializer=fsw__pb2.RawCommandValue.SerializeToString,
                response_deserializer=msg__pb2.Reply.FromString,
                _registered_method=True)
        self.Uplink = channel.stream_unary(
                '/Api/Uplink',
                request_serializer=file__pb2.UplinkFileChunk.SerializeToString,
                response_deserializer=msg__pb2.Reply.FromString,
                _registered_method=True)
        self.GetFsw = channel.unary_unary(
                '/Api/GetFsw',
                request_serializer=msg__pb2.Id.SerializeToString,
                response_deserializer=fsw__pb2.Fsw.FromString,
                _registered_method=True)
        self.AllFsw = channel.unary_unary(
                '/Api/AllFsw',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=msg__pb2.FswList.FromString,
                _registered_method=True)
        self.SubscribeFsw = channel.unary_stream(
                '/Api/SubscribeFsw',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=msg__pb2.FswList.FromString,
                _registered_method=True)
        self.StartProfile = channel.unary_unary(
                '/Api/StartProfile',
                request_serializer=msg__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StopProfile = channel.unary_unary(
                '/Api/StopProfile',
                request_serializer=msg__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/Api/UpdateProfile',
                request_serializer=msg__pb2.ProfileUpdate.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddProfile = channel.unary_unary(
                '/Api/AddProfile',
                request_serializer=profile__pb2.Profile.SerializeToString,
                response_deserializer=msg__pb2.Id.FromString,
                _registered_method=True)
        self.RemoveProfile = channel.unary_unary(
                '/Api/RemoveProfile',
                request_serializer=msg__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AllProfiles = channel.unary_unary(
                '/Api/AllProfiles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=msg__pb2.ProfileList.FromString,
                _registered_method=True)
        self.AllProviders = channel.unary_unary(
                '/Api/AllProviders',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=msg__pb2.ProfileProviderList.FromString,
                _registered_method=True)
        self.GetFileTransferState = channel.unary_unary(
                '/Api/GetFileTransferState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=bus__pb2.FileTransferState.FromString,
                _registered_method=True)
        self.ClearDownlinkTransferState = channel.unary_unary(
                '/Api/ClearDownlinkTransferState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ClearUplinkTransferState = channel.unary_unary(
                '/Api/ClearUplinkTransferState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SubscribeProviders = channel.unary_stream(
                '/Api/SubscribeProviders',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=msg__pb2.ProfileProviderList.FromString,
                _registered_method=True)
        self.SubscribeProfiles = channel.unary_stream(
                '/Api/SubscribeProfiles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=msg__pb2.ProfileList.FromString,
                _registered_method=True)
        self.GetDictionary = channel.unary_unary(
                '/Api/GetDictionary',
                request_serializer=msg__pb2.Id.SerializeToString,
                response_deserializer=dictionary__pb2.Dictionary.FromString,
                _registered_method=True)
        self.AddDictionary = channel.unary_unary(
                '/Api/AddDictionary',
                request_serializer=dictionary__pb2.Dictionary.SerializeToString,
                response_deserializer=msg__pb2.Id.FromString,
                _registered_method=True)
        self.RemoveDictionary = channel.unary_unary(
                '/Api/RemoveDictionary',
                request_serializer=msg__pb2.Id.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AllDictionary = channel.unary_unary(
                '/Api/AllDictionary',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=msg__pb2.DictionaryList.FromString,
                _registered_method=True)
        self.SubscribeDictionary = channel.unary_stream(
                '/Api/SubscribeDictionary',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=msg__pb2.DictionaryList.FromString,
                _registered_method=True)
        self.SubEvent = channel.unary_stream(
                '/Api/SubEvent',
                request_serializer=bus__pb2.BusFilter.SerializeToString,
                response_deserializer=bus__pb2.SourcedEvent.FromString,
                _registered_method=True)
        self.SubTelemetry = channel.unary_stream(
                '/Api/SubTelemetry',
                request_serializer=bus__pb2.BusFilter.SerializeToString,
                response_deserializer=bus__pb2.SourcedTelemetry.FromString,
                _registered_method=True)
        self.SubFileDownlink = channel.unary_stream(
                '/Api/SubFileDownlink',
                request_serializer=bus__pb2.BusFilter.SerializeToString,
                response_deserializer=bus__pb2.FileDownlink.FromString,
                _registered_method=True)
        self.SubFileUplink = channel.unary_stream(
                '/Api/SubFileUplink',
                request_serializer=bus__pb2.BusFilter.SerializeToString,
                response_deserializer=bus__pb2.FileUplink.FromString,
                _registered_method=True)
        self.SubFileTransfer = channel.unary_stream(
                '/Api/SubFileTransfer',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=bus__pb2.FileTransferState.FromString,
                _registered_method=True)


class ApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sequence(self, request, context):
        """*
        Send a command sequence to the FSW to execute.

        If the FSW connection does not implement this endpoint directly,
        this becomes a pseudo-endpoint that will wrap the 'Command' and allow
        running commands in sequence. This is preferrable to successive
        calls to 'Command' because commands are grouped together into
        a single 'Trace' for easily tracking what was sent to the system.

        Metadata:
        "id": [fsw-id]

        TODO(tumbar) We will probably want to expand this to add some identifying
        metadata to allow linking back to the code cell in our Notebooks

        Optional Metadata
        Keep executing the sequence even if
        "keepGoingOnFailure": "x"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RawSequence(self, request, context):
        """*
        A wrapper endpoint around Sequence/RawCommand.
        This endpoint will parse a sequence and run it through Sequence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Command(self, request, context):
        """*
        Send a command to the FSW. Wait for
        completion or otherwise, up to the
        plugin to decide when the promise resolves.

        Metadata:
        "id": [fsw-id]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Request(self, request, context):
        """*
        Send a custom request to the FSW. Requests
        are not defined in the dictionary. The request
        payload data is defined by an agreement between
        the frontend request initiator and the connection
        implementation.

        Metadata:
        "id": [fsw-id]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RawCommand(self, request, context):
        """*
        Send a 'raw' command to the FSW. A raw command
        differs from a full command in that it must be parsed
        by the backend. Each FSW must support converting an argument list
        to a command value and passing it to the "real" Command() interface.
        Wait for completion or otherwise, up to the
        plugin to decide when the promise resolves.

        Metadata:
        "id": [fsw-id]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Uplink(self, request_iterator, context):
        """*
        Uplink a file to the FSW.

        Metadata:
        "id": [fsw-id]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFsw(self, request, context):
        """Get FSW metadata given its ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllFsw(self, request, context):
        """Get all the current connected FSWs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeFsw(self, request, context):
        """Subscribe to any changes to FSW connections state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartProfile(self, request, context):
        """Start a profile and return once it's connected (cancellable)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopProfile(self, request, context):
        """Stop profile given its name/id and reutrn once its stopped (cancellable)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Update a profile
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProfile(self, request, context):
        """Create a new profile, returns it's registered ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProfile(self, request, context):
        """Delete a profile by its id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllProfiles(self, request, context):
        """Get all the profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllProviders(self, request, context):
        """Get all the registered profile providers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileTransferState(self, request, context):
        """Get the current file downlink/uplink state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearDownlinkTransferState(self, request, context):
        """Clear the cached downlink transfer state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearUplinkTransferState(self, request, context):
        """Clear the cached uplink transfer state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeProviders(self, request, context):
        """Get notified when the set of profile providers updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeProfiles(self, request, context):
        """Get notified when the set of profile or their internal state updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDictionary(self, request, context):
        """*
        Get a dictionary by its ID
        Metadata (optional)
        The dictionary "sections" to include in the reply.
        This is a whitelist set of options to include. If this
        list is not provided or empty, the entire dictionary will be transmitted

        A "section" includes two parts [namespace].[definition-id]
        - namespace: Name of the namespace to include
        - section: The portion of the namespace to include, the following sections are valid
        - "commands": All the command definitions in this namespace
        - "events": All event definitions this namespaces
        - "telemetry": All telemetry definitions this namespaces
        - "parameters": All parameter definitions this namespaces
        - "*": The entire namespace
        Example: "sections": [".events", "ns-1.*", "ns-2.telemetry"]
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDictionary(self, request, context):
        """Add a new dictionary entry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveDictionary(self, request, context):
        """Remove specified dictionary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllDictionary(self, request, context):
        """Get all registered dictionaries as a sequential stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeDictionary(self, request, context):
        """Subscribe to changes to the dictionary state. streams { id, type }
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubEvent(self, request, context):
        """Subscribe to the event message bus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubTelemetry(self, request, context):
        """Subscribe to the telemetry message bus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubFileDownlink(self, request, context):
        """Subscribe to the file downlink message bus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubFileUplink(self, request, context):
        """Subscribe to the file downlink message bus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubFileTransfer(self, request, context):
        """Subscribe to the aggregated state of file uplink and downlink
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sequence': grpc.unary_unary_rpc_method_handler(
                    servicer.Sequence,
                    request_deserializer=fsw__pb2.CommandSequence.FromString,
                    response_serializer=msg__pb2.SequenceReply.SerializeToString,
            ),
            'RawSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.RawSequence,
                    request_deserializer=fsw__pb2.RawCommandSequence.FromString,
                    response_serializer=msg__pb2.SequenceReply.SerializeToString,
            ),
            'Command': grpc.unary_unary_rpc_method_handler(
                    servicer.Command,
                    request_deserializer=fsw__pb2.CommandValue.FromString,
                    response_serializer=msg__pb2.Reply.SerializeToString,
            ),
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=fsw__pb2.RequestValue.FromString,
                    response_serializer=fsw__pb2.RequestReply.SerializeToString,
            ),
            'RawCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RawCommand,
                    request_deserializer=fsw__pb2.RawCommandValue.FromString,
                    response_serializer=msg__pb2.Reply.SerializeToString,
            ),
            'Uplink': grpc.stream_unary_rpc_method_handler(
                    servicer.Uplink,
                    request_deserializer=file__pb2.UplinkFileChunk.FromString,
                    response_serializer=msg__pb2.Reply.SerializeToString,
            ),
            'GetFsw': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFsw,
                    request_deserializer=msg__pb2.Id.FromString,
                    response_serializer=fsw__pb2.Fsw.SerializeToString,
            ),
            'AllFsw': grpc.unary_unary_rpc_method_handler(
                    servicer.AllFsw,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=msg__pb2.FswList.SerializeToString,
            ),
            'SubscribeFsw': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeFsw,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=msg__pb2.FswList.SerializeToString,
            ),
            'StartProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.StartProfile,
                    request_deserializer=msg__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StopProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.StopProfile,
                    request_deserializer=msg__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=msg__pb2.ProfileUpdate.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProfile,
                    request_deserializer=profile__pb2.Profile.FromString,
                    response_serializer=msg__pb2.Id.SerializeToString,
            ),
            'RemoveProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProfile,
                    request_deserializer=msg__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AllProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.AllProfiles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=msg__pb2.ProfileList.SerializeToString,
            ),
            'AllProviders': grpc.unary_unary_rpc_method_handler(
                    servicer.AllProviders,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=msg__pb2.ProfileProviderList.SerializeToString,
            ),
            'GetFileTransferState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileTransferState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=bus__pb2.FileTransferState.SerializeToString,
            ),
            'ClearDownlinkTransferState': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearDownlinkTransferState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ClearUplinkTransferState': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearUplinkTransferState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SubscribeProviders': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeProviders,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=msg__pb2.ProfileProviderList.SerializeToString,
            ),
            'SubscribeProfiles': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeProfiles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=msg__pb2.ProfileList.SerializeToString,
            ),
            'GetDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDictionary,
                    request_deserializer=msg__pb2.Id.FromString,
                    response_serializer=dictionary__pb2.Dictionary.SerializeToString,
            ),
            'AddDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDictionary,
                    request_deserializer=dictionary__pb2.Dictionary.FromString,
                    response_serializer=msg__pb2.Id.SerializeToString,
            ),
            'RemoveDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveDictionary,
                    request_deserializer=msg__pb2.Id.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AllDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.AllDictionary,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=msg__pb2.DictionaryList.SerializeToString,
            ),
            'SubscribeDictionary': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeDictionary,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=msg__pb2.DictionaryList.SerializeToString,
            ),
            'SubEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.SubEvent,
                    request_deserializer=bus__pb2.BusFilter.FromString,
                    response_serializer=bus__pb2.SourcedEvent.SerializeToString,
            ),
            'SubTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.SubTelemetry,
                    request_deserializer=bus__pb2.BusFilter.FromString,
                    response_serializer=bus__pb2.SourcedTelemetry.SerializeToString,
            ),
            'SubFileDownlink': grpc.unary_stream_rpc_method_handler(
                    servicer.SubFileDownlink,
                    request_deserializer=bus__pb2.BusFilter.FromString,
                    response_serializer=bus__pb2.FileDownlink.SerializeToString,
            ),
            'SubFileUplink': grpc.unary_stream_rpc_method_handler(
                    servicer.SubFileUplink,
                    request_deserializer=bus__pb2.BusFilter.FromString,
                    response_serializer=bus__pb2.FileUplink.SerializeToString,
            ),
            'SubFileTransfer': grpc.unary_stream_rpc_method_handler(
                    servicer.SubFileTransfer,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=bus__pb2.FileTransferState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Api', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Api', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Api(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/Sequence',
            fsw__pb2.CommandSequence.SerializeToString,
            msg__pb2.SequenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RawSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/RawSequence',
            fsw__pb2.RawCommandSequence.SerializeToString,
            msg__pb2.SequenceReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/Command',
            fsw__pb2.CommandValue.SerializeToString,
            msg__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/Request',
            fsw__pb2.RequestValue.SerializeToString,
            fsw__pb2.RequestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RawCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/RawCommand',
            fsw__pb2.RawCommandValue.SerializeToString,
            msg__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Uplink(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Api/Uplink',
            file__pb2.UplinkFileChunk.SerializeToString,
            msg__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFsw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/GetFsw',
            msg__pb2.Id.SerializeToString,
            fsw__pb2.Fsw.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllFsw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/AllFsw',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            msg__pb2.FswList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeFsw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubscribeFsw',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            msg__pb2.FswList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/StartProfile',
            msg__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/StopProfile',
            msg__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/UpdateProfile',
            msg__pb2.ProfileUpdate.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/AddProfile',
            profile__pb2.Profile.SerializeToString,
            msg__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/RemoveProfile',
            msg__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/AllProfiles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            msg__pb2.ProfileList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/AllProviders',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            msg__pb2.ProfileProviderList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileTransferState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/GetFileTransferState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            bus__pb2.FileTransferState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearDownlinkTransferState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/ClearDownlinkTransferState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearUplinkTransferState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/ClearUplinkTransferState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeProviders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubscribeProviders',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            msg__pb2.ProfileProviderList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubscribeProfiles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            msg__pb2.ProfileList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/GetDictionary',
            msg__pb2.Id.SerializeToString,
            dictionary__pb2.Dictionary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/AddDictionary',
            dictionary__pb2.Dictionary.SerializeToString,
            msg__pb2.Id.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/RemoveDictionary',
            msg__pb2.Id.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Api/AllDictionary',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            msg__pb2.DictionaryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubscribeDictionary',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            msg__pb2.DictionaryList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubEvent',
            bus__pb2.BusFilter.SerializeToString,
            bus__pb2.SourcedEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubTelemetry',
            bus__pb2.BusFilter.SerializeToString,
            bus__pb2.SourcedTelemetry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubFileDownlink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubFileDownlink',
            bus__pb2.BusFilter.SerializeToString,
            bus__pb2.FileDownlink.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubFileUplink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubFileUplink',
            bus__pb2.BusFilter.SerializeToString,
            bus__pb2.FileUplink.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubFileTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/Api/SubFileTransfer',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            bus__pb2.FileTransferState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProviderStub(object):
    """API to provide interface with an external software
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connection = channel.stream_stream(
                '/Provider/Connection',
                request_serializer=msg__pb2.FswConnectionPacket.SerializeToString,
                response_deserializer=msg__pb2.Uplink.FromString,
                _registered_method=True)
        self.File = channel.stream_unary(
                '/Provider/File',
                request_serializer=file__pb2.DownlinkFileChunk.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Event = channel.stream_unary(
                '/Provider/Event',
                request_serializer=bus__pb2.SourcedEvent.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Telemetry = channel.stream_unary(
                '/Provider/Telemetry',
                request_serializer=bus__pb2.SourcedTelemetry.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ProviderServicer(object):
    """API to provide interface with an external software
    """

    def Connection(self, request_iterator, context):
        """*
        A long lived connection telling the host that a link is active with
        some external software (FSW). The server streams in uplink requests which
        are handled and replied to over this long lived connection.

        Any downlink comming from this FSW is routed through the other client stream endpoints.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def File(self, request_iterator, context):
        """*
        Initiate a file downlink session with the host.

        This request is for a single file downlink session.
        It should start with a FileHeader and stream byte data

        TODO(tumbar) Figure out a mechanism for file validation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Event(self, request_iterator, context):
        """*
        Stream events to the host.
        The client can open as many of these as needed though they should be long-lived.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Telemetry(self, request_iterator, context):
        """*
        Stream telemetry to the host.
        The client can open as many of these as needed though they should be long-lived.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connection': grpc.stream_stream_rpc_method_handler(
                    servicer.Connection,
                    request_deserializer=msg__pb2.FswConnectionPacket.FromString,
                    response_serializer=msg__pb2.Uplink.SerializeToString,
            ),
            'File': grpc.stream_unary_rpc_method_handler(
                    servicer.File,
                    request_deserializer=file__pb2.DownlinkFileChunk.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Event': grpc.stream_unary_rpc_method_handler(
                    servicer.Event,
                    request_deserializer=bus__pb2.SourcedEvent.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Telemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.Telemetry,
                    request_deserializer=bus__pb2.SourcedTelemetry.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Provider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Provider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Provider(object):
    """API to provide interface with an external software
    """

    @staticmethod
    def Connection(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/Provider/Connection',
            msg__pb2.FswConnectionPacket.SerializeToString,
            msg__pb2.Uplink.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def File(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Provider/File',
            file__pb2.DownlinkFileChunk.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Event(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Provider/Event',
            bus__pb2.SourcedEvent.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Telemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/Provider/Telemetry',
            bus__pb2.SourcedTelemetry.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
