mod fprime;

// Re-export submodules
pub mod command;
pub mod common;
pub mod error;
pub mod event;
pub mod parameter;
pub mod telemetry;

use common::{annotation_to_metadata, name_key, parse_name, parse_type};
use error::DictionaryError;
use event::{parse_fpp_format_string, parse_severity};
use hermes_pb::*;
use std::collections::HashMap;

pub use fprime::{FPrimeDictionary, Severity, TypeDescriptor, TypeKind};

/// Parse an FPrime JSON dictionary from a JSON string.
///
/// This function converts an FPrime JSON dictionary (generated by FPP or fprime-tools)
/// into Hermes' protobuf-based Dictionary format.
///
/// # Arguments
///
/// * `raw_json` - A JSON string containing the FPrime dictionary data
///
/// # Returns
///
/// * `Ok(Dictionary)` - The parsed dictionary in Hermes protobuf format
/// * `Err(DictionaryError)` - If parsing fails or the dictionary contains invalid data
///
/// # Example
///
/// ```no_run
/// use hermes_fprime_dictionary::parse_fprime_json_dictionary;
///
/// let json = r#"{
///     "metadata": {"deploymentName": "MyMission"},
///     "commands": [],
///     "events": [],
///     "telemetryChannels": []
/// }"#;
///
/// let dictionary = parse_fprime_json_dictionary(json).unwrap();
/// ```
///
/// # Dictionary Structure
///
/// The resulting Dictionary contains:
/// - **Namespaces**: Two namespaces are created:
///   - `""` (empty string): Contains all commands, events, telemetry channels, parameters, and types
///   - `"telemetry-packets"`: Contains telemetry packet definitions (if any)
/// - **Metadata**: Additional dictionary metadata like spacecraft ID
///
/// # Conversion Details
///
/// The function performs the following conversions:
/// - Type definitions (enums, structs, arrays, aliases) -> protobuf Type objects
/// - Commands -> CommandDef with qualified name parsing
/// - Events -> EventDef with severity conversion and format string preprocessing
/// - Telemetry channels -> TelemetryDef
/// - Parameters -> ParameterDef
/// - Telemetry packet sets -> Composite telemetry types
pub fn parse_fprime_json_dictionary(raw_json: &str) -> Result<Dictionary, DictionaryError> {
    let json: FPrimeDictionary = serde_json::from_str(raw_json)?;

    let mut out = Dictionary {
        head: Some(DictionaryHead {
            r#type: "fprime".to_string(),
            name: json
                .metadata
                .as_ref()
                .and_then(|m| m.deployment_name.clone())
                .unwrap_or_default(),
            version: json
                .metadata
                .as_ref()
                .and_then(|m| m.project_version.clone())
                .unwrap_or_default(),
        }),
        content: HashMap::new(),
        metadata: HashMap::new(),
        id: String::new(),
    };

    let mut ns = DictionaryNamespace {
        commands: HashMap::new(),
        events: HashMap::new(),
        telemetry: HashMap::new(),
        parameters: HashMap::new(),
        types: HashMap::new(),
    };

    let mut tlm_pkts = DictionaryNamespace {
        commands: HashMap::new(),
        events: HashMap::new(),
        telemetry: HashMap::new(),
        parameters: HashMap::new(),
        types: HashMap::new(),
    };

    // Process type definitions
    if let Some(type_defs) = &json.type_definitions {
        for type_def in type_defs {
            match type_def {
                fprime::TypeDefinition::Array {
                    qualified_name,
                    size,
                    element_type,
                    annotation,
                    ..
                } => {
                    let array_type = Type {
                        value: Some(hermes_pb::r#type::Value::Array(Box::new(ArrayType {
                            name: qualified_name.clone(),
                            el_type: Some(Box::new(parse_type(element_type)?)),
                            size: Some(hermes_pb::array_type::Size::Static(*size as u32)),
                            length_type: UIntKind::UintU32 as i32,
                        }))),
                        metadata: annotation_to_metadata(annotation),
                    };
                    ns.types.insert(qualified_name.clone(), array_type);
                }
                fprime::TypeDefinition::Enum {
                    qualified_name,
                    representation_type,
                    enumerated_constants,
                    annotation,
                    ..
                } => {
                    let encode_type_pb = parse_type(representation_type)?;

                    // Validate that the encode type is an integer
                    let encode_type = if let Some(hermes_pb::r#type::Value::Int(int_type)) =
                        &encode_type_pb.value
                    {
                        int_type.kind
                    } else {
                        return Err(DictionaryError::InvalidEnumEncodeType(format!(
                            "{:?}",
                            representation_type.kind
                        )));
                    };

                    let items = enumerated_constants
                        .iter()
                        .map(|c| EnumItem {
                            value: c.value as i32,
                            name: c.name.clone(),
                            metadata: annotation_to_metadata(&c.annotation),
                        })
                        .collect();

                    let enum_type = Type {
                        value: Some(hermes_pb::r#type::Value::Enum(EnumType {
                            name: qualified_name.clone(),
                            encode_type,
                            items,
                        })),
                        metadata: annotation_to_metadata(annotation),
                    };
                    ns.types.insert(qualified_name.clone(), enum_type);
                }
                fprime::TypeDefinition::Struct {
                    qualified_name,
                    members,
                    annotation,
                    ..
                } => {
                    // Sort members by index
                    let mut sorted_members: Vec<_> = members.iter().collect();
                    sorted_members.sort_by(|a, b| {
                        a.1.index
                            .partial_cmp(&b.1.index)
                            .unwrap_or(std::cmp::Ordering::Equal)
                    });

                    let fields: Result<Vec<_>, DictionaryError> = sorted_members
                        .into_iter()
                        .map(|(name, field)| {
                            let field_type = if let Some(size) = field.size {
                                // Field has an array size
                                Type {
                                    value: Some(hermes_pb::r#type::Value::Array(Box::new(
                                        ArrayType {
                                            name: String::new(),
                                            el_type: Some(Box::new(parse_type(&field.type_)?)),
                                            size: Some(hermes_pb::array_type::Size::Static(
                                                size as u32,
                                            )),
                                            length_type: UIntKind::UintU32 as i32,
                                        },
                                    ))),
                                    metadata: String::new(),
                                }
                            } else {
                                parse_type(&field.type_)?
                            };

                            Ok::<Field, DictionaryError>(Field {
                                name: name.clone(),
                                r#type: Some(field_type),
                                metadata: annotation_to_metadata(&field.annotation),
                                value: None,
                            })
                        })
                        .collect();

                    let object_type = Type {
                        value: Some(hermes_pb::r#type::Value::Object(ObjectType {
                            name: qualified_name.clone(),
                            fields: fields?,
                        })),
                        metadata: annotation_to_metadata(annotation),
                    };
                    ns.types.insert(qualified_name.clone(), object_type);
                }
                fprime::TypeDefinition::Alias {
                    qualified_name,
                    underlying_type,
                    ..
                } => {
                    let alias_type = parse_type(underlying_type)?;
                    ns.types.insert(qualified_name.clone(), alias_type);
                }
            }
        }
    }

    // Process events
    if let Some(events) = &json.events {
        for event in events {
            let (component, name) = parse_name(&event.name)?;
            let key = format!("{}.{}", component, name);

            let arguments: Result<Vec<_>, DictionaryError> = event
                .formal_params
                .iter()
                .map(|param| {
                    Ok::<Field, DictionaryError>(Field {
                        name: param.name.clone(),
                        r#type: Some(parse_type(&param.type_)?),
                        metadata: annotation_to_metadata(&param.annotation),
                        value: None,
                    })
                })
                .collect();

            // Parse the format string first so we can use it for backward compatibility
            let format = Some(parse_fpp_format_string(
                &event
                    .format
                    .clone()
                    .unwrap_or_else(|| "unknown message".to_string()),
                event.formal_params.len(),
            )?);

            let event_def = EventDef {
                id: event.id as i32,
                component,
                name,
                severity: parse_severity(&event.severity)? as i32,
                #[allow(deprecated)]
                format_string: format
                    .as_ref()
                    .map(|f| f.original.clone())
                    .unwrap_or_default(),
                arguments: arguments?,
                metadata: annotation_to_metadata(&event.annotation),
                format,
            };

            ns.events.insert(key, event_def);
        }
    }

    // Process telemetry channels
    if let Some(channels) = &json.telemetry_channels {
        for channel in channels {
            let (key, telemetry_def) = telemetry::process_telemetry_channel(channel)?;
            ns.telemetry.insert(key, telemetry_def);
        }
    }

    // Process commands
    if let Some(commands) = &json.commands {
        for command in commands {
            let (key, command_def) = command::process_command(command)?;
            ns.commands.insert(key, command_def);
        }
    }

    // Process parameters
    if let Some(parameters) = &json.parameters {
        for param in parameters {
            let (key, param_def) = parameter::process_parameter(param)?;
            ns.parameters.insert(key, param_def);
        }
    }

    // Process telemetry packet sets
    if let Some(packet_sets) = &json.telemetry_packet_sets {
        for packet_set in packet_sets {
            for packet in &packet_set.members {
                // Resolve telemetry packet as a single struct type
                let fields: Result<Vec<_>, DictionaryError> = packet
                    .members
                    .iter()
                    .map(|member_name| {
                        let key = name_key(member_name)?;
                        let member_tlm = ns
                            .telemetry
                            .get(&key)
                            .ok_or_else(|| DictionaryError::TelemetryNotFound(key.clone()))?;

                        Ok(Field {
                            name: key.replace('.', "_"),
                            r#type: member_tlm.r#type.clone(),
                            metadata: String::new(),
                            value: None,
                        })
                    })
                    .collect();

                let packet_type = Type {
                    value: Some(hermes_pb::r#type::Value::Object(ObjectType {
                        name: packet.name.clone(),
                        fields: fields?,
                    })),
                    metadata: String::new(),
                };

                let tlm_def = TelemetryDef {
                    id: packet.id as i32,
                    name: packet.name.clone(),
                    component: "_".to_string(),
                    r#type: Some(packet_type),
                    metadata: format!(r#"{{"group":{}}}"#, packet.group),
                };

                tlm_pkts.telemetry.insert(packet.name.clone(), tlm_def);
            }
        }

        // Copy all types to telemetry packets namespace
        for (name, type_) in &ns.types {
            tlm_pkts.types.insert(name.clone(), type_.clone());
        }
    }

    // Add namespaces to dictionary
    out.content.insert(String::new(), ns);
    if json.telemetry_packet_sets.is_some() {
        out.content
            .insert("telemetry-packets".to_string(), tlm_pkts);
    }

    // Extract SpacecraftId from constants if present
    if let Some(constants) = json.constants {
        if let Some(scid) = constants
            .iter()
            .find(|c| c.qualified_name == "ComCfg.SpacecraftId")
        {
            if let Some(value) = scid.value.as_f64() {
                out.metadata
                    .insert("SpacecraftId".to_string(), value.to_string());
            } else {
                return Err(DictionaryError::InvalidSpacecraftId(format!(
                    "{:?}",
                    scid.value
                )));
            }
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_fprime_json_dictionary() {
        let json = r#"{
            "metadata": {
                "deploymentName": "TestDeployment",
                "frameworkVersion": "3.0.0",
                "projectVersion": "1.0.0"
            },
            "typeDefinitions": [
                {
                    "kind": "enum",
                    "qualifiedName": "TestComponent.TestEnum",
                    "representationType": {
                        "name": "U8",
                        "kind": "integer",
                        "size": 8,
                        "signed": false
                    },
                    "enumeratedConstants": [
                        {
                            "name": "VALUE1",
                            "value": 0,
                            "annotation": "First value"
                        },
                        {
                            "name": "VALUE2",
                            "value": 1
                        }
                    ],
                    "default": "VALUE1",
                    "annotation": "Test enum"
                }
            ],
            "commands": [
                {
                    "name": "TestComponent.TestCommand",
                    "commandKind": "async",
                    "opcode": 1,
                    "formalParams": [
                        {
                            "name": "arg1",
                            "type": {
                                "name": "U32",
                                "kind": "integer",
                                "size": 32,
                                "signed": false
                            },
                            "ref": false,
                            "annotation": "Argument 1"
                        }
                    ],
                    "annotation": "Test command"
                }
            ],
            "events": [
                {
                    "name": "TestComponent.TestEvent",
                    "severity": "WARNING_HI",
                    "formalParams": [
                        {
                            "name": "value",
                            "type": {
                                "name": "U32",
                                "kind": "integer",
                                "size": 32,
                                "signed": false
                            },
                            "ref": false,
                            "annotation": "Test value"
                        }
                    ],
                    "id": 1,
                    "annotation": "Test event",
                    "format": "Test message: {d}"
                }
            ],
            "telemetryChannels": [
                {
                    "name": "TestComponent.TestChannel",
                    "type": {
                        "name": "F32",
                        "kind": "float",
                        "size": 32
                    },
                    "id": 1,
                    "telemetryUpdate": "always",
                    "annotation": "Test channel"
                }
            ],
            "parameters": [
                {
                    "name": "TestComponent.TestParam",
                    "type": {
                        "name": "U32",
                        "kind": "integer",
                        "size": 32,
                        "signed": false
                    },
                    "id": 1,
                    "annotation": "Test parameter",
                    "default": 42
                }
            ]
        }"#;

        let dict = parse_fprime_json_dictionary(json).unwrap();

        // Verify dictionary head
        let head = dict.head.as_ref().unwrap();
        assert_eq!(head.r#type, "fprime");
        assert_eq!(head.name, "TestDeployment");
        assert_eq!(head.version, "1.0.0");

        // Verify namespaces exist
        assert!(dict.content.contains_key(""));

        let ns = dict.content.get("").unwrap();

        // Verify types
        assert_eq!(ns.types.len(), 1);
        assert!(ns.types.contains_key("TestComponent.TestEnum"));

        // Verify commands
        assert_eq!(ns.commands.len(), 1);
        let cmd = ns.commands.get("TestComponent.TestCommand").unwrap();
        assert_eq!(cmd.opcode, 1);
        assert_eq!(cmd.mnemonic, "TestCommand");
        assert_eq!(cmd.component, "TestComponent");
        assert_eq!(cmd.arguments.len(), 1);
        assert_eq!(cmd.arguments[0].name, "arg1");

        // Verify events
        assert_eq!(ns.events.len(), 1);
        let evt = ns.events.get("TestComponent.TestEvent").unwrap();
        assert_eq!(evt.id, 1);
        assert_eq!(evt.name, "TestEvent");
        assert_eq!(evt.component, "TestComponent");
        assert_eq!(evt.severity, EvrSeverity::EvrWarningHigh as i32);
        assert_eq!(evt.arguments.len(), 1);
        assert_eq!(evt.arguments[0].name, "value");

        // Verify format string was parsed
        let format = evt.format.as_ref().unwrap();
        assert_eq!(format.original, "Test message: {d}");
        assert_eq!(format.fragments.len(), 2); // text + specifier
        if let Some(format_fragment::Fragment::Specifier(spec)) = &format.fragments[1].fragment {
            assert_eq!(spec.r#type, FormatSpecifierType::FmtDecimal as i32);
            assert_eq!(spec.argument_index, 0);
        } else {
            panic!("Expected specifier fragment");
        }

        // Verify telemetry
        assert_eq!(ns.telemetry.len(), 1);
        let tlm = ns.telemetry.get("TestComponent.TestChannel").unwrap();
        assert_eq!(tlm.id, 1);
        assert_eq!(tlm.name, "TestChannel");
        assert_eq!(tlm.component, "TestComponent");

        // Verify parameters
        assert_eq!(ns.parameters.len(), 1);
        let param = ns.parameters.get("TestComponent.TestParam").unwrap();
        assert_eq!(param.id, 1);
        assert_eq!(param.name, "TestParam");
        assert_eq!(param.component, "TestComponent");
    }
}
