// Code generated by protocolc. DO NOT EDIT.

package test

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"strconv"

	"github.com/nasa/hermes/pkg/serial"
)

type ArrayFlat struct {
	StaticPrim  [3]uint32 `json:"static_prim"`
	StaticByte  [3]byte   `json:"static_byte"`
	StaticEnum  [3]EA     `json:"static_enum"`
	DyanmicPrim []uint32  `json:"dyanmic_prim"`
	DynamicByte []byte    `json:"dynamic_byte"`
	DynamicEnum []EA      `json:"dynamic_enum"`
	ReadPrim    []uint32  `json:"read_prim"`
	ReadByte    []byte    `json:"read_byte"`
	ReadEnum    []EA      `json:"read_enum"`
	FillPrim    []uint32  `json:"fill_prim"`
	FillByte    []byte    `json:"fill_byte"`
	FillEnum    [3]EA     `json:"fill_enum"`
}

func (s *ArrayFlat) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal StaticPrim
	for i := range 3 {
		s.StaticPrim[i], err = r.U32()
		if err != nil {
			return fmt.Errorf("s.StaticPrim[i]: %w", err)
		}
	}

	// Unmarshal StaticByte
	s.StaticByte, err = r.Read(uint32(3))
	if err != nil {
		return fmt.Errorf("array buffer read failed: %w", err)
	}

	// Unmarshal StaticEnum
	for i := range 3 {
		err = s.StaticEnum[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("EA unmarshal failed: %w", err)
		}
	}

	// Unmarshal DyanmicPrim
	var s_DyanmicPrimLen uint16
	s_DyanmicPrimLen, err = r.U16()
	if err != nil {
		return fmt.Errorf("s_DyanmicPrimLen: %w", err)
	}
	s.DyanmicPrim = make([]uint32, s_DyanmicPrimLen)
	for i := range s_DyanmicPrimLen {
		s.DyanmicPrim[i], err = r.U32()
		if err != nil {
			return fmt.Errorf("s.DyanmicPrim[i]: %w", err)
		}
	}

	// Unmarshal DynamicByte
	var s_DynamicByteLen uint16
	s_DynamicByteLen, err = r.U16()
	if err != nil {
		return fmt.Errorf("s_DynamicByteLen: %w", err)
	}
	s.DynamicByte, err = r.Read(uint32(s_DynamicByteLen))
	if err != nil {
		return fmt.Errorf("array buffer read failed: %w", err)
	}

	// Unmarshal DynamicEnum
	var s_DynamicEnumLen uint16
	s_DynamicEnumLen, err = r.U16()
	if err != nil {
		return fmt.Errorf("s_DynamicEnumLen: %w", err)
	}
	s.DynamicEnum = make([]EA, s_DynamicEnumLen)
	for i := range s_DynamicEnumLen {
		err = s.DynamicEnum[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("EA unmarshal failed: %w", err)
		}
	}

	// Unmarshal n
	var n uint8
	n, err = r.U8()
	if err != nil {
		return fmt.Errorf("n: %w", err)
	}

	// Unmarshal ReadPrim
	s.ReadPrim = make([]uint32, n)
	for i := range n {
		s.ReadPrim[i], err = r.U32()
		if err != nil {
			return fmt.Errorf("s.ReadPrim[i]: %w", err)
		}
	}

	// Unmarshal ReadByte
	s.ReadByte, err = r.Read(uint32(n))
	if err != nil {
		return fmt.Errorf("array buffer read failed: %w", err)
	}

	// Unmarshal ReadEnum
	s.ReadEnum = make([]EA, n)
	for i := range n {
		err = s.ReadEnum[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("EA unmarshal failed: %w", err)
		}
	}

	// Unmarshal FillPrim
	for {
		var i uint32
		i, err = r.U32()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			} else {
				return fmt.Errorf("i: %w", err)
			}
		}
		s.FillPrim = append(s.FillPrim, i)
	}

	// Unmarshal FillByte
	s.FillByte, err = r.Read(r.BytesLeft())
	if err != nil {
		return fmt.Errorf("array buffer read failed: %w", err)
	}

	// Unmarshal FillEnum
	for i := range 3 {
		err = s.FillEnum[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("EA unmarshal failed: %w", err)
		}
	}

	return nil
}

func (s *ArrayFlat) Marshal(wo *serial.Writer) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	if len(s.StaticPrim) != 3 {
		return fmt.Errorf("expected 'len(s.StaticPrim)' == 3, got %d", len(s.StaticPrim))
	}
	for _, i := range s.StaticPrim {
		w.U32(i)
	}
	if len(s.StaticByte) != 3 {
		return fmt.Errorf("expected 'len(s.StaticByte)' == 3, got %d", len(s.StaticByte))
	}
	w.Write(s.StaticByte)
	if len(s.StaticEnum) != 3 {
		return fmt.Errorf("expected 'len(s.StaticEnum)' == 3, got %d", len(s.StaticEnum))
	}
	for _, i := range s.StaticEnum {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("EA marshal failed: %w", err)
		}
	}
	w.U16(uint16(len(s.DyanmicPrim)))
	for _, i := range s.DyanmicPrim {
		w.U32(i)
	}
	w.U16(uint16(len(s.DynamicByte)))
	w.Write(s.DynamicByte)
	w.U16(uint16(len(s.DynamicEnum)))
	for _, i := range s.DynamicEnum {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("EA marshal failed: %w", err)
		}
	}
	n := uint8(0)
	w.U8(n)
	if len(s.ReadPrim) != int(n) {
		return fmt.Errorf("expected 'len(s.ReadPrim)' == n, %d != %d", len(s.ReadPrim), int(n))
	}
	for _, i := range s.ReadPrim {
		w.U32(i)
	}
	if len(s.ReadByte) != int(n) {
		return fmt.Errorf("expected 'len(s.ReadByte)' == n, %d != %d", len(s.ReadByte), int(n))
	}
	w.Write(s.ReadByte)
	if len(s.ReadEnum) != int(n) {
		return fmt.Errorf("expected 'len(s.ReadEnum)' == n, %d != %d", len(s.ReadEnum), int(n))
	}
	for _, i := range s.ReadEnum {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("EA marshal failed: %w", err)
		}
	}
	for _, i := range s.FillPrim {
		w.U32(i)
	}
	w.Write(s.FillByte)
	if len(s.FillEnum) != 3 {
		return fmt.Errorf("expected 'len(s.FillEnum)' == 3, got %d", len(s.FillEnum))
	}
	for _, i := range s.FillEnum {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("EA marshal failed: %w", err)
		}
	}
	return nil
}

type NestedArray struct {
	StaticStruct   [3]*ArrayFlat   `json:"static_struct"`
	StaticStatic   [3][3]uint16    `json:"static_static"`
	StaticDynamic  [3][]uint16     `json:"static_dynamic"`
	StaticFill     [3][]uint16     `json:"static_fill"`
	ReadNested     [3][]*ArrayFlat `json:"read_nested"`
	ReadInverse    [][3]uint16     `json:"read_inverse"`
	DynamicStruct  []*ArrayFlat    `json:"dynamic_struct"`
	DynamicStatic  [][3]uint16     `json:"dynamic_static"`
	DyanmicDynamic [][]uint16      `json:"dyanmic_dynamic"`
	DynamicFill    [][]uint16      `json:"dynamic_fill"`
	FillStruct     []*ArrayFlat    `json:"fill_struct"`
	FillStatic     [][3]uint16     `json:"fill_static"`
	FillDynamic    [][]uint16      `json:"fill_dynamic"`
	FillFill       [][]uint16      `json:"fill_fill"`
}

func (s *NestedArray) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal StaticStruct
	for i := range 3 {
		s.StaticStruct[i] = &ArrayFlat{}
		err = s.StaticStruct[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'ArrayFlat': %w", err)
		}
	}

	// Unmarshal StaticStatic
	for i := range 3 {
		for ii := range 3 {
			s.StaticStatic[i][ii], err = r.U16()
			if err != nil {
				return fmt.Errorf("s.StaticStatic[i][ii]: %w", err)
			}
		}
	}

	// Unmarshal StaticDynamic
	for i := range 3 {
		var s_StaticDynamic_iLen uint8
		s_StaticDynamic_iLen, err = r.U8()
		if err != nil {
			return fmt.Errorf("s_StaticDynamic_iLen: %w", err)
		}
		s.StaticDynamic[i] = make([]uint16, s_StaticDynamic_iLen)
		for ii := range s_StaticDynamic_iLen {
			s.StaticDynamic[i][ii], err = r.U16()
			if err != nil {
				return fmt.Errorf("s.StaticDynamic[i][ii]: %w", err)
			}
		}
	}

	// Unmarshal StaticFill
	for i := range 3 {
		for {
			var ii uint16
			ii, err = r.U16()
			if err != nil {
				if errors.Is(err, io.EOF) {
					break
				} else {
					return fmt.Errorf("ii: %w", err)
				}
			}
			s.StaticFill[i] = append(s.StaticFill[i], ii)
		}
	}

	// Unmarshal m
	var m uint8
	m, err = r.U8()
	if err != nil {
		return fmt.Errorf("m: %w", err)
	}

	// Unmarshal ReadNested
	for i := range 3 {
		s.ReadNested[i] = make([]*ArrayFlat, m)
		for ii := range m {
			s.ReadNested[i][ii] = &ArrayFlat{}
			err = s.ReadNested[i][ii].Unmarshal(r)
			if err != nil {
				return fmt.Errorf("unmarshal failed 'ArrayFlat': %w", err)
			}
		}
	}

	// Unmarshal ReadInverse
	s.ReadInverse = make([][3]uint16, m)
	for i := range m {
		for ii := range 3 {
			s.ReadInverse[i][ii], err = r.U16()
			if err != nil {
				return fmt.Errorf("s.ReadInverse[i][ii]: %w", err)
			}
		}
	}

	// Unmarshal DynamicStruct
	var s_DynamicStructLen uint8
	s_DynamicStructLen, err = r.U8()
	if err != nil {
		return fmt.Errorf("s_DynamicStructLen: %w", err)
	}
	s.DynamicStruct = make([]*ArrayFlat, s_DynamicStructLen)
	for i := range s_DynamicStructLen {
		s.DynamicStruct[i] = &ArrayFlat{}
		err = s.DynamicStruct[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'ArrayFlat': %w", err)
		}
	}

	// Unmarshal DynamicStatic
	var s_DynamicStaticLen uint8
	s_DynamicStaticLen, err = r.U8()
	if err != nil {
		return fmt.Errorf("s_DynamicStaticLen: %w", err)
	}
	s.DynamicStatic = make([][3]uint16, s_DynamicStaticLen)
	for i := range s_DynamicStaticLen {
		for ii := range 3 {
			s.DynamicStatic[i][ii], err = r.U16()
			if err != nil {
				return fmt.Errorf("s.DynamicStatic[i][ii]: %w", err)
			}
		}
	}

	// Unmarshal DyanmicDynamic
	var s_DyanmicDynamicLen uint8
	s_DyanmicDynamicLen, err = r.U8()
	if err != nil {
		return fmt.Errorf("s_DyanmicDynamicLen: %w", err)
	}
	s.DyanmicDynamic = make([][]uint16, s_DyanmicDynamicLen)
	for i := range s_DyanmicDynamicLen {
		var s_DyanmicDynamic_iLen uint8
		s_DyanmicDynamic_iLen, err = r.U8()
		if err != nil {
			return fmt.Errorf("s_DyanmicDynamic_iLen: %w", err)
		}
		s.DyanmicDynamic[i] = make([]uint16, s_DyanmicDynamic_iLen)
		for ii := range s_DyanmicDynamic_iLen {
			s.DyanmicDynamic[i][ii], err = r.U16()
			if err != nil {
				return fmt.Errorf("s.DyanmicDynamic[i][ii]: %w", err)
			}
		}
	}

	// Unmarshal DynamicFill
	var s_DynamicFillLen uint8
	s_DynamicFillLen, err = r.U8()
	if err != nil {
		return fmt.Errorf("s_DynamicFillLen: %w", err)
	}
	s.DynamicFill = make([][]uint16, s_DynamicFillLen)
	for i := range s_DynamicFillLen {
		for {
			var ii uint16
			ii, err = r.U16()
			if err != nil {
				if errors.Is(err, io.EOF) {
					break
				} else {
					return fmt.Errorf("ii: %w", err)
				}
			}
			s.DynamicFill[i] = append(s.DynamicFill[i], ii)
		}
	}

	// Unmarshal FillStruct
	for {
		var i *ArrayFlat
		i = &ArrayFlat{}
		err = i.Unmarshal(r)
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			} else {
				return fmt.Errorf("unmarshal failed 'ArrayFlat': %w", err)
			}
		}
		s.FillStruct = append(s.FillStruct, i)
	}

	// Unmarshal FillStatic
	for {
		var i [3]uint16
		for ii := range 3 {
			i[ii], err = r.U16()
			if err != nil {
				if errors.Is(err, io.EOF) {
					break
				} else {
					return fmt.Errorf("i[ii]: %w", err)
				}
			}
		}
		s.FillStatic = append(s.FillStatic, i)
	}

	// Unmarshal FillDynamic
	for {
		var i []uint16
		var iLen uint8
		iLen, err = r.U8()
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			} else {
				return fmt.Errorf("iLen: %w", err)
			}
		}
		i = make([]uint16, iLen)
		for ii := range iLen {
			i[ii], err = r.U16()
			if err != nil {
				if errors.Is(err, io.EOF) {
					break
				} else {
					return fmt.Errorf("i[ii]: %w", err)
				}
			}
		}
		s.FillDynamic = append(s.FillDynamic, i)
	}

	// Unmarshal FillFill
	for {
		var i []uint16
		for {
			var ii uint16
			ii, err = r.U16()
			if err != nil {
				if errors.Is(err, io.EOF) {
					break
				} else {
					return fmt.Errorf("ii: %w", err)
				}
			}
			i = append(i, ii)
		}
		s.FillFill = append(s.FillFill, i)
	}

	return nil
}

func (s *NestedArray) Marshal(wo *serial.Writer) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	if len(s.StaticStruct) != 3 {
		return fmt.Errorf("expected 'len(s.StaticStruct)' == 3, got %d", len(s.StaticStruct))
	}
	for _, i := range s.StaticStruct {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'ArrayFlat': %w", err)
		}
	}
	if len(s.StaticStatic) != 3 {
		return fmt.Errorf("expected 'len(s.StaticStatic)' == 3, got %d", len(s.StaticStatic))
	}
	for _, i := range s.StaticStatic {
		if len(i) != 3 {
			return fmt.Errorf("expected 'len(i)' == 3, got %d", len(i))
		}
		for _, ii := range i {
			w.U16(ii)
		}
	}
	if len(s.StaticDynamic) != 3 {
		return fmt.Errorf("expected 'len(s.StaticDynamic)' == 3, got %d", len(s.StaticDynamic))
	}
	for _, i := range s.StaticDynamic {
		w.U8(uint8(len(i)))
		for _, ii := range i {
			w.U16(ii)
		}
	}
	if len(s.StaticFill) != 3 {
		return fmt.Errorf("expected 'len(s.StaticFill)' == 3, got %d", len(s.StaticFill))
	}
	for _, i := range s.StaticFill {
		for _, ii := range i {
			w.U16(ii)
		}
	}
	m := uint8(0)
	w.U8(m)
	if len(s.ReadNested) != 3 {
		return fmt.Errorf("expected 'len(s.ReadNested)' == 3, got %d", len(s.ReadNested))
	}
	for _, i := range s.ReadNested {
		if len(i) != int(m) {
			return fmt.Errorf("expected 'len(i)' == m, %d != %d", len(i), int(m))
		}
		for _, ii := range i {
			err = ii.Marshal(w)
			if err != nil {
				return fmt.Errorf("marshal failed 'ArrayFlat': %w", err)
			}
		}
	}
	if len(s.ReadInverse) != int(m) {
		return fmt.Errorf("expected 'len(s.ReadInverse)' == m, %d != %d", len(s.ReadInverse), int(m))
	}
	for _, i := range s.ReadInverse {
		if len(i) != 3 {
			return fmt.Errorf("expected 'len(i)' == 3, got %d", len(i))
		}
		for _, ii := range i {
			w.U16(ii)
		}
	}
	w.U8(uint8(len(s.DynamicStruct)))
	for _, i := range s.DynamicStruct {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'ArrayFlat': %w", err)
		}
	}
	w.U8(uint8(len(s.DynamicStatic)))
	for _, i := range s.DynamicStatic {
		if len(i) != 3 {
			return fmt.Errorf("expected 'len(i)' == 3, got %d", len(i))
		}
		for _, ii := range i {
			w.U16(ii)
		}
	}
	w.U8(uint8(len(s.DyanmicDynamic)))
	for _, i := range s.DyanmicDynamic {
		w.U8(uint8(len(i)))
		for _, ii := range i {
			w.U16(ii)
		}
	}
	w.U8(uint8(len(s.DynamicFill)))
	for _, i := range s.DynamicFill {
		for _, ii := range i {
			w.U16(ii)
		}
	}
	for _, i := range s.FillStruct {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'ArrayFlat': %w", err)
		}
	}
	for _, i := range s.FillStatic {
		if len(i) != 3 {
			return fmt.Errorf("expected 'len(i)' == 3, got %d", len(i))
		}
		for _, ii := range i {
			w.U16(ii)
		}
	}
	for _, i := range s.FillDynamic {
		w.U8(uint8(len(i)))
		for _, ii := range i {
			w.U16(ii)
		}
	}
	for _, i := range s.FillFill {
		for _, ii := range i {
			w.U16(ii)
		}
	}
	return nil
}

const (
	EA_E1 EA = 1
	EA_E2 EA = 2
	EA_E3 EA = 3
)

type EA uint16

func (e *EA) Unmarshal(r *serial.Reader) (err error) {
	var raw uint16
	raw, err = r.U16()
	if err != nil {
		return fmt.Errorf("raw: %w", err)
	}
	*e = EA(raw)
	return nil
}

func (e *EA) Marshal(w *serial.Writer) (err error) {
	w.U16(uint16(*e))
	return nil
}

func (e EA) String() string {
	switch e {
	case EA_E1:
		return "E1"
	case EA_E2:
		return "E2"
	case EA_E3:
		return "E3"
	default:
		return strconv.FormatInt(int64(e), 10)
	}
}

func (e *EA) FromString(s string) error {
	switch s {
	case "E1":
		*e = EA_E1
		return nil
	case "E2":
		*e = EA_E2
		return nil
	case "E3":
		*e = EA_E3
		return nil
	default:
		return fmt.Errorf("'%s' is not a valid member of EA", s)
	}
}
