// Code generated by protocolc. DO NOT EDIT.

package test

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"strconv"

	"github.com/nasa/hermes/pkg/serial"
)

type BA struct {
	F1 E_BA   `json:"f1"`
	F2 uint8  `json:"f2"`
	F3 uint8  `json:"f3"`
	F4 uint16 `json:"f4"`
	F5 uint16 `json:"f5"`
	F6 uint32 `json:"f6"`
	F7 uint64 `json:"f7"`
}

func (s *BA) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	{
		raw, err := r.Read(15)
		if err != nil {
			return fmt.Errorf("failed to read bitmask value: %w", err)
		}

		// F1 (3 bits)
		F1Tmp := uint8(0)
		F1Tmp |= uint8((raw[0]>>5)&0x07) << 0
		s.F1 = E_BA(F1Tmp)
		// F2 (4 bits)
		F2Tmp := uint8(0)
		F2Tmp |= uint8((raw[0]>>1)&0x0F) << 0
		s.F2 = uint8(F2Tmp)
		// F3 (1 bits)
		F3Tmp := uint8(0)
		F3Tmp |= uint8((raw[0]>>0)&0x01) << 0
		s.F3 = uint8(F3Tmp)
		// F4 (9 bits)
		F4Tmp := uint16(0)
		F4Tmp |= uint16((raw[1]>>0)&0xFF) << 1
		F4Tmp |= uint16((raw[2]>>7)&0x01) << 0
		s.F4 = uint16(F4Tmp)
		// F5 (10 bits)
		F5Tmp := uint16(0)
		F5Tmp |= uint16((raw[2]>>0)&0x7F) << 3
		F5Tmp |= uint16((raw[3]>>5)&0x07) << 0
		s.F5 = uint16(F5Tmp)
		// <reserved> (5 bits)
		// F6 (32 bits)
		F6Tmp := uint32(0)
		F6Tmp |= uint32((raw[4]>>0)&0xFF) << 24
		F6Tmp |= uint32((raw[5]>>0)&0xFF) << 16
		F6Tmp |= uint32((raw[6]>>0)&0xFF) << 8
		F6Tmp |= uint32((raw[7]>>0)&0xFF) << 0
		s.F6 = uint32(F6Tmp)
		// <reserved> (2 bits)
		// F7 (57 bits)
		F7Tmp := uint64(0)
		F7Tmp |= uint64((raw[8]>>0)&0x3F) << 51
		F7Tmp |= uint64((raw[9]>>0)&0xFF) << 43
		F7Tmp |= uint64((raw[10]>>0)&0xFF) << 35
		F7Tmp |= uint64((raw[11]>>0)&0xFF) << 27
		F7Tmp |= uint64((raw[12]>>0)&0xFF) << 19
		F7Tmp |= uint64((raw[13]>>0)&0xFF) << 11
		F7Tmp |= uint64((raw[14]>>0)&0xFF) << 3
		F7Tmp |= uint64((raw[15]>>5)&0x07) << 0
		s.F7 = uint64(F7Tmp)
		// <left over> (3 bits)
	}

	return nil
}

func (s *BA) Marshal(wo *serial.Writer) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	{
		var raw [15]byte

		// F1 (3 bits)
		raw[0] |= byte(((uint8(s.F1) >> 0) & 0x07) << 5)
		// F2 (4 bits)
		raw[0] |= byte(((s.F2 >> 0) & 0x0F) << 1)
		// F3 (1 bits)
		raw[0] |= byte(((s.F3 >> 0) & 0x01) << 0)
		// F4 (9 bits)
		raw[1] |= byte(((s.F4 >> 1) & 0xFF) << 0)
		raw[2] |= byte(((s.F4 >> 0) & 0x01) << 7)
		// F5 (10 bits)
		raw[2] |= byte(((s.F5 >> 3) & 0x7F) << 0)
		raw[3] |= byte(((s.F5 >> 0) & 0x07) << 5)
		// <reserved> (5 bits)
		// F6 (32 bits)
		raw[4] |= byte(((s.F6 >> 24) & 0xFF) << 0)
		raw[5] |= byte(((s.F6 >> 16) & 0xFF) << 0)
		raw[6] |= byte(((s.F6 >> 8) & 0xFF) << 0)
		raw[7] |= byte(((s.F6 >> 0) & 0xFF) << 0)
		// <reserved> (2 bits)
		// F7 (57 bits)
		raw[8] |= byte(((s.F7 >> 51) & 0x3F) << 0)
		raw[9] |= byte(((s.F7 >> 43) & 0xFF) << 0)
		raw[10] |= byte(((s.F7 >> 35) & 0xFF) << 0)
		raw[11] |= byte(((s.F7 >> 27) & 0xFF) << 0)
		raw[12] |= byte(((s.F7 >> 19) & 0xFF) << 0)
		raw[13] |= byte(((s.F7 >> 11) & 0xFF) << 0)
		raw[14] |= byte(((s.F7 >> 3) & 0xFF) << 0)
		raw[15] |= byte(((s.F7 >> 0) & 0x07) << 5)
		// <left over> (3 bits)

		w.Write(raw[:])
	}
	return nil
}

type S_BA struct {
	M   *BA    `json:"m"`
	M3  [3]*BA `json:"m3"`
	MD  []*BA  `json:"md"`
	MDF []*BA  `json:"mdf"`
	MF  []*BA  `json:"mf"`
}

func (s *S_BA) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal M
	s.M = &BA{}
	err = s.M.Unmarshal(r)
	if err != nil {
		return fmt.Errorf("unmarshal failed 'BA': %w", err)
	}

	// Unmarshal M3
	for i := range 3 {
		s.M3[i] = &BA{}
		err = s.M3[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'BA': %w", err)
		}
	}

	// Unmarshal MD
	var s_MDLen uint8
	s_MDLen, err = r.U8()
	if err != nil {
		return fmt.Errorf("s_MDLen: %w", err)
	}
	s.MD = make([]*BA, s_MDLen)
	for i := range s_MDLen {
		s.MD[i] = &BA{}
		err = s.MD[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'BA': %w", err)
		}
	}

	// Unmarshal MDF
	s.MDF = make([]*BA, s.M.F5)
	for i := range s.M.F5 {
		s.MDF[i] = &BA{}
		err = s.MDF[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'BA': %w", err)
		}
	}

	// Unmarshal MF
	for {
		var i *BA
		i = &BA{}
		err = i.Unmarshal(r)
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			} else {
				return fmt.Errorf("unmarshal failed 'BA': %w", err)
			}
		}
		s.MF = append(s.MF, i)
	}

	return nil
}

func (s *S_BA) Marshal(wo *serial.Writer) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	err = s.M.Marshal(w)
	if err != nil {
		return fmt.Errorf("marshal failed 'BA': %w", err)
	}
	if len(s.M3) != 3 {
		return fmt.Errorf("expected 'len(s.M3)' == 3, got %d", len(s.M3))
	}
	for _, i := range s.M3 {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'BA': %w", err)
		}
	}
	w.U8(uint8(len(s.MD)))
	for _, i := range s.MD {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'BA': %w", err)
		}
	}
	if len(s.MDF) != int(s.M.F5) {
		return fmt.Errorf("expected 'len(s.MDF)' == s.M.F5, %d != %d", len(s.MDF), int(s.M.F5))
	}
	for _, i := range s.MDF {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'BA': %w", err)
		}
	}
	for _, i := range s.MF {
		err = i.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'BA': %w", err)
		}
	}
	return nil
}

const (
	E_BA_OPTION_0 E_BA = 0
	E_BA_OPTION_1 E_BA = 1
	E_BA_OPTION_2 E_BA = 2
	E_BA_OPTION_3 E_BA = 3
)

type E_BA uint8

func (e *E_BA) Unmarshal(r *serial.Reader) (err error) {
	var raw uint8
	raw, err = r.U8()
	if err != nil {
		return fmt.Errorf("raw: %w", err)
	}
	*e = E_BA(raw)
	return nil
}

func (e *E_BA) Marshal(w *serial.Writer) (err error) {
	w.U8(uint8(*e))
	return nil
}

func (e E_BA) String() string {
	switch e {
	case E_BA_OPTION_0:
		return "OPTION_0"
	case E_BA_OPTION_1:
		return "OPTION_1"
	case E_BA_OPTION_2:
		return "OPTION_2"
	case E_BA_OPTION_3:
		return "OPTION_3"
	default:
		return strconv.FormatInt(int64(e), 10)
	}
}

func (e *E_BA) FromString(s string) error {
	switch s {
	case "OPTION_0":
		*e = E_BA_OPTION_0
		return nil
	case "OPTION_1":
		*e = E_BA_OPTION_1
		return nil
	case "OPTION_2":
		*e = E_BA_OPTION_2
		return nil
	case "OPTION_3":
		*e = E_BA_OPTION_3
		return nil
	default:
		return fmt.Errorf("'%s' is not a valid member of E_BA", s)
	}
}
