// Code generated by protocolc. DO NOT EDIT.

package test

import (
	"encoding/binary"
	"errors"
	"fmt"
	"io"

	"github.com/nasa/hermes/pkg/serial"
)

type Inner struct {
	InnerField  uint8    `json:"inner_field"`
	ArrayField  []uint32 `json:"array_field"`
	ArrayField2 []uint32 `json:"array_field2"`
}

func (s *Inner) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.LittleEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal InnerField
	s.InnerField, err = r.U8()
	if err != nil {
		return fmt.Errorf("s.InnerField: %w", err)
	}

	// Unmarshal pField
	var pField uint32
	pField, err = r.U32()
	if err != nil {
		return fmt.Errorf("pField: %w", err)
	}

	// Unmarshal ArrayField
	s.ArrayField = make([]uint32, pField)
	for i := range pField {
		s.ArrayField[i], err = r.U32()
		if err != nil {
			return fmt.Errorf("s.ArrayField[i]: %w", err)
		}
	}

	// Unmarshal piField
	var piField uint32
	piField, err = r.U32()
	if err != nil {
		return fmt.Errorf("piField: %w", err)
	}

	// Unmarshal ArrayField2
	s.ArrayField2 = make([]uint32, piField)
	for i := range piField {
		s.ArrayField2[i], err = r.U32()
		if err != nil {
			return fmt.Errorf("s.ArrayField2[i]: %w", err)
		}
	}

	return nil
}

func (s *Inner) Marshal(wo *serial.Writer, pField uint32) (err error) {
	w := wo.WithByteOrder(binary.LittleEndian)
	defer func() { wo.Set(w.Get()) }()

	w.U8(s.InnerField)
	w.U32(pField)
	if len(s.ArrayField) != int(pField) {
		return fmt.Errorf("expected 'len(s.ArrayField)' == pField, %d != %d", len(s.ArrayField), int(pField))
	}
	for _, i := range s.ArrayField {
		w.U32(i)
	}
	piField := uint32(len(s.ArrayField2))
	w.U32(piField)
	if len(s.ArrayField2) != int(piField) {
		return fmt.Errorf("expected 'len(s.ArrayField2)' == piField, %d != %d", len(s.ArrayField2), int(piField))
	}
	for _, i := range s.ArrayField2 {
		w.U32(i)
	}
	return nil
}

type Outer struct {
	Nested       *Inner    `json:"nested"`
	Divider      float32   `json:"divider"`
	Another      *Inner    `json:"another"`
	ArrayStatic  [3]*Inner `json:"array_static"`
	ArrayDynamic []*Inner  `json:"array_dynamic"`
	Fill         []*Inner  `json:"fill"`
}

func (s *Outer) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal Nested
	s.Nested = &Inner{}
	err = s.Nested.Unmarshal(r)
	if err != nil {
		return fmt.Errorf("unmarshal failed 'Inner': %w", err)
	}

	// Unmarshal Divider
	s.Divider, err = r.F32()
	if err != nil {
		return fmt.Errorf("s.Divider: %w", err)
	}

	// Unmarshal Another
	s.Another = &Inner{}
	err = s.Another.Unmarshal(r)
	if err != nil {
		return fmt.Errorf("unmarshal failed 'Inner': %w", err)
	}

	// Unmarshal ArrayStatic
	for i := range 3 {
		s.ArrayStatic[i] = &Inner{}
		err = s.ArrayStatic[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'Inner': %w", err)
		}
	}

	// Unmarshal ArrayDynamic
	var s_ArrayDynamicLen uint8
	s_ArrayDynamicLen, err = r.U8()
	if err != nil {
		return fmt.Errorf("s_ArrayDynamicLen: %w", err)
	}
	s.ArrayDynamic = make([]*Inner, s_ArrayDynamicLen)
	for i := range s_ArrayDynamicLen {
		s.ArrayDynamic[i] = &Inner{}
		err = s.ArrayDynamic[i].Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'Inner': %w", err)
		}
	}

	// Unmarshal Fill
	for {
		var i *Inner
		i = &Inner{}
		err = i.Unmarshal(r)
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			} else {
				return fmt.Errorf("unmarshal failed 'Inner': %w", err)
			}
		}
		s.Fill = append(s.Fill, i)
	}

	return nil
}

func (s *Outer) Marshal(wo *serial.Writer, s_Nested_pField uint32, s_Another_pField uint32, i_pField uint32) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	err = s.Nested.Marshal(w, s_Nested_pField)
	if err != nil {
		return fmt.Errorf("marshal failed 'Inner': %w", err)
	}
	w.F32(s.Divider)
	err = s.Another.Marshal(w, s_Another_pField)
	if err != nil {
		return fmt.Errorf("marshal failed 'Inner': %w", err)
	}
	if len(s.ArrayStatic) != 3 {
		return fmt.Errorf("expected 'len(s.ArrayStatic)' == 3, got %d", len(s.ArrayStatic))
	}
	for _, i := range s.ArrayStatic {
		err = i.Marshal(w, i_pField)
		if err != nil {
			return fmt.Errorf("marshal failed 'Inner': %w", err)
		}
	}
	w.U8(uint8(len(s.ArrayDynamic)))
	for _, i := range s.ArrayDynamic {
		err = i.Marshal(w, i_pField)
		if err != nil {
			return fmt.Errorf("marshal failed 'Inner': %w", err)
		}
	}
	for _, i := range s.Fill {
		err = i.Marshal(w, i_pField)
		if err != nil {
			return fmt.Errorf("marshal failed 'Inner': %w", err)
		}
	}
	return nil
}
