// Code generated by protocolc. DO NOT EDIT.

package test

import (
	"encoding/binary"
	"fmt"

	"github.com/nasa/hermes/pkg/serial"
)

type S_Pad struct {
	I uint32 `json:"i"`
	U uint64 `json:"u"`
}

func (s *S_Pad) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal I
	s.I, err = r.U32()
	if err != nil {
		return fmt.Errorf("s.I: %w", err)
	}

	_, err = r.Read(4)
	if err != nil {
		return fmt.Errorf("pad read failed: %w", err)
	}

	// Unmarshal U
	s.U, err = r.U64()
	if err != nil {
		return fmt.Errorf("s.U: %w", err)
	}

	return nil
}

func (s *S_Pad) Marshal(wo *serial.Writer) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	w.U32(s.I)
	w.Write(make([]byte, 4))
	w.U64(s.U)
	return nil
}
