// Code generated by protocolc. DO NOT EDIT.

package test

import (
	"encoding/binary"
	"fmt"

	"github.com/nasa/hermes/pkg/serial"
)

type S_Primitive struct {
	F1  uint8   `json:"f1"`
	F2  int8    `json:"f2"`
	F3  uint16  `json:"f3"`
	F4  int16   `json:"f4"`
	F5  uint32  `json:"f5"`
	F6  int32   `json:"f6"`
	F7  uint64  `json:"f7"`
	F8  int64   `json:"f8"`
	F9  float32 `json:"f9"`
	F10 float64 `json:"f10"`
	F12 []byte  `json:"f12"`
}

func (s *S_Primitive) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal F1
	s.F1, err = r.U8()
	if err != nil {
		return fmt.Errorf("s.F1: %w", err)
	}

	// Unmarshal F2
	s.F2, err = r.I8()
	if err != nil {
		return fmt.Errorf("s.F2: %w", err)
	}

	// Unmarshal F3
	s.F3, err = r.U16()
	if err != nil {
		return fmt.Errorf("s.F3: %w", err)
	}

	// Unmarshal F4
	s.F4, err = r.I16()
	if err != nil {
		return fmt.Errorf("s.F4: %w", err)
	}

	// Unmarshal F5
	s.F5, err = r.U32()
	if err != nil {
		return fmt.Errorf("s.F5: %w", err)
	}

	// Unmarshal F6
	s.F6, err = r.I32()
	if err != nil {
		return fmt.Errorf("s.F6: %w", err)
	}

	// Unmarshal F7
	s.F7, err = r.U64()
	if err != nil {
		return fmt.Errorf("s.F7: %w", err)
	}

	// Unmarshal F8
	s.F8, err = r.I64()
	if err != nil {
		return fmt.Errorf("s.F8: %w", err)
	}

	// Unmarshal F9
	s.F9, err = r.F32()
	if err != nil {
		return fmt.Errorf("s.F9: %w", err)
	}

	// Unmarshal F10
	s.F10, err = r.F64()
	if err != nil {
		return fmt.Errorf("s.F10: %w", err)
	}

	// Unmarshal f11
	var f11 uint8
	f11, err = r.U8()
	if err != nil {
		return fmt.Errorf("f11: %w", err)
	}

	// Unmarshal F12
	s.F12, err = r.Read(uint32(f11))
	if err != nil {
		return fmt.Errorf("array buffer read failed: %w", err)
	}

	return nil
}

func (s *S_Primitive) Marshal(wo *serial.Writer, f11 uint8) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	w.U8(s.F1)
	w.I8(s.F2)
	w.U16(s.F3)
	w.I16(s.F4)
	w.U32(s.F5)
	w.I32(s.F6)
	w.U64(s.F7)
	w.I64(s.F8)
	w.F32(s.F9)
	w.F64(s.F10)
	w.U8(f11)
	if len(s.F12) != int(f11) {
		return fmt.Errorf("expected 'len(s.F12)' == f11, %d != %d", len(s.F12), int(f11))
	}
	w.Write(s.F12)
	return nil
}
