// Code generated by protocolc. DO NOT EDIT.

package test

import (
	"encoding/binary"
	"fmt"
	"strconv"

	"github.com/nasa/hermes/pkg/serial"
)

type S_TypeCase struct {
	Kind    TypeCaseKind `json:"kind"`
	Payload any          `json:"payload"`
}

func (s *S_TypeCase) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal Kind
	err = s.Kind.Unmarshal(r)
	if err != nil {
		return fmt.Errorf("TypeCaseKind unmarshal failed: %w", err)
	}

	// Unmarshal Payload
	switch {
	case s.Kind == TypeCaseKind_C1:
		var s_Payload *TC1
		_ = s_Payload
		s_Payload = &TC1{}
		err = s_Payload.Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'TC1': %w", err)
		}
		s.Payload = s_Payload
	case s.Kind == TypeCaseKind_C2:
		var s_Payload *TC2
		_ = s_Payload
		s_Payload = &TC2{}
		err = s_Payload.Unmarshal(r)
		if err != nil {
			return fmt.Errorf("unmarshal failed 'TC2': %w", err)
		}
		s.Payload = s_Payload
	default:
		var s_Payload []byte
		_ = s_Payload
		var s_PayloadTmp []byte
		s_PayloadTmp, err = r.Read(r.BytesLeft())
		if err != nil {
			return fmt.Errorf("array buffer read failed: %w", err)
		}
		if len(s_PayloadTmp) > 0 {
			return fmt.Errorf("invalid type case: %v", s.Kind)
		}
		s.Payload = s_Payload
	}

	return nil
}

func (s *S_TypeCase) Marshal(wo *serial.Writer) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	err = s.Kind.Marshal(w)
	if err != nil {
		return fmt.Errorf("TypeCaseKind marshal failed: %w", err)
	}
	switch {
	case s.Kind == TypeCaseKind_C1:
		s_Payload, ok := s.Payload.(*TC1)
		_ = s_Payload
		if !ok {
			return fmt.Errorf("expected s.Payload to be *TC1, got %T", s.Payload)
		}
		err = s_Payload.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'TC1': %w", err)
		}
	case s.Kind == TypeCaseKind_C2:
		s_Payload, ok := s.Payload.(*TC2)
		_ = s_Payload
		if !ok {
			return fmt.Errorf("expected s.Payload to be *TC2, got %T", s.Payload)
		}
		err = s_Payload.Marshal(w)
		if err != nil {
			return fmt.Errorf("marshal failed 'TC2': %w", err)
		}
	default:
		s_Payload, ok := s.Payload.([]byte)
		_ = s_Payload
		if !ok {
			return fmt.Errorf("expected s.Payload to be []byte, got %T", s.Payload)
		}
	}
	return nil
}

type TC1 struct {
	F1   uint32   `json:"f1"`
	F2   [][]byte `json:"f2"`
	Rest []byte   `json:"rest"`
}

func (s *TC1) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal F1
	s.F1, err = r.U32()
	if err != nil {
		return fmt.Errorf("s.F1: %w", err)
	}

	// Unmarshal F2
	var s_F2Len uint8
	s_F2Len, err = r.U8()
	if err != nil {
		return fmt.Errorf("s_F2Len: %w", err)
	}
	s.F2 = make([][]byte, s_F2Len)
	for i := range s_F2Len {
		var s_F2_iLen uint8
		s_F2_iLen, err = r.U8()
		if err != nil {
			return fmt.Errorf("s_F2_iLen: %w", err)
		}
		s.F2[i], err = r.Read(uint32(s_F2_iLen))
		if err != nil {
			return fmt.Errorf("array buffer read failed: %w", err)
		}
	}

	// Unmarshal Rest
	s.Rest, err = r.Read(r.BytesLeft())
	if err != nil {
		return fmt.Errorf("array buffer read failed: %w", err)
	}

	return nil
}

func (s *TC1) Marshal(wo *serial.Writer) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	w.U32(s.F1)
	w.U8(uint8(len(s.F2)))
	for _, i := range s.F2 {
		w.U8(uint8(len(i)))
		w.Write(i)
	}
	w.Write(s.Rest)
	return nil
}

type TC2 struct {
	F1 uint32 `json:"f1"`
	F2 int32  `json:"f2"`
	F3 []byte `json:"f3"`
}

func (s *TC2) Unmarshal(ro *serial.Reader) (err error) {
	r := ro.WithByteOrder(binary.BigEndian)
	defer func() { ro.SetOffset(r.Offset()) }()

	// Unmarshal F1
	s.F1, err = r.U32()
	if err != nil {
		return fmt.Errorf("s.F1: %w", err)
	}

	// Unmarshal F2
	s.F2, err = r.I32()
	if err != nil {
		return fmt.Errorf("s.F2: %w", err)
	}

	// Unmarshal F3
	var s_F3Len uint16
	s_F3Len, err = r.U16()
	if err != nil {
		return fmt.Errorf("s_F3Len: %w", err)
	}
	s.F3, err = r.Read(uint32(s_F3Len))
	if err != nil {
		return fmt.Errorf("array buffer read failed: %w", err)
	}

	return nil
}

func (s *TC2) Marshal(wo *serial.Writer) (err error) {
	w := wo.WithByteOrder(binary.BigEndian)
	defer func() { wo.Set(w.Get()) }()

	w.U32(s.F1)
	w.I32(s.F2)
	w.U16(uint16(len(s.F3)))
	w.Write(s.F3)
	return nil
}

const (
	TypeCaseKind_C1 TypeCaseKind = 1
	TypeCaseKind_C2 TypeCaseKind = 2
)

type TypeCaseKind uint16

func (e *TypeCaseKind) Unmarshal(r *serial.Reader) (err error) {
	var raw uint16
	raw, err = r.U16()
	if err != nil {
		return fmt.Errorf("raw: %w", err)
	}
	*e = TypeCaseKind(raw)
	return nil
}

func (e *TypeCaseKind) Marshal(w *serial.Writer) (err error) {
	w.U16(uint16(*e))
	return nil
}

func (e TypeCaseKind) String() string {
	switch e {
	case TypeCaseKind_C1:
		return "C1"
	case TypeCaseKind_C2:
		return "C2"
	default:
		return strconv.FormatInt(int64(e), 10)
	}
}

func (e *TypeCaseKind) FromString(s string) error {
	switch s {
	case "C1":
		*e = TypeCaseKind_C1
		return nil
	case "C2":
		*e = TypeCaseKind_C2
		return nil
	default:
		return fmt.Errorf("'%s' is not a valid member of TypeCaseKind", s)
	}
}
