// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	host "github.com/nasa/hermes/pkg/host"
)

// MockProfileProvider is an autogenerated mock type for the ProfileProvider type
type MockProfileProvider[T interface{}] struct {
	mock.Mock
}

type MockProfileProvider_Expecter[T interface{}] struct {
	mock *mock.Mock
}

func (_m *MockProfileProvider[T]) EXPECT() *MockProfileProvider_Expecter[T] {
	return &MockProfileProvider_Expecter[T]{mock: &_m.Mock}
}

// Default provides a mock function with no fields
func (_m *MockProfileProvider[T]) Default() T {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Default")
	}

	var r0 T
	if rf, ok := ret.Get(0).(func() T); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	return r0
}

// MockProfileProvider_Default_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Default'
type MockProfileProvider_Default_Call[T interface{}] struct {
	*mock.Call
}

// Default is a helper method to define mock.On call
func (_e *MockProfileProvider_Expecter[T]) Default() *MockProfileProvider_Default_Call[T] {
	return &MockProfileProvider_Default_Call[T]{Call: _e.mock.On("Default")}
}

func (_c *MockProfileProvider_Default_Call[T]) Run(run func()) *MockProfileProvider_Default_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProfileProvider_Default_Call[T]) Return(_a0 T) *MockProfileProvider_Default_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileProvider_Default_Call[T]) RunAndReturn(run func() T) *MockProfileProvider_Default_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx, settings, session
func (_m *MockProfileProvider[T]) Start(ctx context.Context, settings T, session host.ConnectSession) error {
	ret := _m.Called(ctx, settings, session)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T, host.ConnectSession) error); ok {
		r0 = rf(ctx, settings, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProfileProvider_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockProfileProvider_Start_Call[T interface{}] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - settings T
//   - session host.ConnectSession
func (_e *MockProfileProvider_Expecter[T]) Start(ctx interface{}, settings interface{}, session interface{}) *MockProfileProvider_Start_Call[T] {
	return &MockProfileProvider_Start_Call[T]{Call: _e.mock.On("Start", ctx, settings, session)}
}

func (_c *MockProfileProvider_Start_Call[T]) Run(run func(ctx context.Context, settings T, session host.ConnectSession)) *MockProfileProvider_Start_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T), args[2].(host.ConnectSession))
	})
	return _c
}

func (_c *MockProfileProvider_Start_Call[T]) Return(_a0 error) *MockProfileProvider_Start_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProfileProvider_Start_Call[T]) RunAndReturn(run func(context.Context, T, host.ConnectSession) error) *MockProfileProvider_Start_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileProvider creates a new instance of MockProfileProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileProvider[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileProvider[T] {
	mock := &MockProfileProvider[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
