// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: yamcs/protobuf/events/events_service.proto

package events

import (
	api "github.com/nasa/hermes/internal/yamcspb/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Yamcs instance name
	Instance *string `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	// The zero-based row number at which to start outputting results.
	// Default: `0`
	//
	// This option is deprecated and will be removed in a later version.
	// Use the returned continuationToken instead.
	//
	// Deprecated: Marked as deprecated in yamcs/protobuf/events/events_service.proto.
	Pos *int64 `protobuf:"varint,2,opt,name=pos" json:"pos,omitempty"`
	// The maximum number of returned records per page. Choose this value too high
	// and you risk hitting the maximum response size limit enforced by the server.
	// Default: `100`
	Limit *int32 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	// The order of the returned results. Can be either `asc` or `desc`.
	// Default: `desc`
	Order *string `protobuf:"bytes,4,opt,name=order" json:"order,omitempty"`
	// The minimum severity level of the events. One of `info`, `watch`, `warning`,
	// `distress`, `critical` or `severe`. Default: `info`
	Severity *string `protobuf:"bytes,5,opt,name=severity" json:"severity,omitempty"`
	// The source of the events. Names must match exactly.
	Source []string `protobuf:"bytes,6,rep,name=source" json:"source,omitempty"`
	// Continuation token returned by a previous page response.
	Next *string `protobuf:"bytes,7,opt,name=next" json:"next,omitempty"`
	// Filter the lower bound of the event's generation time. Specify a date string in
	// ISO 8601 format. This bound is inclusive.
	Start *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start" json:"start,omitempty"`
	// Filter the upper bound of the event's generation time. Specify a date string in
	// ISO 8601 format. This bound is exclusive.
	Stop *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=stop" json:"stop,omitempty"`
	// Text to search for in the message.
	Q *string `protobuf:"bytes,10,opt,name=q" json:"q,omitempty"`
	// Filter query. See {doc}`../filtering` for how to write a filter query.
	//
	// Literal text search matches against the `message`, `source` and `type`
	// fields. Field comparisons can use any of the following fields:
	//
	// | Field       | Type   | Description                        |
	// | ----------- | ------ | ---------------------------------- |
	// | `message`   | string | Filter by message text             |
	// | `seqNumber` | number | Filter by archived sequence number |
	// | `severity`  | enum   | Filter by event severity           |
	// | `source`    | string | Filter by event source             |
	// | `type`      | string | Filter by event type               |
	//
	// Possible severities: `info`, `watch`, `warning`, `distress`, `critical`
	// or `severe`.
	Filter        *string `protobuf:"bytes,11,opt,name=filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_events_events_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListEventsRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

// Deprecated: Marked as deprecated in yamcs/protobuf/events/events_service.proto.
func (x *ListEventsRequest) GetPos() int64 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *ListEventsRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *ListEventsRequest) GetSource() []string {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ListEventsRequest) GetNext() string {
	if x != nil && x.Next != nil {
		return *x.Next
	}
	return ""
}

func (x *ListEventsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ListEventsRequest) GetStop() *timestamppb.Timestamp {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ListEventsRequest) GetQ() string {
	if x != nil && x.Q != nil {
		return *x.Q
	}
	return ""
}

func (x *ListEventsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

type ListEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated, use `events` instead
	//
	// Deprecated: Marked as deprecated in yamcs/protobuf/events/events_service.proto.
	Event []*Event `protobuf:"bytes,1,rep,name=event" json:"event,omitempty"`
	// Page with matching events
	Events []*Event `protobuf:"bytes,3,rep,name=events" json:"events,omitempty"`
	// Token indicating the response is only partial. More results can then
	// be obtained by performing the same request (including all original
	// query parameters) and setting the `next` parameter to this token.
	ContinuationToken *string `protobuf:"bytes,2,opt,name=continuationToken" json:"continuationToken,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_events_events_service_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in yamcs/protobuf/events/events_service.proto.
func (x *ListEventsResponse) GetEvent() []*Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetContinuationToken() string {
	if x != nil && x.ContinuationToken != nil {
		return *x.ContinuationToken
	}
	return ""
}

type SubscribeEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Yamcs instance name
	Instance *string `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	// Filter query. See {doc}`../filtering` for how to write a filter query.
	//
	// Literal text search matches against the `message`, `source` and `type`
	// fields. Field comparisons can use any of the following fields:
	//
	// | Field       | Type   | Description                        |
	// | ----------- | ------ | ---------------------------------- |
	// | `message`   | string | Filter by message text             |
	// | `seqNumber` | number | Filter by archived sequence number |
	// | `severity`  | enum   | Filter by event severity           |
	// | `source`    | string | Filter by event source             |
	// | `type`      | string | Filter by event type               |
	//
	// Possible severities: `info`, `watch`, `warning`, `distress`, `critical`
	// or `severe`.
	Filter        *string `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_events_events_service_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeEventsRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *SubscribeEventsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

type CreateEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Yamcs instance name
	Instance *string `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	// Description of the type of the event. Useful for quick classification or filtering.
	Type *string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// **Required.** Event message.
	Message *string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	// The severity level of the event. One of `info`, `watch`, `warning`,
	// `distress`, `critical` or `severe`. Default is `info`
	Severity *string `protobuf:"bytes,4,opt,name=severity" json:"severity,omitempty"`
	// Time associated with the event.
	// If unspecified, this will default to the current mission time.
	Time *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=time" json:"time,omitempty"`
	// Source of the event. Useful for grouping events in the archive. Default is
	// `User`.
	Source *string `protobuf:"bytes,6,opt,name=source" json:"source,omitempty"`
	// Sequence number of this event. This is primarily used to determine unicity of
	// events coming from the same source. If not set Yamcs will automatically
	// assign a sequential number as if every submitted event is unique.
	SequenceNumber *int32 `protobuf:"varint,7,opt,name=sequenceNumber" json:"sequenceNumber,omitempty"`
	// Additional properties
	Extra         map[string]string `protobuf:"bytes,8,rep,name=extra" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_events_events_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEventRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *CreateEventRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *CreateEventRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *CreateEventRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *CreateEventRequest) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CreateEventRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *CreateEventRequest) GetSequenceNumber() int32 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *CreateEventRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Yamcs instance name
	Instance *string `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	// Filter the lower bound of the event's generation time. Specify a date
	// string in ISO 8601 format.
	Start *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	// Filter the upper bound of the event's generation time. Specify a date
	// string in ISO 8601 format.
	Stop *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=stop" json:"stop,omitempty"`
	// Event sources to include. Leave unset, to include all.
	Source []string `protobuf:"bytes,4,rep,name=source" json:"source,omitempty"`
	// Filter on minimum severity level
	Severity *string `protobuf:"bytes,5,opt,name=severity" json:"severity,omitempty"`
	// Search by text
	Q *string `protobuf:"bytes,6,opt,name=q" json:"q,omitempty"`
	// Filter query. See {doc}`../filtering` for how to write a filter query.
	//
	// Literal text search matches against the `message`, `source` and `type`
	// fields. Field comparisons can use any of the following fields:
	//
	// | Field       | Type   | Description                        |
	// | ----------- | ------ | ---------------------------------- |
	// | `message`   | string | Filter by message text             |
	// | `seqNumber` | number | Filter by archived sequence number |
	// | `severity`  | enum   | Filter by event severity           |
	// | `source`    | string | Filter by event source             |
	// | `type`      | string | Filter by event type               |
	//
	// Possible severities: `info`, `watch`, `warning`, `distress`, `critical`
	// or `severe`.
	Filter        *string `protobuf:"bytes,7,opt,name=filter" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_events_events_service_proto_rawDescGZIP(), []int{4}
}

func (x *StreamEventsRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *StreamEventsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *StreamEventsRequest) GetStop() *timestamppb.Timestamp {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *StreamEventsRequest) GetSource() []string {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *StreamEventsRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *StreamEventsRequest) GetQ() string {
	if x != nil && x.Q != nil {
		return *x.Q
	}
	return ""
}

func (x *StreamEventsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

type ListEventSourcesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Yamcs instance name
	Instance      *string `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventSourcesRequest) Reset() {
	*x = ListEventSourcesRequest{}
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventSourcesRequest) ProtoMessage() {}

func (x *ListEventSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListEventSourcesRequest) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_events_events_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListEventSourcesRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

type ListEventSourcesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated, use `sources` instead
	//
	// Deprecated: Marked as deprecated in yamcs/protobuf/events/events_service.proto.
	Source []string `protobuf:"bytes,1,rep,name=source" json:"source,omitempty"`
	// Known event sources
	Sources       []string `protobuf:"bytes,2,rep,name=sources" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventSourcesResponse) Reset() {
	*x = ListEventSourcesResponse{}
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventSourcesResponse) ProtoMessage() {}

func (x *ListEventSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListEventSourcesResponse) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_events_events_service_proto_rawDescGZIP(), []int{6}
}

// Deprecated: Marked as deprecated in yamcs/protobuf/events/events_service.proto.
func (x *ListEventSourcesResponse) GetSource() []string {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ListEventSourcesResponse) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ExportEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Yamcs instance name
	Instance *string `protobuf:"bytes,1,opt,name=instance" json:"instance,omitempty"`
	// Filter the lower bound of the event's generation time.
	// Specify a date string in ISO 8601 format. This bound is inclusive.
	Start *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start" json:"start,omitempty"`
	// Filter the upper bound of the event's generation time. Specify a date
	// string in ISO 8601 format. This bound is exclusive.
	Stop *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=stop" json:"stop,omitempty"`
	// The source of the events. Names must match exactly.
	Source []string `protobuf:"bytes,4,rep,name=source" json:"source,omitempty"`
	// The minimum severity level of the events. One of `info`, `watch`,
	// `warning`, `distress` or `severe`. Default: `info`
	Severity *string `protobuf:"bytes,5,opt,name=severity" json:"severity,omitempty"`
	// Text to search for in the message.
	Q *string `protobuf:"bytes,6,opt,name=q" json:"q,omitempty"`
	// Filter query. See {doc}`../filtering` for how to write a filter query.
	//
	// Literal text search matches against the `message`, `source` and `type`
	// fields. Field comparisons can use any of the following fields:
	//
	// | Field       | Type   | Description                        |
	// | ----------- | ------ | ---------------------------------- |
	// | `message`   | string | Filter by message text             |
	// | `seqNumber` | number | Filter by archived sequence number |
	// | `severity`  | enum   | Filter by event severity           |
	// | `source`    | string | Filter by event source             |
	// | `type`      | string | Filter by event type               |
	//
	// Possible severities: `info`, `watch`, `warning`, `distress`, `critical`
	// or `severe`.
	Filter *string `protobuf:"bytes,8,opt,name=filter" json:"filter,omitempty"`
	// Column delimiter. One of `TAB`, `COMMA` or `SEMICOLON`.
	// Default: `TAB`.
	Delimiter     *string `protobuf:"bytes,7,opt,name=delimiter" json:"delimiter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportEventsRequest) Reset() {
	*x = ExportEventsRequest{}
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEventsRequest) ProtoMessage() {}

func (x *ExportEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yamcs_protobuf_events_events_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEventsRequest.ProtoReflect.Descriptor instead.
func (*ExportEventsRequest) Descriptor() ([]byte, []int) {
	return file_yamcs_protobuf_events_events_service_proto_rawDescGZIP(), []int{7}
}

func (x *ExportEventsRequest) GetInstance() string {
	if x != nil && x.Instance != nil {
		return *x.Instance
	}
	return ""
}

func (x *ExportEventsRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ExportEventsRequest) GetStop() *timestamppb.Timestamp {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ExportEventsRequest) GetSource() []string {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ExportEventsRequest) GetSeverity() string {
	if x != nil && x.Severity != nil {
		return *x.Severity
	}
	return ""
}

func (x *ExportEventsRequest) GetQ() string {
	if x != nil && x.Q != nil {
		return *x.Q
	}
	return ""
}

func (x *ExportEventsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *ExportEventsRequest) GetDelimiter() string {
	if x != nil && x.Delimiter != nil {
		return *x.Delimiter
	}
	return ""
}

var File_yamcs_protobuf_events_events_service_proto protoreflect.FileDescriptor

const file_yamcs_protobuf_events_events_service_proto_rawDesc = "" +
	"\n" +
	"*yamcs/protobuf/events/events_service.proto\x12\x15yamcs.protobuf.events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1byamcs/api/annotations.proto\x1a\x18yamcs/api/httpbody.proto\x1a\"yamcs/protobuf/events/events.proto\"\xc1\x02\n" +
	"\x11ListEventsRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x14\n" +
	"\x03pos\x18\x02 \x01(\x03B\x02\x18\x01R\x03pos\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05order\x18\x04 \x01(\tR\x05order\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x16\n" +
	"\x06source\x18\x06 \x03(\tR\x06source\x12\x12\n" +
	"\x04next\x18\a \x01(\tR\x04next\x120\n" +
	"\x05start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12.\n" +
	"\x04stop\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x04stop\x12\f\n" +
	"\x01q\x18\n" +
	" \x01(\tR\x01q\x12\x16\n" +
	"\x06filter\x18\v \x01(\tR\x06filter\"\xb0\x01\n" +
	"\x12ListEventsResponse\x126\n" +
	"\x05event\x18\x01 \x03(\v2\x1c.yamcs.protobuf.events.EventB\x02\x18\x01R\x05event\x124\n" +
	"\x06events\x18\x03 \x03(\v2\x1c.yamcs.protobuf.events.EventR\x06events\x12,\n" +
	"\x11continuationToken\x18\x02 \x01(\tR\x11continuationToken\"L\n" +
	"\x16SubscribeEventsRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\"\xf0\x02\n" +
	"\x12CreateEventRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12.\n" +
	"\x04time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12&\n" +
	"\x0esequenceNumber\x18\a \x01(\x05R\x0esequenceNumber\x12J\n" +
	"\x05extra\x18\b \x03(\v24.yamcs.protobuf.events.CreateEventRequest.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x01\n" +
	"\x13StreamEventsRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12.\n" +
	"\x04stop\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04stop\x12\x16\n" +
	"\x06source\x18\x04 \x03(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\f\n" +
	"\x01q\x18\x06 \x01(\tR\x01q\x12\x16\n" +
	"\x06filter\x18\a \x01(\tR\x06filter\"5\n" +
	"\x17ListEventSourcesRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\"P\n" +
	"\x18ListEventSourcesResponse\x12\x1a\n" +
	"\x06source\x18\x01 \x03(\tB\x02\x18\x01R\x06source\x12\x18\n" +
	"\asources\x18\x02 \x03(\tR\asources\"\x8b\x02\n" +
	"\x13ExportEventsRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12.\n" +
	"\x04stop\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04stop\x12\x16\n" +
	"\x06source\x18\x04 \x03(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\f\n" +
	"\x01q\x18\x06 \x01(\tR\x01q\x12\x16\n" +
	"\x06filter\x18\b \x01(\tR\x06filter\x12\x1c\n" +
	"\tdelimiter\x18\a \x01(\tR\tdelimiter2\xee\x06\n" +
	"\tEventsApi\x12\xb1\x01\n" +
	"\n" +
	"ListEvents\x12(.yamcs.protobuf.events.ListEventsRequest\x1a).yamcs.protobuf.events.ListEventsResponse\"N\x8a\x92\x03JZ(:\x01*\x1a#/api/archive/{instance}/events:list\n" +
	"\x1e/api/archive/{instance}/events\x12\x7f\n" +
	"\vCreateEvent\x12).yamcs.protobuf.events.CreateEventRequest\x1a\x1c.yamcs.protobuf.events.Event\"'\x8a\x92\x03#:\x01*\x1a\x1e/api/archive/{instance}/events\x12\xa1\x01\n" +
	"\x10ListEventSources\x12..yamcs.protobuf.events.ListEventSourcesRequest\x1a/.yamcs.protobuf.events.ListEventSourcesResponse\",\x8a\x92\x03(\n" +
	"&/api/archive/{instance}/events/sources\x12\x90\x01\n" +
	"\fStreamEvents\x12*.yamcs.protobuf.events.StreamEventsRequest\x1a\x1c.yamcs.protobuf.events.Event\"4\x8a\x92\x030:\x01*\x1a+/api/stream-archive/{instance}:streamEvents0\x01\x12}\n" +
	"\fExportEvents\x12*.yamcs.protobuf.events.ExportEventsRequest\x1a\x13.yamcs.api.HttpBody\"*\x8a\x92\x03&\n" +
	"$/api/archive/{instance}:exportEvents0\x01\x12p\n" +
	"\x0fSubscribeEvents\x12-.yamcs.protobuf.events.SubscribeEventsRequest\x1a\x1c.yamcs.protobuf.events.Event\"\fڒ\x03\b\n" +
	"\x06events(\x010\x01\x1a\x04Ѐ\x01\x01B*\n" +
	"\x12org.yamcs.protobufB\x12EventsServiceProtoP\x01"

var (
	file_yamcs_protobuf_events_events_service_proto_rawDescOnce sync.Once
	file_yamcs_protobuf_events_events_service_proto_rawDescData []byte
)

func file_yamcs_protobuf_events_events_service_proto_rawDescGZIP() []byte {
	file_yamcs_protobuf_events_events_service_proto_rawDescOnce.Do(func() {
		file_yamcs_protobuf_events_events_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yamcs_protobuf_events_events_service_proto_rawDesc), len(file_yamcs_protobuf_events_events_service_proto_rawDesc)))
	})
	return file_yamcs_protobuf_events_events_service_proto_rawDescData
}

var file_yamcs_protobuf_events_events_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_yamcs_protobuf_events_events_service_proto_goTypes = []any{
	(*ListEventsRequest)(nil),        // 0: yamcs.protobuf.events.ListEventsRequest
	(*ListEventsResponse)(nil),       // 1: yamcs.protobuf.events.ListEventsResponse
	(*SubscribeEventsRequest)(nil),   // 2: yamcs.protobuf.events.SubscribeEventsRequest
	(*CreateEventRequest)(nil),       // 3: yamcs.protobuf.events.CreateEventRequest
	(*StreamEventsRequest)(nil),      // 4: yamcs.protobuf.events.StreamEventsRequest
	(*ListEventSourcesRequest)(nil),  // 5: yamcs.protobuf.events.ListEventSourcesRequest
	(*ListEventSourcesResponse)(nil), // 6: yamcs.protobuf.events.ListEventSourcesResponse
	(*ExportEventsRequest)(nil),      // 7: yamcs.protobuf.events.ExportEventsRequest
	nil,                              // 8: yamcs.protobuf.events.CreateEventRequest.ExtraEntry
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
	(*Event)(nil),                    // 10: yamcs.protobuf.events.Event
	(*api.HttpBody)(nil),             // 11: yamcs.api.HttpBody
}
var file_yamcs_protobuf_events_events_service_proto_depIdxs = []int32{
	9,  // 0: yamcs.protobuf.events.ListEventsRequest.start:type_name -> google.protobuf.Timestamp
	9,  // 1: yamcs.protobuf.events.ListEventsRequest.stop:type_name -> google.protobuf.Timestamp
	10, // 2: yamcs.protobuf.events.ListEventsResponse.event:type_name -> yamcs.protobuf.events.Event
	10, // 3: yamcs.protobuf.events.ListEventsResponse.events:type_name -> yamcs.protobuf.events.Event
	9,  // 4: yamcs.protobuf.events.CreateEventRequest.time:type_name -> google.protobuf.Timestamp
	8,  // 5: yamcs.protobuf.events.CreateEventRequest.extra:type_name -> yamcs.protobuf.events.CreateEventRequest.ExtraEntry
	9,  // 6: yamcs.protobuf.events.StreamEventsRequest.start:type_name -> google.protobuf.Timestamp
	9,  // 7: yamcs.protobuf.events.StreamEventsRequest.stop:type_name -> google.protobuf.Timestamp
	9,  // 8: yamcs.protobuf.events.ExportEventsRequest.start:type_name -> google.protobuf.Timestamp
	9,  // 9: yamcs.protobuf.events.ExportEventsRequest.stop:type_name -> google.protobuf.Timestamp
	0,  // 10: yamcs.protobuf.events.EventsApi.ListEvents:input_type -> yamcs.protobuf.events.ListEventsRequest
	3,  // 11: yamcs.protobuf.events.EventsApi.CreateEvent:input_type -> yamcs.protobuf.events.CreateEventRequest
	5,  // 12: yamcs.protobuf.events.EventsApi.ListEventSources:input_type -> yamcs.protobuf.events.ListEventSourcesRequest
	4,  // 13: yamcs.protobuf.events.EventsApi.StreamEvents:input_type -> yamcs.protobuf.events.StreamEventsRequest
	7,  // 14: yamcs.protobuf.events.EventsApi.ExportEvents:input_type -> yamcs.protobuf.events.ExportEventsRequest
	2,  // 15: yamcs.protobuf.events.EventsApi.SubscribeEvents:input_type -> yamcs.protobuf.events.SubscribeEventsRequest
	1,  // 16: yamcs.protobuf.events.EventsApi.ListEvents:output_type -> yamcs.protobuf.events.ListEventsResponse
	10, // 17: yamcs.protobuf.events.EventsApi.CreateEvent:output_type -> yamcs.protobuf.events.Event
	6,  // 18: yamcs.protobuf.events.EventsApi.ListEventSources:output_type -> yamcs.protobuf.events.ListEventSourcesResponse
	10, // 19: yamcs.protobuf.events.EventsApi.StreamEvents:output_type -> yamcs.protobuf.events.Event
	11, // 20: yamcs.protobuf.events.EventsApi.ExportEvents:output_type -> yamcs.api.HttpBody
	10, // 21: yamcs.protobuf.events.EventsApi.SubscribeEvents:output_type -> yamcs.protobuf.events.Event
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_yamcs_protobuf_events_events_service_proto_init() }
func file_yamcs_protobuf_events_events_service_proto_init() {
	if File_yamcs_protobuf_events_events_service_proto != nil {
		return
	}
	file_yamcs_protobuf_events_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yamcs_protobuf_events_events_service_proto_rawDesc), len(file_yamcs_protobuf_events_events_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yamcs_protobuf_events_events_service_proto_goTypes,
		DependencyIndexes: file_yamcs_protobuf_events_events_service_proto_depIdxs,
		MessageInfos:      file_yamcs_protobuf_events_events_service_proto_msgTypes,
	}.Build()
	File_yamcs_protobuf_events_events_service_proto = out.File
	file_yamcs_protobuf_events_events_service_proto_goTypes = nil
	file_yamcs_protobuf_events_events_service_proto_depIdxs = nil
}
