// Code generated by goyacc syntax.y. DO NOT EDIT.

//line syntax.y:2
package parser

import (
	__yyfmt__ "fmt"

	"github.com/nasa/hermes/cmd/protocolc/ast"
)

//line syntax.y:2

//line syntax.y:7
type yySymType struct {
	yys int
	Pos ast.Pos

	Nodes ast.Nodes

	Node ast.Node
	Decl ast.Decl
	Expr ast.Expr
	Type ast.Type

	SymbolDeclName *ast.SymbolDeclName
	ExternDeclName *ast.ExternDeclName

	Bool      bool
	LitExpr   *ast.LitExpr
	LitExprs  []*ast.LitExpr
	Ident     *ast.Ident
	TypeSize  *ast.TypeSize
	Args      []ast.Expr
	ParamArgs []*ast.Ident

	TypeCase  *ast.TypeCase
	MatchType []*ast.TypeCase

	ByteOrder      ast.ByteOrderKind
	Field          *ast.Field
	Fields         []*ast.Field
	EnumMember     *ast.EnumMember
	EnumMembers    []*ast.EnumMember
	BitmaskMember  *ast.BitmaskMember
	BitmaskMembers []*ast.BitmaskMember
}

const LexError = 57346
const PAREN_OPEN = 57347
const PAREN_CLOSE = 57348
const BRACKET_OPEN = 57349
const BRACKET_CLOSE = 57350
const CURLY_OPEN = 57351
const CURLY_CLOSE = 57352
const SEMI = 57353
const COLON = 57354
const DOT = 57355
const STAR = 57356
const COMMA = 57357
const EQUAL = 57358
const QUESTION = 57359
const PIPE = 57360
const DIRECT = 57361
const DOLLAR = 57362
const ARROW = 57363
const STRUCT = 57364
const STRING = 57365
const ENUM = 57366
const BITMASK = 57367
const TYPE = 57368
const EXTERN = 57369
const MARSHAL = 57370
const UNMARSHAL = 57371
const IMPORT = 57372
const Literal = 57373
const Ident = 57374

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LexError",
	"PAREN_OPEN",
	"PAREN_CLOSE",
	"BRACKET_OPEN",
	"BRACKET_CLOSE",
	"CURLY_OPEN",
	"CURLY_CLOSE",
	"SEMI",
	"COLON",
	"DOT",
	"STAR",
	"COMMA",
	"EQUAL",
	"QUESTION",
	"PIPE",
	"DIRECT",
	"DOLLAR",
	"ARROW",
	"STRUCT",
	"STRING",
	"ENUM",
	"BITMASK",
	"TYPE",
	"EXTERN",
	"MARSHAL",
	"UNMARSHAL",
	"IMPORT",
	"Literal",
	"Ident",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line syntax.y:294

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 154

var yyAct = [...]int8{
	82, 96, 98, 56, 95, 85, 58, 54, 44, 47,
	89, 47, 67, 21, 24, 24, 83, 119, 24, 73,
	83, 108, 24, 34, 83, 36, 39, 46, 55, 46,
	49, 50, 49, 50, 45, 24, 45, 83, 97, 23,
	23, 24, 97, 23, 60, 59, 97, 23, 38, 24,
	106, 83, 66, 99, 24, 87, 71, 87, 31, 81,
	23, 74, 15, 11, 125, 37, 23, 75, 122, 112,
	33, 80, 123, 107, 23, 86, 4, 86, 5, 23,
	6, 7, 72, 111, 8, 91, 104, 102, 93, 55,
	100, 90, 79, 70, 42, 40, 105, 109, 16, 117,
	94, 124, 92, 76, 116, 65, 25, 78, 52, 19,
	18, 113, 110, 115, 64, 109, 103, 121, 120, 101,
	68, 26, 69, 32, 28, 88, 63, 62, 61, 10,
	118, 77, 51, 114, 35, 12, 13, 27, 20, 3,
	84, 53, 9, 22, 43, 17, 14, 41, 29, 30,
	57, 48, 2, 1,
}

var yyPact = [...]int16{
	54, -1000, 54, -1000, 31, 31, 31, 30, 67, -1000,
	96, 133, 8, 90, 109, 132, -1000, 115, -1000, -1000,
	26, 114, 47, 129, 34, 8, 64, 63, 4, 126,
	93, -1000, -4, -1000, -1000, 13, 120, 119, 118, -1000,
	-1000, 99, -1000, 2, -1000, 108, 113, 62, 51, -1000,
	-1000, -1000, -13, 57, -1000, 87, 125, 92, -1000, -1000,
	-1000, -1000, -1000, -1000, 61, -1000, -1000, -1000, 28, 45,
	117, -22, -1000, -1000, -1000, -1000, 60, -1000, 13, -1000,
	86, 71, 79, 15, 43, -1000, 107, 56, -1000, 104,
	-1000, -1000, 55, 42, 41, 11, -1000, 100, -1000, -1000,
	-1000, 52, -1000, 38, -1000, -1000, 15, 128, -1000, -1000,
	42, 83, 124, 7, 13, -1000, 8, 37, -1000, -1000,
	66, 85, -1000, -1000, 33, -1000,
}

var yyPgo = [...]uint8{
	0, 153, 152, 139, 6, 151, 3, 150, 149, 148,
	147, 129, 146, 145, 8, 144, 143, 0, 2, 1,
	4, 7, 141, 5, 140,
}

var yyR1 = [...]int8{
	0, 1, 1, 2, 2, 4, 4, 7, 7, 6,
	6, 16, 16, 16, 17, 17, 17, 17, 18, 18,
	18, 18, 19, 19, 20, 20, 5, 5, 14, 14,
	14, 14, 14, 14, 14, 15, 15, 13, 13, 23,
	23, 23, 23, 23, 24, 24, 21, 22, 22, 8,
	8, 9, 9, 11, 11, 10, 10, 12, 12, 3,
	3, 3, 3, 3,
}

var yyR2 = [...]int8{
	0, 0, 1, 1, 2, 1, 1, 1, 3, 0,
	1, 3, 3, 3, 2, 2, 1, 4, 1, 3,
	5, 6, 3, 1, 1, 2, 1, 1, 3, 5,
	5, 4, 3, 6, 2, 1, 2, 1, 1, 3,
	5, 5, 7, 2, 1, 2, 3, 1, 2, 1,
	3, 0, 1, 1, 4, 1, 3, 1, 4, 6,
	6, 4, 4, 2,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 22, 24, 26, 27, 30, -3,
	-11, 32, -11, -11, -12, 32, 31, -13, 14, 13,
	5, -17, -16, 32, 7, 16, 12, 5, 9, -9,
	-8, 32, 9, 23, -17, 5, -17, 31, 14, -17,
	31, -10, 31, -15, -14, 32, 25, 7, -5, 28,
	29, 6, 15, -22, -21, 32, -6, -7, -4, 32,
	31, 8, 8, 8, 15, 6, -14, 10, 12, 9,
	31, 5, 31, 32, -21, 10, 16, 6, 15, 31,
	-18, 31, -17, 9, -24, -23, 32, 12, 8, 32,
	31, -4, 16, 17, 21, -20, -19, 31, -18, 10,
	-23, 12, 31, 12, 31, -18, 9, 32, 10, -19,
	12, 31, 31, -20, 5, -18, 21, 16, 6, 10,
	-6, -17, 31, 6, 16, 31,
}

var yyDef = [...]int8{
	1, -2, 2, 3, 0, 0, 0, 0, 0, 4,
	0, 53, 0, 0, 0, 57, 63, 0, 37, 38,
	51, 0, 0, 16, 0, 0, 0, 0, 0, 0,
	52, 49, 0, 14, 15, 9, 0, 0, 0, 61,
	62, 0, 55, 0, 35, 0, 0, 0, 0, 26,
	27, 54, 0, 0, 47, 0, 0, 10, 7, 5,
	6, 11, 12, 13, 0, 58, 36, 59, 0, 0,
	0, 0, 34, 50, 48, 60, 0, 17, 0, 56,
	28, 0, 18, 0, 0, 44, 0, 0, 32, 0,
	46, 8, 0, 0, 0, 0, 24, 0, 23, 31,
	45, 0, 43, 0, 29, 30, 0, 0, 19, 25,
	0, 39, 0, 0, 9, 22, 0, 0, 33, 20,
	0, 40, 41, 21, 0, 42,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line syntax.y:109
		{
			yyVAL.Nodes = ast.Nodes{}
			yylex.(*lex).SetResult(yyVAL.Nodes)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:115
		{
			yyVAL.Nodes = yyDollar[1].Nodes
			yylex.(*lex).SetResult(yyVAL.Nodes)
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:121
		{
			yyVAL.Nodes = ast.Nodes{yyDollar[1].Decl}
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:122
		{
			yyVAL.Nodes = append(yyDollar[1].Nodes, yyDollar[2].Decl)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:125
		{
			yyVAL.Expr = yyDollar[1].Ident
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:126
		{
			yyVAL.Expr = yyDollar[1].LitExpr
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:129
		{
			yyVAL.Args = []ast.Expr{yyDollar[1].Expr}
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:130
		{
			yyVAL.Args = append(yyDollar[1].Args, yyDollar[3].Expr)
		}
	case 9:
		yyDollar = yyS[yypt-0 : yypt+1]
//line syntax.y:133
		{
			yyVAL.Args = []ast.Expr{}
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:134
		{
			yyVAL.Args = yyDollar[1].Args
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:138
		{
			yyVAL.TypeSize = &ast.TypeSize{Kind: ast.DYNAMIC, Dynamic: yyDollar[2].Type, Open: yyDollar[1].Pos, Close: yyDollar[3].Pos}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:141
		{
			yyVAL.TypeSize = &ast.TypeSize{Kind: ast.STATIC, Static: yyDollar[2].LitExpr, Open: yyDollar[1].Pos, Close: yyDollar[3].Pos}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:144
		{
			yyVAL.TypeSize = &ast.TypeSize{Kind: ast.FILL, Open: yyDollar[1].Pos, Close: yyDollar[3].Pos}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:147
		{
			yyVAL.Type = &ast.StringType{Size: yyDollar[1].TypeSize, Token: yyDollar[2].Pos}
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:148
		{
			yyVAL.Type = &ast.ArrayType{Size: yyDollar[1].TypeSize, Elt: yyDollar[2].Type}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:149
		{
			yyVAL.Type = &ast.RefType{Name: yyDollar[1].Ident}
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line syntax.y:151
		{
			yyVAL.Type = &ast.RefType{Name: yyDollar[1].Ident, Args: ast.Group[[]ast.Expr]{Open: yyDollar[2].Pos, Members: yyDollar[3].Args, Close: yyDollar[4].Pos}}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:155
		{
			yyVAL.Type = yyDollar[1].Type
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:158
		{
			yyVAL.Type = &ast.MatchType{Cases: ast.Group[[]*ast.TypeCase]{Open: yyDollar[1].Pos, Members: yyDollar[2].MatchType, Close: yyDollar[3].Pos}}
		}
	case 20:
		yyDollar = yyS[yypt-5 : yypt+1]
//line syntax.y:161
		{
			yyVAL.Type = &ast.MatchType{Reader: yyDollar[1].Type, Cases: ast.Group[[]*ast.TypeCase]{Open: yyDollar[3].Pos, Members: yyDollar[4].MatchType, Close: yyDollar[5].Pos}}
		}
	case 21:
		yyDollar = yyS[yypt-6 : yypt+1]
//line syntax.y:164
		{
			yyVAL.Type = &ast.TransformType{Initial: yyDollar[1].Type, Name: yyDollar[3].Ident, Args: ast.Group[[]ast.Expr]{Open: yyDollar[4].Pos, Members: yyDollar[5].Args, Close: yyDollar[6].Pos}}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:168
		{
			yyVAL.TypeCase = &ast.TypeCase{Cond: yyDollar[1].LitExpr, Type: yyDollar[3].Type}
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:172
		{
			yyVAL.TypeCase = &ast.TypeCase{Type: yyDollar[1].Type}
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:176
		{
			yyVAL.MatchType = []*ast.TypeCase{yyDollar[1].TypeCase}
		}
	case 25:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:179
		{
			yyVAL.MatchType = append(yyDollar[1].MatchType, yyDollar[2].TypeCase)
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:182
		{
			yyVAL.Bool = true
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:183
		{
			yyVAL.Bool = false
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:187
		{
			yyVAL.Field = &ast.Field{Name: yyDollar[1].Ident, Type: yyDollar[3].Type}
		}
	case 29:
		yyDollar = yyS[yypt-5 : yypt+1]
//line syntax.y:190
		{
			yyVAL.Field = &ast.Field{Name: yyDollar[1].Ident, Type: yyDollar[3].Type, Initializer: yyDollar[5].LitExpr}
		}
	case 30:
		yyDollar = yyS[yypt-5 : yypt+1]
//line syntax.y:193
		{
			yyVAL.Field = &ast.Field{Name: yyDollar[1].Ident, Type: yyDollar[5].Type, Condition: yyDollar[3].LitExpr}
		}
	case 31:
		yyDollar = yyS[yypt-4 : yypt+1]
//line syntax.y:196
		{
			yyVAL.Field = &ast.Field{Type: &ast.BitmaskType{Members: ast.Group[[]*ast.BitmaskMember]{Open: yyDollar[1].Pos, Members: yyDollar[3].BitmaskMembers, Close: yyDollar[4].Pos}}}
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:199
		{
			yyVAL.Field = &ast.Field{Type: &ast.PadType{Size: yyDollar[2].LitExpr}}
		}
	case 33:
		yyDollar = yyS[yypt-6 : yypt+1]
//line syntax.y:202
		{
			yyVAL.Field = &ast.Field{Arg: &ast.Param{IsMarshal: yyDollar[1].Bool, Name: yyDollar[3].Ident, Type: yyDollar[5].LitExpr}}
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:205
		{
			yyVAL.Field = &ast.Field{Literal: &ast.FieldLiteral{IsMarshal: yyDollar[1].Bool, Code: yyDollar[2].LitExpr}}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:209
		{
			yyVAL.Fields = []*ast.Field{yyDollar[1].Field}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:212
		{
			yyVAL.Fields = append(yyDollar[1].Fields, yyDollar[2].Field)
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:215
		{
			yyVAL.ByteOrder = ast.BIG
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:216
		{
			yyVAL.ByteOrder = ast.LITTLE
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:220
		{
			yyVAL.BitmaskMember = &ast.BitmaskMember{Name: yyDollar[1].Ident, Value: yyDollar[3].LitExpr}
		}
	case 40:
		yyDollar = yyS[yypt-5 : yypt+1]
//line syntax.y:225
		{
			yyVAL.BitmaskMember = &ast.BitmaskMember{Name: yyDollar[1].Ident, Value: yyDollar[3].LitExpr, Type: yyDollar[5].Type}
		}
	case 41:
		yyDollar = yyS[yypt-5 : yypt+1]
//line syntax.y:229
		{
			yyVAL.BitmaskMember = &ast.BitmaskMember{Name: yyDollar[1].Ident, Value: yyDollar[3].LitExpr, Initializer: yyDollar[5].LitExpr}
		}
	case 42:
		yyDollar = yyS[yypt-7 : yypt+1]
//line syntax.y:232
		{
			yyVAL.BitmaskMember = &ast.BitmaskMember{Name: yyDollar[1].Ident, Value: yyDollar[3].LitExpr, Type: yyDollar[5].Type, Initializer: yyDollar[7].LitExpr}
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:238
		{
			yyVAL.BitmaskMember = &ast.BitmaskMember{Value: yyDollar[2].LitExpr}
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:241
		{
			yyVAL.BitmaskMembers = []*ast.BitmaskMember{yyDollar[1].BitmaskMember}
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:242
		{
			yyVAL.BitmaskMembers = append(yyDollar[1].BitmaskMembers, yyDollar[2].BitmaskMember)
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:245
		{
			yyVAL.EnumMember = &ast.EnumMember{Name: yyDollar[1].Ident, Value: yyDollar[3].LitExpr}
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:248
		{
			yyVAL.EnumMembers = []*ast.EnumMember{yyDollar[1].EnumMember}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:249
		{
			yyVAL.EnumMembers = append(yyDollar[1].EnumMembers, yyDollar[2].EnumMember)
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:252
		{
			yyVAL.ParamArgs = []*ast.Ident{yyDollar[1].Ident}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:253
		{
			yyVAL.ParamArgs = append(yyDollar[1].ParamArgs, yyDollar[3].Ident)
		}
	case 51:
		yyDollar = yyS[yypt-0 : yypt+1]
//line syntax.y:256
		{
			yyVAL.ParamArgs = []*ast.Ident{}
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:257
		{
			yyVAL.ParamArgs = yyDollar[1].ParamArgs
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:261
		{
			yyVAL.SymbolDeclName = &ast.SymbolDeclName{Name: yyDollar[1].Ident}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line syntax.y:263
		{
			yyVAL.SymbolDeclName = &ast.SymbolDeclName{Name: yyDollar[1].Ident, Args: ast.Group[[]*ast.Ident]{Open: yyDollar[2].Pos, Members: yyDollar[3].ParamArgs, Close: yyDollar[4].Pos}}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:267
		{
			yyVAL.LitExprs = []*ast.LitExpr{yyDollar[1].LitExpr}
		}
	case 56:
		yyDollar = yyS[yypt-3 : yypt+1]
//line syntax.y:270
		{
			yyVAL.LitExprs = append(yyDollar[1].LitExprs, yyDollar[3].LitExpr)
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line syntax.y:274
		{
			yyVAL.ExternDeclName = &ast.ExternDeclName{Name: yyDollar[1].Ident}
		}
	case 58:
		yyDollar = yyS[yypt-4 : yypt+1]
//line syntax.y:276
		{
			yyVAL.ExternDeclName = &ast.ExternDeclName{Name: yyDollar[1].Ident, Args: ast.Group[[]*ast.LitExpr]{Open: yyDollar[2].Pos, Members: yyDollar[3].LitExprs, Close: yyDollar[4].Pos}}
		}
	case 59:
		yyDollar = yyS[yypt-6 : yypt+1]
//line syntax.y:280
		{
			yyVAL.Decl = &ast.StructTypeDecl{Name: yyDollar[2].SymbolDeclName, ByteOrder: yyDollar[3].ByteOrder, Fields: ast.Group[[]*ast.Field]{Open: yyDollar[4].Pos, Members: yyDollar[5].Fields, Close: yyDollar[6].Pos}}
		}
	case 60:
		yyDollar = yyS[yypt-6 : yypt+1]
//line syntax.y:283
		{
			yyVAL.Decl = &ast.EnumTypeDecl{Name: yyDollar[2].SymbolDeclName, EncodeType: yyDollar[3].Type, Members: ast.Group[[]*ast.EnumMember]{Open: yyDollar[4].Pos, Members: yyDollar[5].EnumMembers, Close: yyDollar[6].Pos}}
		}
	case 61:
		yyDollar = yyS[yypt-4 : yypt+1]
//line syntax.y:286
		{
			yyVAL.Decl = &ast.AliasTypeDecl{Name: yyDollar[2].SymbolDeclName, Type: yyDollar[4].Type}
		}
	case 62:
		yyDollar = yyS[yypt-4 : yypt+1]
//line syntax.y:289
		{
			yyVAL.Decl = &ast.ExternTypeDecl{Name: yyDollar[2].ExternDeclName, Type: yyDollar[4].LitExpr}
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line syntax.y:292
		{
			yyVAL.Decl = &ast.ExternImport{Pkg: yyDollar[2].LitExpr}
		}
	}
	goto yystack /* stack new state and value */
}
