// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: hermes.proto

package grpc

import (
	context "context"
	pb "github.com/nasa/hermes/pkg/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Api_Sequence_FullMethodName            = "/Api/Sequence"
	Api_RawSequence_FullMethodName         = "/Api/RawSequence"
	Api_Command_FullMethodName             = "/Api/Command"
	Api_RawCommand_FullMethodName          = "/Api/RawCommand"
	Api_Uplink_FullMethodName              = "/Api/Uplink"
	Api_GetFsw_FullMethodName              = "/Api/GetFsw"
	Api_AllFsw_FullMethodName              = "/Api/AllFsw"
	Api_SubscribeFsw_FullMethodName        = "/Api/SubscribeFsw"
	Api_StartProfile_FullMethodName        = "/Api/StartProfile"
	Api_StopProfile_FullMethodName         = "/Api/StopProfile"
	Api_UpdateProfile_FullMethodName       = "/Api/UpdateProfile"
	Api_AddProfile_FullMethodName          = "/Api/AddProfile"
	Api_RemoveProfile_FullMethodName       = "/Api/RemoveProfile"
	Api_AllProfiles_FullMethodName         = "/Api/AllProfiles"
	Api_AllProviders_FullMethodName        = "/Api/AllProviders"
	Api_SubscribeProviders_FullMethodName  = "/Api/SubscribeProviders"
	Api_SubscribeProfiles_FullMethodName   = "/Api/SubscribeProfiles"
	Api_GetDictionary_FullMethodName       = "/Api/GetDictionary"
	Api_AddDictionary_FullMethodName       = "/Api/AddDictionary"
	Api_RemoveDictionary_FullMethodName    = "/Api/RemoveDictionary"
	Api_AllDictionary_FullMethodName       = "/Api/AllDictionary"
	Api_SubscribeDictionary_FullMethodName = "/Api/SubscribeDictionary"
	Api_SubEvent_FullMethodName            = "/Api/SubEvent"
	Api_SubTelemetry_FullMethodName        = "/Api/SubTelemetry"
	Api_SubFileDownlink_FullMethodName     = "/Api/SubFileDownlink"
)

// ApiClient is the client API for Api service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiClient interface {
	// *
	// Send a command sequence to the FSW to execute.
	//
	// If the FSW connection does not implement this endpoint directly,
	// this becomes a pseudo-endpoint that will wrap the 'Command' and allow
	// running commands in sequence. This is preferrable to successive
	// calls to 'Command' because commands are grouped together into
	// a single 'Trace' for easily tracking what was sent to the system.
	//
	// Metadata:
	//
	//	"id": [fsw-id]
	//
	// TODO(tumbar) We will probably want to expand this to add some identifying
	// metadata to allow linking back to the code cell in our Notebooks
	//
	// Optional Metadata
	//
	//	Keep executing the sequence even if
	//	"keepGoingOnFailure": "x"
	Sequence(ctx context.Context, in *pb.CommandSequence, opts ...grpc.CallOption) (*pb.SequenceReply, error)
	// *
	// A wrapper endpoint around Sequence/RawCommand.
	// This endpoint will parse a sequence and run it through Sequence.
	RawSequence(ctx context.Context, in *pb.RawCommandSequence, opts ...grpc.CallOption) (*pb.SequenceReply, error)
	// *
	// Send a command to the FSW. Wait for
	// completion or otherwise, up to the
	// plugin to decide when the promise resolves.
	//
	// Metadata:
	//
	//	"id": [fsw-id]
	Command(ctx context.Context, in *pb.CommandValue, opts ...grpc.CallOption) (*pb.Reply, error)
	// *
	// Send a 'raw' command to the FSW. A raw command
	// differs from a full command in that it must be parsed
	// by the backend. Each FSW must support converting an argument list
	// to a command value and passing it to the "real" Command() interface.
	// Wait for completion or otherwise, up to the
	// plugin to decide when the promise resolves.
	//
	// Metadata:
	//
	//	"id": [fsw-id]
	RawCommand(ctx context.Context, in *pb.RawCommandValue, opts ...grpc.CallOption) (*pb.Reply, error)
	// *
	// Uplink a file to the FSW.
	//
	// Metadata:
	//
	//	"id": [fsw-id]
	Uplink(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.UplinkFileChunk, pb.Reply], error)
	// Get FSW metadata given its ID
	GetFsw(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Fsw, error)
	// Get all the current connected FSWs
	AllFsw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.FswList, error)
	// Subscribe to any changes to FSW connections state
	SubscribeFsw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.FswList], error)
	// Start a profile and return once it's connected (cancellable)
	StartProfile(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Stop profile given its name/id and reutrn once its stopped (cancellable)
	StopProfile(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Update a profile
	UpdateProfile(ctx context.Context, in *pb.ProfileUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Create a new profile, returns it's registered ID
	AddProfile(ctx context.Context, in *pb.Profile, opts ...grpc.CallOption) (*pb.Id, error)
	// Delete a profile by its id
	RemoveProfile(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get all the profiles
	AllProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.ProfileList, error)
	// Get all the registered profile providers
	AllProviders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.ProfileProviderList, error)
	// Get notified when the set of profile providers updates
	SubscribeProviders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.ProfileProviderList], error)
	// Get notified when the set of profile or their internal state updates
	SubscribeProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.ProfileList], error)
	// *
	// Get a dictionary by its ID
	// Metadata (optional)
	//
	//	The dictionary "sections" to include in the reply.
	//	This is a whitelist set of options to include. If this
	//	list is not provided or empty, the entire dictionary will be transmitted
	//
	//	A "section" includes two parts [namespace].[definition-id]
	//	- namespace: Name of the namespace to include
	//	- section: The portion of the namespace to include, the following sections are valid
	//	  - "commands": All the command definitions in this namespace
	//	  - "events": All event definitions this namespaces
	//	  - "telemetry": All telemetry definitions this namespaces
	//	  - "parameters": All parameter definitions this namespaces
	//	  - "*": The entire namespace
	//	Example: "sections": [".events", "ns-1.*", "ns-2.telemetry"]
	GetDictionary(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Dictionary, error)
	// Add a new dictionary entry
	AddDictionary(ctx context.Context, in *pb.Dictionary, opts ...grpc.CallOption) (*pb.Id, error)
	// Remove specified dictionary
	RemoveDictionary(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get all registered dictionaries as a sequential stream
	AllDictionary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.DictionaryList, error)
	// Subscribe to changes to the dictionary state. streams { id, type }
	SubscribeDictionary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.DictionaryList], error)
	// Subscribe to the event message bus
	SubEvent(ctx context.Context, in *pb.BusFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.SourcedEvent], error)
	// Subscribe to the telemetry message bus
	SubTelemetry(ctx context.Context, in *pb.BusFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.SourcedTelemetry], error)
	// Subscribe to the file downlink message bus
	SubFileDownlink(ctx context.Context, in *pb.BusFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.FileDownlink], error)
}

type apiClient struct {
	cc grpc.ClientConnInterface
}

func NewApiClient(cc grpc.ClientConnInterface) ApiClient {
	return &apiClient{cc}
}

func (c *apiClient) Sequence(ctx context.Context, in *pb.CommandSequence, opts ...grpc.CallOption) (*pb.SequenceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.SequenceReply)
	err := c.cc.Invoke(ctx, Api_Sequence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RawSequence(ctx context.Context, in *pb.RawCommandSequence, opts ...grpc.CallOption) (*pb.SequenceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.SequenceReply)
	err := c.cc.Invoke(ctx, Api_RawSequence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Command(ctx context.Context, in *pb.CommandValue, opts ...grpc.CallOption) (*pb.Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Reply)
	err := c.cc.Invoke(ctx, Api_Command_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RawCommand(ctx context.Context, in *pb.RawCommandValue, opts ...grpc.CallOption) (*pb.Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Reply)
	err := c.cc.Invoke(ctx, Api_RawCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) Uplink(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.UplinkFileChunk, pb.Reply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[0], Api_Uplink_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.UplinkFileChunk, pb.Reply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_UplinkClient = grpc.ClientStreamingClient[pb.UplinkFileChunk, pb.Reply]

func (c *apiClient) GetFsw(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Fsw, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Fsw)
	err := c.cc.Invoke(ctx, Api_GetFsw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AllFsw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.FswList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.FswList)
	err := c.cc.Invoke(ctx, Api_AllFsw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SubscribeFsw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.FswList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[1], Api_SubscribeFsw_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, pb.FswList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeFswClient = grpc.ServerStreamingClient[pb.FswList]

func (c *apiClient) StartProfile(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Api_StartProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) StopProfile(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Api_StopProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) UpdateProfile(ctx context.Context, in *pb.ProfileUpdate, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Api_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AddProfile(ctx context.Context, in *pb.Profile, opts ...grpc.CallOption) (*pb.Id, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Id)
	err := c.cc.Invoke(ctx, Api_AddProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RemoveProfile(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Api_RemoveProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AllProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.ProfileList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.ProfileList)
	err := c.cc.Invoke(ctx, Api_AllProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AllProviders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.ProfileProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.ProfileProviderList)
	err := c.cc.Invoke(ctx, Api_AllProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SubscribeProviders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.ProfileProviderList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[2], Api_SubscribeProviders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, pb.ProfileProviderList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeProvidersClient = grpc.ServerStreamingClient[pb.ProfileProviderList]

func (c *apiClient) SubscribeProfiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.ProfileList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[3], Api_SubscribeProfiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, pb.ProfileList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeProfilesClient = grpc.ServerStreamingClient[pb.ProfileList]

func (c *apiClient) GetDictionary(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Dictionary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Dictionary)
	err := c.cc.Invoke(ctx, Api_GetDictionary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AddDictionary(ctx context.Context, in *pb.Dictionary, opts ...grpc.CallOption) (*pb.Id, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.Id)
	err := c.cc.Invoke(ctx, Api_AddDictionary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) RemoveDictionary(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Api_RemoveDictionary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) AllDictionary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.DictionaryList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb.DictionaryList)
	err := c.cc.Invoke(ctx, Api_AllDictionary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiClient) SubscribeDictionary(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.DictionaryList], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[4], Api_SubscribeDictionary_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, pb.DictionaryList]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeDictionaryClient = grpc.ServerStreamingClient[pb.DictionaryList]

func (c *apiClient) SubEvent(ctx context.Context, in *pb.BusFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.SourcedEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[5], Api_SubEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.BusFilter, pb.SourcedEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubEventClient = grpc.ServerStreamingClient[pb.SourcedEvent]

func (c *apiClient) SubTelemetry(ctx context.Context, in *pb.BusFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.SourcedTelemetry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[6], Api_SubTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.BusFilter, pb.SourcedTelemetry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubTelemetryClient = grpc.ServerStreamingClient[pb.SourcedTelemetry]

func (c *apiClient) SubFileDownlink(ctx context.Context, in *pb.BusFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[pb.FileDownlink], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Api_ServiceDesc.Streams[7], Api_SubFileDownlink_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.BusFilter, pb.FileDownlink]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubFileDownlinkClient = grpc.ServerStreamingClient[pb.FileDownlink]

// ApiServer is the server API for Api service.
// All implementations must embed UnimplementedApiServer
// for forward compatibility.
type ApiServer interface {
	// *
	// Send a command sequence to the FSW to execute.
	//
	// If the FSW connection does not implement this endpoint directly,
	// this becomes a pseudo-endpoint that will wrap the 'Command' and allow
	// running commands in sequence. This is preferrable to successive
	// calls to 'Command' because commands are grouped together into
	// a single 'Trace' for easily tracking what was sent to the system.
	//
	// Metadata:
	//
	//	"id": [fsw-id]
	//
	// TODO(tumbar) We will probably want to expand this to add some identifying
	// metadata to allow linking back to the code cell in our Notebooks
	//
	// Optional Metadata
	//
	//	Keep executing the sequence even if
	//	"keepGoingOnFailure": "x"
	Sequence(context.Context, *pb.CommandSequence) (*pb.SequenceReply, error)
	// *
	// A wrapper endpoint around Sequence/RawCommand.
	// This endpoint will parse a sequence and run it through Sequence.
	RawSequence(context.Context, *pb.RawCommandSequence) (*pb.SequenceReply, error)
	// *
	// Send a command to the FSW. Wait for
	// completion or otherwise, up to the
	// plugin to decide when the promise resolves.
	//
	// Metadata:
	//
	//	"id": [fsw-id]
	Command(context.Context, *pb.CommandValue) (*pb.Reply, error)
	// *
	// Send a 'raw' command to the FSW. A raw command
	// differs from a full command in that it must be parsed
	// by the backend. Each FSW must support converting an argument list
	// to a command value and passing it to the "real" Command() interface.
	// Wait for completion or otherwise, up to the
	// plugin to decide when the promise resolves.
	//
	// Metadata:
	//
	//	"id": [fsw-id]
	RawCommand(context.Context, *pb.RawCommandValue) (*pb.Reply, error)
	// *
	// Uplink a file to the FSW.
	//
	// Metadata:
	//
	//	"id": [fsw-id]
	Uplink(grpc.ClientStreamingServer[pb.UplinkFileChunk, pb.Reply]) error
	// Get FSW metadata given its ID
	GetFsw(context.Context, *pb.Id) (*pb.Fsw, error)
	// Get all the current connected FSWs
	AllFsw(context.Context, *emptypb.Empty) (*pb.FswList, error)
	// Subscribe to any changes to FSW connections state
	SubscribeFsw(*emptypb.Empty, grpc.ServerStreamingServer[pb.FswList]) error
	// Start a profile and return once it's connected (cancellable)
	StartProfile(context.Context, *pb.Id) (*emptypb.Empty, error)
	// Stop profile given its name/id and reutrn once its stopped (cancellable)
	StopProfile(context.Context, *pb.Id) (*emptypb.Empty, error)
	// Update a profile
	UpdateProfile(context.Context, *pb.ProfileUpdate) (*emptypb.Empty, error)
	// Create a new profile, returns it's registered ID
	AddProfile(context.Context, *pb.Profile) (*pb.Id, error)
	// Delete a profile by its id
	RemoveProfile(context.Context, *pb.Id) (*emptypb.Empty, error)
	// Get all the profiles
	AllProfiles(context.Context, *emptypb.Empty) (*pb.ProfileList, error)
	// Get all the registered profile providers
	AllProviders(context.Context, *emptypb.Empty) (*pb.ProfileProviderList, error)
	// Get notified when the set of profile providers updates
	SubscribeProviders(*emptypb.Empty, grpc.ServerStreamingServer[pb.ProfileProviderList]) error
	// Get notified when the set of profile or their internal state updates
	SubscribeProfiles(*emptypb.Empty, grpc.ServerStreamingServer[pb.ProfileList]) error
	// *
	// Get a dictionary by its ID
	// Metadata (optional)
	//
	//	The dictionary "sections" to include in the reply.
	//	This is a whitelist set of options to include. If this
	//	list is not provided or empty, the entire dictionary will be transmitted
	//
	//	A "section" includes two parts [namespace].[definition-id]
	//	- namespace: Name of the namespace to include
	//	- section: The portion of the namespace to include, the following sections are valid
	//	  - "commands": All the command definitions in this namespace
	//	  - "events": All event definitions this namespaces
	//	  - "telemetry": All telemetry definitions this namespaces
	//	  - "parameters": All parameter definitions this namespaces
	//	  - "*": The entire namespace
	//	Example: "sections": [".events", "ns-1.*", "ns-2.telemetry"]
	GetDictionary(context.Context, *pb.Id) (*pb.Dictionary, error)
	// Add a new dictionary entry
	AddDictionary(context.Context, *pb.Dictionary) (*pb.Id, error)
	// Remove specified dictionary
	RemoveDictionary(context.Context, *pb.Id) (*emptypb.Empty, error)
	// Get all registered dictionaries as a sequential stream
	AllDictionary(context.Context, *emptypb.Empty) (*pb.DictionaryList, error)
	// Subscribe to changes to the dictionary state. streams { id, type }
	SubscribeDictionary(*emptypb.Empty, grpc.ServerStreamingServer[pb.DictionaryList]) error
	// Subscribe to the event message bus
	SubEvent(*pb.BusFilter, grpc.ServerStreamingServer[pb.SourcedEvent]) error
	// Subscribe to the telemetry message bus
	SubTelemetry(*pb.BusFilter, grpc.ServerStreamingServer[pb.SourcedTelemetry]) error
	// Subscribe to the file downlink message bus
	SubFileDownlink(*pb.BusFilter, grpc.ServerStreamingServer[pb.FileDownlink]) error
	mustEmbedUnimplementedApiServer()
}

// UnimplementedApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiServer struct{}

func (UnimplementedApiServer) Sequence(context.Context, *pb.CommandSequence) (*pb.SequenceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sequence not implemented")
}
func (UnimplementedApiServer) RawSequence(context.Context, *pb.RawCommandSequence) (*pb.SequenceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawSequence not implemented")
}
func (UnimplementedApiServer) Command(context.Context, *pb.CommandValue) (*pb.Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Command not implemented")
}
func (UnimplementedApiServer) RawCommand(context.Context, *pb.RawCommandValue) (*pb.Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawCommand not implemented")
}
func (UnimplementedApiServer) Uplink(grpc.ClientStreamingServer[pb.UplinkFileChunk, pb.Reply]) error {
	return status.Errorf(codes.Unimplemented, "method Uplink not implemented")
}
func (UnimplementedApiServer) GetFsw(context.Context, *pb.Id) (*pb.Fsw, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFsw not implemented")
}
func (UnimplementedApiServer) AllFsw(context.Context, *emptypb.Empty) (*pb.FswList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllFsw not implemented")
}
func (UnimplementedApiServer) SubscribeFsw(*emptypb.Empty, grpc.ServerStreamingServer[pb.FswList]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeFsw not implemented")
}
func (UnimplementedApiServer) StartProfile(context.Context, *pb.Id) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProfile not implemented")
}
func (UnimplementedApiServer) StopProfile(context.Context, *pb.Id) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopProfile not implemented")
}
func (UnimplementedApiServer) UpdateProfile(context.Context, *pb.ProfileUpdate) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedApiServer) AddProfile(context.Context, *pb.Profile) (*pb.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProfile not implemented")
}
func (UnimplementedApiServer) RemoveProfile(context.Context, *pb.Id) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveProfile not implemented")
}
func (UnimplementedApiServer) AllProfiles(context.Context, *emptypb.Empty) (*pb.ProfileList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllProfiles not implemented")
}
func (UnimplementedApiServer) AllProviders(context.Context, *emptypb.Empty) (*pb.ProfileProviderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllProviders not implemented")
}
func (UnimplementedApiServer) SubscribeProviders(*emptypb.Empty, grpc.ServerStreamingServer[pb.ProfileProviderList]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeProviders not implemented")
}
func (UnimplementedApiServer) SubscribeProfiles(*emptypb.Empty, grpc.ServerStreamingServer[pb.ProfileList]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeProfiles not implemented")
}
func (UnimplementedApiServer) GetDictionary(context.Context, *pb.Id) (*pb.Dictionary, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDictionary not implemented")
}
func (UnimplementedApiServer) AddDictionary(context.Context, *pb.Dictionary) (*pb.Id, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDictionary not implemented")
}
func (UnimplementedApiServer) RemoveDictionary(context.Context, *pb.Id) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveDictionary not implemented")
}
func (UnimplementedApiServer) AllDictionary(context.Context, *emptypb.Empty) (*pb.DictionaryList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllDictionary not implemented")
}
func (UnimplementedApiServer) SubscribeDictionary(*emptypb.Empty, grpc.ServerStreamingServer[pb.DictionaryList]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeDictionary not implemented")
}
func (UnimplementedApiServer) SubEvent(*pb.BusFilter, grpc.ServerStreamingServer[pb.SourcedEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubEvent not implemented")
}
func (UnimplementedApiServer) SubTelemetry(*pb.BusFilter, grpc.ServerStreamingServer[pb.SourcedTelemetry]) error {
	return status.Errorf(codes.Unimplemented, "method SubTelemetry not implemented")
}
func (UnimplementedApiServer) SubFileDownlink(*pb.BusFilter, grpc.ServerStreamingServer[pb.FileDownlink]) error {
	return status.Errorf(codes.Unimplemented, "method SubFileDownlink not implemented")
}
func (UnimplementedApiServer) mustEmbedUnimplementedApiServer() {}
func (UnimplementedApiServer) testEmbeddedByValue()             {}

// UnsafeApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiServer will
// result in compilation errors.
type UnsafeApiServer interface {
	mustEmbedUnimplementedApiServer()
}

func RegisterApiServer(s grpc.ServiceRegistrar, srv ApiServer) {
	// If the following call pancis, it indicates UnimplementedApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Api_ServiceDesc, srv)
}

func _Api_Sequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.CommandSequence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Sequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_Sequence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Sequence(ctx, req.(*pb.CommandSequence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RawSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.RawCommandSequence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RawSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RawSequence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RawSequence(ctx, req.(*pb.RawCommandSequence))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Command_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.CommandValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).Command(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_Command_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).Command(ctx, req.(*pb.CommandValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RawCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.RawCommandValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RawCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RawCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RawCommand(ctx, req.(*pb.RawCommandValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_Uplink_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ApiServer).Uplink(&grpc.GenericServerStream[pb.UplinkFileChunk, pb.Reply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_UplinkServer = grpc.ClientStreamingServer[pb.UplinkFileChunk, pb.Reply]

func _Api_GetFsw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetFsw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetFsw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetFsw(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AllFsw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AllFsw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_AllFsw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AllFsw(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SubscribeFsw_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).SubscribeFsw(m, &grpc.GenericServerStream[emptypb.Empty, pb.FswList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeFswServer = grpc.ServerStreamingServer[pb.FswList]

func _Api_StartProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).StartProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_StartProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).StartProfile(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_StopProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).StopProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_StopProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).StopProfile(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.ProfileUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).UpdateProfile(ctx, req.(*pb.ProfileUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AddProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Profile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AddProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_AddProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AddProfile(ctx, req.(*pb.Profile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RemoveProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RemoveProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RemoveProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RemoveProfile(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AllProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AllProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_AllProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AllProfiles(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AllProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AllProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_AllProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AllProviders(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SubscribeProviders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).SubscribeProviders(m, &grpc.GenericServerStream[emptypb.Empty, pb.ProfileProviderList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeProvidersServer = grpc.ServerStreamingServer[pb.ProfileProviderList]

func _Api_SubscribeProfiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).SubscribeProfiles(m, &grpc.GenericServerStream[emptypb.Empty, pb.ProfileList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeProfilesServer = grpc.ServerStreamingServer[pb.ProfileList]

func _Api_GetDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).GetDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_GetDictionary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).GetDictionary(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AddDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Dictionary)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AddDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_AddDictionary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AddDictionary(ctx, req.(*pb.Dictionary))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_RemoveDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).RemoveDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_RemoveDictionary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).RemoveDictionary(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_AllDictionary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServer).AllDictionary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Api_AllDictionary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServer).AllDictionary(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Api_SubscribeDictionary_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).SubscribeDictionary(m, &grpc.GenericServerStream[emptypb.Empty, pb.DictionaryList]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubscribeDictionaryServer = grpc.ServerStreamingServer[pb.DictionaryList]

func _Api_SubEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(pb.BusFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).SubEvent(m, &grpc.GenericServerStream[pb.BusFilter, pb.SourcedEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubEventServer = grpc.ServerStreamingServer[pb.SourcedEvent]

func _Api_SubTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(pb.BusFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).SubTelemetry(m, &grpc.GenericServerStream[pb.BusFilter, pb.SourcedTelemetry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubTelemetryServer = grpc.ServerStreamingServer[pb.SourcedTelemetry]

func _Api_SubFileDownlink_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(pb.BusFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApiServer).SubFileDownlink(m, &grpc.GenericServerStream[pb.BusFilter, pb.FileDownlink]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Api_SubFileDownlinkServer = grpc.ServerStreamingServer[pb.FileDownlink]

// Api_ServiceDesc is the grpc.ServiceDesc for Api service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Api_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Api",
	HandlerType: (*ApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sequence",
			Handler:    _Api_Sequence_Handler,
		},
		{
			MethodName: "RawSequence",
			Handler:    _Api_RawSequence_Handler,
		},
		{
			MethodName: "Command",
			Handler:    _Api_Command_Handler,
		},
		{
			MethodName: "RawCommand",
			Handler:    _Api_RawCommand_Handler,
		},
		{
			MethodName: "GetFsw",
			Handler:    _Api_GetFsw_Handler,
		},
		{
			MethodName: "AllFsw",
			Handler:    _Api_AllFsw_Handler,
		},
		{
			MethodName: "StartProfile",
			Handler:    _Api_StartProfile_Handler,
		},
		{
			MethodName: "StopProfile",
			Handler:    _Api_StopProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _Api_UpdateProfile_Handler,
		},
		{
			MethodName: "AddProfile",
			Handler:    _Api_AddProfile_Handler,
		},
		{
			MethodName: "RemoveProfile",
			Handler:    _Api_RemoveProfile_Handler,
		},
		{
			MethodName: "AllProfiles",
			Handler:    _Api_AllProfiles_Handler,
		},
		{
			MethodName: "AllProviders",
			Handler:    _Api_AllProviders_Handler,
		},
		{
			MethodName: "GetDictionary",
			Handler:    _Api_GetDictionary_Handler,
		},
		{
			MethodName: "AddDictionary",
			Handler:    _Api_AddDictionary_Handler,
		},
		{
			MethodName: "RemoveDictionary",
			Handler:    _Api_RemoveDictionary_Handler,
		},
		{
			MethodName: "AllDictionary",
			Handler:    _Api_AllDictionary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Uplink",
			Handler:       _Api_Uplink_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeFsw",
			Handler:       _Api_SubscribeFsw_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeProviders",
			Handler:       _Api_SubscribeProviders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeProfiles",
			Handler:       _Api_SubscribeProfiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeDictionary",
			Handler:       _Api_SubscribeDictionary_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubEvent",
			Handler:       _Api_SubEvent_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubTelemetry",
			Handler:       _Api_SubTelemetry_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubFileDownlink",
			Handler:       _Api_SubFileDownlink_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hermes.proto",
}

const (
	Provider_Connection_FullMethodName = "/Provider/Connection"
	Provider_File_FullMethodName       = "/Provider/File"
	Provider_Event_FullMethodName      = "/Provider/Event"
	Provider_Telemetry_FullMethodName  = "/Provider/Telemetry"
)

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API to provide interface with an external software
type ProviderClient interface {
	// *
	// A long lived connection telling the host that a link is active with
	// some external software (FSW). The server streams in uplink requests which
	// are handled and replied to over this long lived connection.
	//
	// Any downlink comming from this FSW is routed through the other client stream endpoints.
	Connection(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb.FswConnectionPacket, pb.Uplink], error)
	// *
	// Initiate a file downlink session with the host.
	//
	// This request is for a single file downlink session.
	// It should start with a FileHeader and stream byte data
	//
	// TODO(tumbar) Figure out a mechanism for file validation
	File(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.DownlinkFileChunk, emptypb.Empty], error)
	// *
	// Stream events to the host.
	// The client can open as many of these as needed though they should be long-lived.
	Event(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.SourcedEvent, emptypb.Empty], error)
	// *
	// Stream telemetry to the host.
	// The client can open as many of these as needed though they should be long-lived.
	Telemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.SourcedTelemetry, emptypb.Empty], error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Connection(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb.FswConnectionPacket, pb.Uplink], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[0], Provider_Connection_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.FswConnectionPacket, pb.Uplink]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_ConnectionClient = grpc.BidiStreamingClient[pb.FswConnectionPacket, pb.Uplink]

func (c *providerClient) File(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.DownlinkFileChunk, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[1], Provider_File_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.DownlinkFileChunk, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_FileClient = grpc.ClientStreamingClient[pb.DownlinkFileChunk, emptypb.Empty]

func (c *providerClient) Event(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.SourcedEvent, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[2], Provider_Event_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.SourcedEvent, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_EventClient = grpc.ClientStreamingClient[pb.SourcedEvent, emptypb.Empty]

func (c *providerClient) Telemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[pb.SourcedTelemetry, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[3], Provider_Telemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb.SourcedTelemetry, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_TelemetryClient = grpc.ClientStreamingClient[pb.SourcedTelemetry, emptypb.Empty]

// ProviderServer is the server API for Provider service.
// All implementations must embed UnimplementedProviderServer
// for forward compatibility.
//
// API to provide interface with an external software
type ProviderServer interface {
	// *
	// A long lived connection telling the host that a link is active with
	// some external software (FSW). The server streams in uplink requests which
	// are handled and replied to over this long lived connection.
	//
	// Any downlink comming from this FSW is routed through the other client stream endpoints.
	Connection(grpc.BidiStreamingServer[pb.FswConnectionPacket, pb.Uplink]) error
	// *
	// Initiate a file downlink session with the host.
	//
	// This request is for a single file downlink session.
	// It should start with a FileHeader and stream byte data
	//
	// TODO(tumbar) Figure out a mechanism for file validation
	File(grpc.ClientStreamingServer[pb.DownlinkFileChunk, emptypb.Empty]) error
	// *
	// Stream events to the host.
	// The client can open as many of these as needed though they should be long-lived.
	Event(grpc.ClientStreamingServer[pb.SourcedEvent, emptypb.Empty]) error
	// *
	// Stream telemetry to the host.
	// The client can open as many of these as needed though they should be long-lived.
	Telemetry(grpc.ClientStreamingServer[pb.SourcedTelemetry, emptypb.Empty]) error
	mustEmbedUnimplementedProviderServer()
}

// UnimplementedProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServer struct{}

func (UnimplementedProviderServer) Connection(grpc.BidiStreamingServer[pb.FswConnectionPacket, pb.Uplink]) error {
	return status.Errorf(codes.Unimplemented, "method Connection not implemented")
}
func (UnimplementedProviderServer) File(grpc.ClientStreamingServer[pb.DownlinkFileChunk, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method File not implemented")
}
func (UnimplementedProviderServer) Event(grpc.ClientStreamingServer[pb.SourcedEvent, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Event not implemented")
}
func (UnimplementedProviderServer) Telemetry(grpc.ClientStreamingServer[pb.SourcedTelemetry, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method Telemetry not implemented")
}
func (UnimplementedProviderServer) mustEmbedUnimplementedProviderServer() {}
func (UnimplementedProviderServer) testEmbeddedByValue()                  {}

// UnsafeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServer will
// result in compilation errors.
type UnsafeProviderServer interface {
	mustEmbedUnimplementedProviderServer()
}

func RegisterProviderServer(s grpc.ServiceRegistrar, srv ProviderServer) {
	// If the following call pancis, it indicates UnimplementedProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Provider_ServiceDesc, srv)
}

func _Provider_Connection_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServer).Connection(&grpc.GenericServerStream[pb.FswConnectionPacket, pb.Uplink]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_ConnectionServer = grpc.BidiStreamingServer[pb.FswConnectionPacket, pb.Uplink]

func _Provider_File_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServer).File(&grpc.GenericServerStream[pb.DownlinkFileChunk, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_FileServer = grpc.ClientStreamingServer[pb.DownlinkFileChunk, emptypb.Empty]

func _Provider_Event_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServer).Event(&grpc.GenericServerStream[pb.SourcedEvent, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_EventServer = grpc.ClientStreamingServer[pb.SourcedEvent, emptypb.Empty]

func _Provider_Telemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServer).Telemetry(&grpc.GenericServerStream[pb.SourcedTelemetry, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_TelemetryServer = grpc.ClientStreamingServer[pb.SourcedTelemetry, emptypb.Empty]

// Provider_ServiceDesc is the grpc.ServiceDesc for Provider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connection",
			Handler:       _Provider_Connection_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "File",
			Handler:       _Provider_File_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Event",
			Handler:       _Provider_Event_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Telemetry",
			Handler:       _Provider_Telemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "hermes.proto",
}
