// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: hermes.proto

package grpc

import (
	pb "github.com/nasa/hermes/pkg/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hermes_proto protoreflect.FileDescriptor

const file_hermes_proto_rawDesc = "" +
	"\n" +
	"\fhermes.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10dictionary.proto\x1a\n" +
	"file.proto\x1a\tfsw.proto\x1a\tbus.proto\x1a\rprofile.proto\x1a\tmsg.proto2\xe7\v\n" +
	"\x03Api\x12,\n" +
	"\bSequence\x12\x10.CommandSequence\x1a\x0e.SequenceReply\x122\n" +
	"\vRawSequence\x12\x13.RawCommandSequence\x1a\x0e.SequenceReply\x12 \n" +
	"\aCommand\x12\r.CommandValue\x1a\x06.Reply\x12&\n" +
	"\n" +
	"RawCommand\x12\x10.RawCommandValue\x1a\x06.Reply\x12$\n" +
	"\x06Uplink\x12\x10.UplinkFileChunk\x1a\x06.Reply(\x01\x12\x13\n" +
	"\x06GetFsw\x12\x03.Id\x1a\x04.Fsw\x12*\n" +
	"\x06AllFsw\x12\x16.google.protobuf.Empty\x1a\b.FswList\x122\n" +
	"\fSubscribeFsw\x12\x16.google.protobuf.Empty\x1a\b.FswList0\x01\x12+\n" +
	"\fStartProfile\x12\x03.Id\x1a\x16.google.protobuf.Empty\x12*\n" +
	"\vStopProfile\x12\x03.Id\x1a\x16.google.protobuf.Empty\x127\n" +
	"\rUpdateProfile\x12\x0e.ProfileUpdate\x1a\x16.google.protobuf.Empty\x12\x1b\n" +
	"\n" +
	"AddProfile\x12\b.Profile\x1a\x03.Id\x12,\n" +
	"\rRemoveProfile\x12\x03.Id\x1a\x16.google.protobuf.Empty\x123\n" +
	"\vAllProfiles\x12\x16.google.protobuf.Empty\x1a\f.ProfileList\x12<\n" +
	"\fAllProviders\x12\x16.google.protobuf.Empty\x1a\x14.ProfileProviderList\x12B\n" +
	"\x14GetFileTransferState\x12\x16.google.protobuf.Empty\x1a\x12.FileTransferState\x12L\n" +
	"\x1aClearDownlinkTransferState\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x18ClearUplinkTransferState\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\x12SubscribeProviders\x12\x16.google.protobuf.Empty\x1a\x14.ProfileProviderList0\x01\x12;\n" +
	"\x11SubscribeProfiles\x12\x16.google.protobuf.Empty\x1a\f.ProfileList0\x01\x12!\n" +
	"\rGetDictionary\x12\x03.Id\x1a\v.Dictionary\x12!\n" +
	"\rAddDictionary\x12\v.Dictionary\x1a\x03.Id\x12/\n" +
	"\x10RemoveDictionary\x12\x03.Id\x1a\x16.google.protobuf.Empty\x128\n" +
	"\rAllDictionary\x12\x16.google.protobuf.Empty\x1a\x0f.DictionaryList\x12@\n" +
	"\x13SubscribeDictionary\x12\x16.google.protobuf.Empty\x1a\x0f.DictionaryList0\x01\x12'\n" +
	"\bSubEvent\x12\n" +
	".BusFilter\x1a\r.SourcedEvent0\x01\x12/\n" +
	"\fSubTelemetry\x12\n" +
	".BusFilter\x1a\x11.SourcedTelemetry0\x01\x12.\n" +
	"\x0fSubFileDownlink\x12\n" +
	".BusFilter\x1a\r.FileDownlink0\x01\x12*\n" +
	"\rSubFileUplink\x12\n" +
	".BusFilter\x1a\v.FileUplink0\x01\x12?\n" +
	"\x0fSubFileTransfer\x12\x16.google.protobuf.Empty\x1a\x12.FileTransferState0\x012\xdd\x01\n" +
	"\bProvider\x12/\n" +
	"\n" +
	"Connection\x12\x14.FswConnectionPacket\x1a\a.Uplink(\x010\x01\x124\n" +
	"\x04File\x12\x12.DownlinkFileChunk\x1a\x16.google.protobuf.Empty(\x01\x120\n" +
	"\x05Event\x12\r.SourcedEvent\x1a\x16.google.protobuf.Empty(\x01\x128\n" +
	"\tTelemetry\x12\x11.SourcedTelemetry\x1a\x16.google.protobuf.Empty(\x01B!Z\x1fgithub.com/nasa/hermes/pkg/grpcb\x06proto3"

var file_hermes_proto_goTypes = []any{
	(*pb.CommandSequence)(nil),     // 0: CommandSequence
	(*pb.RawCommandSequence)(nil),  // 1: RawCommandSequence
	(*pb.CommandValue)(nil),        // 2: CommandValue
	(*pb.RawCommandValue)(nil),     // 3: RawCommandValue
	(*pb.UplinkFileChunk)(nil),     // 4: UplinkFileChunk
	(*pb.Id)(nil),                  // 5: Id
	(*emptypb.Empty)(nil),          // 6: google.protobuf.Empty
	(*pb.ProfileUpdate)(nil),       // 7: ProfileUpdate
	(*pb.Profile)(nil),             // 8: Profile
	(*pb.Dictionary)(nil),          // 9: Dictionary
	(*pb.BusFilter)(nil),           // 10: BusFilter
	(*pb.FswConnectionPacket)(nil), // 11: FswConnectionPacket
	(*pb.DownlinkFileChunk)(nil),   // 12: DownlinkFileChunk
	(*pb.SourcedEvent)(nil),        // 13: SourcedEvent
	(*pb.SourcedTelemetry)(nil),    // 14: SourcedTelemetry
	(*pb.SequenceReply)(nil),       // 15: SequenceReply
	(*pb.Reply)(nil),               // 16: Reply
	(*pb.Fsw)(nil),                 // 17: Fsw
	(*pb.FswList)(nil),             // 18: FswList
	(*pb.ProfileList)(nil),         // 19: ProfileList
	(*pb.ProfileProviderList)(nil), // 20: ProfileProviderList
	(*pb.FileTransferState)(nil),   // 21: FileTransferState
	(*pb.DictionaryList)(nil),      // 22: DictionaryList
	(*pb.FileDownlink)(nil),        // 23: FileDownlink
	(*pb.FileUplink)(nil),          // 24: FileUplink
	(*pb.Uplink)(nil),              // 25: Uplink
}
var file_hermes_proto_depIdxs = []int32{
	0,  // 0: Api.Sequence:input_type -> CommandSequence
	1,  // 1: Api.RawSequence:input_type -> RawCommandSequence
	2,  // 2: Api.Command:input_type -> CommandValue
	3,  // 3: Api.RawCommand:input_type -> RawCommandValue
	4,  // 4: Api.Uplink:input_type -> UplinkFileChunk
	5,  // 5: Api.GetFsw:input_type -> Id
	6,  // 6: Api.AllFsw:input_type -> google.protobuf.Empty
	6,  // 7: Api.SubscribeFsw:input_type -> google.protobuf.Empty
	5,  // 8: Api.StartProfile:input_type -> Id
	5,  // 9: Api.StopProfile:input_type -> Id
	7,  // 10: Api.UpdateProfile:input_type -> ProfileUpdate
	8,  // 11: Api.AddProfile:input_type -> Profile
	5,  // 12: Api.RemoveProfile:input_type -> Id
	6,  // 13: Api.AllProfiles:input_type -> google.protobuf.Empty
	6,  // 14: Api.AllProviders:input_type -> google.protobuf.Empty
	6,  // 15: Api.GetFileTransferState:input_type -> google.protobuf.Empty
	6,  // 16: Api.ClearDownlinkTransferState:input_type -> google.protobuf.Empty
	6,  // 17: Api.ClearUplinkTransferState:input_type -> google.protobuf.Empty
	6,  // 18: Api.SubscribeProviders:input_type -> google.protobuf.Empty
	6,  // 19: Api.SubscribeProfiles:input_type -> google.protobuf.Empty
	5,  // 20: Api.GetDictionary:input_type -> Id
	9,  // 21: Api.AddDictionary:input_type -> Dictionary
	5,  // 22: Api.RemoveDictionary:input_type -> Id
	6,  // 23: Api.AllDictionary:input_type -> google.protobuf.Empty
	6,  // 24: Api.SubscribeDictionary:input_type -> google.protobuf.Empty
	10, // 25: Api.SubEvent:input_type -> BusFilter
	10, // 26: Api.SubTelemetry:input_type -> BusFilter
	10, // 27: Api.SubFileDownlink:input_type -> BusFilter
	10, // 28: Api.SubFileUplink:input_type -> BusFilter
	6,  // 29: Api.SubFileTransfer:input_type -> google.protobuf.Empty
	11, // 30: Provider.Connection:input_type -> FswConnectionPacket
	12, // 31: Provider.File:input_type -> DownlinkFileChunk
	13, // 32: Provider.Event:input_type -> SourcedEvent
	14, // 33: Provider.Telemetry:input_type -> SourcedTelemetry
	15, // 34: Api.Sequence:output_type -> SequenceReply
	15, // 35: Api.RawSequence:output_type -> SequenceReply
	16, // 36: Api.Command:output_type -> Reply
	16, // 37: Api.RawCommand:output_type -> Reply
	16, // 38: Api.Uplink:output_type -> Reply
	17, // 39: Api.GetFsw:output_type -> Fsw
	18, // 40: Api.AllFsw:output_type -> FswList
	18, // 41: Api.SubscribeFsw:output_type -> FswList
	6,  // 42: Api.StartProfile:output_type -> google.protobuf.Empty
	6,  // 43: Api.StopProfile:output_type -> google.protobuf.Empty
	6,  // 44: Api.UpdateProfile:output_type -> google.protobuf.Empty
	5,  // 45: Api.AddProfile:output_type -> Id
	6,  // 46: Api.RemoveProfile:output_type -> google.protobuf.Empty
	19, // 47: Api.AllProfiles:output_type -> ProfileList
	20, // 48: Api.AllProviders:output_type -> ProfileProviderList
	21, // 49: Api.GetFileTransferState:output_type -> FileTransferState
	6,  // 50: Api.ClearDownlinkTransferState:output_type -> google.protobuf.Empty
	6,  // 51: Api.ClearUplinkTransferState:output_type -> google.protobuf.Empty
	20, // 52: Api.SubscribeProviders:output_type -> ProfileProviderList
	19, // 53: Api.SubscribeProfiles:output_type -> ProfileList
	9,  // 54: Api.GetDictionary:output_type -> Dictionary
	5,  // 55: Api.AddDictionary:output_type -> Id
	6,  // 56: Api.RemoveDictionary:output_type -> google.protobuf.Empty
	22, // 57: Api.AllDictionary:output_type -> DictionaryList
	22, // 58: Api.SubscribeDictionary:output_type -> DictionaryList
	13, // 59: Api.SubEvent:output_type -> SourcedEvent
	14, // 60: Api.SubTelemetry:output_type -> SourcedTelemetry
	23, // 61: Api.SubFileDownlink:output_type -> FileDownlink
	24, // 62: Api.SubFileUplink:output_type -> FileUplink
	21, // 63: Api.SubFileTransfer:output_type -> FileTransferState
	25, // 64: Provider.Connection:output_type -> Uplink
	6,  // 65: Provider.File:output_type -> google.protobuf.Empty
	6,  // 66: Provider.Event:output_type -> google.protobuf.Empty
	6,  // 67: Provider.Telemetry:output_type -> google.protobuf.Empty
	34, // [34:68] is the sub-list for method output_type
	0,  // [0:34] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_hermes_proto_init() }
func file_hermes_proto_init() {
	if File_hermes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hermes_proto_rawDesc), len(file_hermes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_hermes_proto_goTypes,
		DependencyIndexes: file_hermes_proto_depIdxs,
	}.Build()
	File_hermes_proto = out.File
	file_hermes_proto_goTypes = nil
	file_hermes_proto_depIdxs = nil
}
