// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: bus.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceContextFilter int32

const (
	// Only subscribe to realtime data
	SourceContextFilter_REALTIME_ONLY SourceContextFilter = 0
	// Only subscribe to recorded data
	SourceContextFilter_RECORDED_ONLY SourceContextFilter = 1
	// Subscribe to all recorded and realtime data
	SourceContextFilter_ALL SourceContextFilter = 2
)

// Enum value maps for SourceContextFilter.
var (
	SourceContextFilter_name = map[int32]string{
		0: "REALTIME_ONLY",
		1: "RECORDED_ONLY",
		2: "ALL",
	}
	SourceContextFilter_value = map[string]int32{
		"REALTIME_ONLY": 0,
		"RECORDED_ONLY": 1,
		"ALL":           2,
	}
)

func (x SourceContextFilter) Enum() *SourceContextFilter {
	p := new(SourceContextFilter)
	*p = x
	return p
}

func (x SourceContextFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceContextFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_bus_proto_enumTypes[0].Descriptor()
}

func (SourceContextFilter) Type() protoreflect.EnumType {
	return &file_bus_proto_enumTypes[0]
}

func (x SourceContextFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceContextFilter.Descriptor instead.
func (SourceContextFilter) EnumDescriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{0}
}

type SourceContext int32

const (
	// Telemetry item was emitted and downlinked in realtime
	// rather than recorded and downlinked later
	SourceContext_REALTIME SourceContext = 0
	// Telemetry item was recorded on-board and downlinked.
	// These are generally data products.
	SourceContext_RECORDED SourceContext = 1
)

// Enum value maps for SourceContext.
var (
	SourceContext_name = map[int32]string{
		0: "REALTIME",
		1: "RECORDED",
	}
	SourceContext_value = map[string]int32{
		"REALTIME": 0,
		"RECORDED": 1,
	}
)

func (x SourceContext) Enum() *SourceContext {
	p := new(SourceContext)
	*p = x
	return p
}

func (x SourceContext) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceContext) Descriptor() protoreflect.EnumDescriptor {
	return file_bus_proto_enumTypes[1].Descriptor()
}

func (SourceContext) Type() protoreflect.EnumType {
	return &file_bus_proto_enumTypes[1]
}

func (x SourceContext) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceContext.Descriptor instead.
func (SourceContext) EnumDescriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{1}
}

type FileDownlinkCompletionStatus int32

const (
	// File downlinked successfully and validated fully
	FileDownlinkCompletionStatus_DOWNLINK_COMPLETED FileDownlinkCompletionStatus = 0
	// Something failed during downlink and a valid status was not set
	FileDownlinkCompletionStatus_DOWNLINK_UNKNOWN FileDownlinkCompletionStatus = -1
	// File partially downlinked and there are some missing chunks
	FileDownlinkCompletionStatus_DOWNLINK_PARTIAL FileDownlinkCompletionStatus = 1
	// File downlinked fully (i.e. no missing chunks) but the CRC failed
	FileDownlinkCompletionStatus_DOWNLINK_CRC_FAILED FileDownlinkCompletionStatus = 2
)

// Enum value maps for FileDownlinkCompletionStatus.
var (
	FileDownlinkCompletionStatus_name = map[int32]string{
		0:  "DOWNLINK_COMPLETED",
		-1: "DOWNLINK_UNKNOWN",
		1:  "DOWNLINK_PARTIAL",
		2:  "DOWNLINK_CRC_FAILED",
	}
	FileDownlinkCompletionStatus_value = map[string]int32{
		"DOWNLINK_COMPLETED":  0,
		"DOWNLINK_UNKNOWN":    -1,
		"DOWNLINK_PARTIAL":    1,
		"DOWNLINK_CRC_FAILED": 2,
	}
)

func (x FileDownlinkCompletionStatus) Enum() *FileDownlinkCompletionStatus {
	p := new(FileDownlinkCompletionStatus)
	*p = x
	return p
}

func (x FileDownlinkCompletionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileDownlinkCompletionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_bus_proto_enumTypes[2].Descriptor()
}

func (FileDownlinkCompletionStatus) Type() protoreflect.EnumType {
	return &file_bus_proto_enumTypes[2]
}

func (x FileDownlinkCompletionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileDownlinkCompletionStatus.Descriptor instead.
func (FileDownlinkCompletionStatus) EnumDescriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{2}
}

type BusFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// (optional) filter to limit subscription streams by fsw id
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// (optional) Listen to a subset of ids
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	// Filter whether to get recorded vs realtime data streams
	Context       SourceContextFilter `protobuf:"varint,3,opt,name=context,proto3,enum=SourceContextFilter" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusFilter) Reset() {
	*x = BusFilter{}
	mi := &file_bus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusFilter) ProtoMessage() {}

func (x *BusFilter) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusFilter.ProtoReflect.Descriptor instead.
func (*BusFilter) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{0}
}

func (x *BusFilter) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BusFilter) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *BusFilter) GetContext() SourceContextFilter {
	if x != nil {
		return x.Context
	}
	return SourceContextFilter_REALTIME_ONLY
}

// Event telemetry
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dictionary entry definition of event
	Ref *EventRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Timestamp of when the event is emitted by its source (FSW or otherwise)
	Time *Time `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// final formatted EVR message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// (optional) parsed arguments before message is formatted
	Args []*Value `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	// (optional) tags to attach to the EVR for additional context
	Tags          map[string]*Value `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_bus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetRef() *EventRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Event) GetTime() *Time {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetArgs() []*Value {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Event) GetTags() map[string]*Value {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Channelized telemetry
type Telemetry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dictionary entry definition of telemetry
	Ref *TelemetryRef `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Timestamp of when channel is emitted by its source (FSW or otherwise)
	Time *Time `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// Packed telemetry value
	Value *Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// An optional set of tags to add cardinality to this telemetry
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_bus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{2}
}

func (x *Telemetry) GetRef() *TelemetryRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Telemetry) GetTime() *Time {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Telemetry) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Telemetry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type SourcedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Context       SourceContext          `protobuf:"varint,3,opt,name=context,proto3,enum=SourceContext" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcedEvent) Reset() {
	*x = SourcedEvent{}
	mi := &file_bus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcedEvent) ProtoMessage() {}

func (x *SourcedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcedEvent.ProtoReflect.Descriptor instead.
func (*SourcedEvent) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{3}
}

func (x *SourcedEvent) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SourcedEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SourcedEvent) GetContext() SourceContext {
	if x != nil {
		return x.Context
	}
	return SourceContext_REALTIME
}

type SourcedTelemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telemetry     *Telemetry             `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Context       SourceContext          `protobuf:"varint,3,opt,name=context,proto3,enum=SourceContext" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcedTelemetry) Reset() {
	*x = SourcedTelemetry{}
	mi := &file_bus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcedTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcedTelemetry) ProtoMessage() {}

func (x *SourcedTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcedTelemetry.ProtoReflect.Descriptor instead.
func (*SourcedTelemetry) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{4}
}

func (x *SourcedTelemetry) GetTelemetry() *Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *SourcedTelemetry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SourcedTelemetry) GetContext() SourceContext {
	if x != nil {
		return x.Context
	}
	return SourceContext_REALTIME
}

type FileDownlinkChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset in bytes from the start of the file
	Offset uint64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Size in bytes of this chunk
	Size          uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownlinkChunk) Reset() {
	*x = FileDownlinkChunk{}
	mi := &file_bus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownlinkChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownlinkChunk) ProtoMessage() {}

func (x *FileDownlinkChunk) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownlinkChunk.ProtoReflect.Descriptor instead.
func (*FileDownlinkChunk) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{5}
}

func (x *FileDownlinkChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileDownlinkChunk) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileDownlink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Time when downlink started (ground time)
	TimeStart *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timeStart,proto3" json:"timeStart,omitempty"`
	// Time when downlink ended
	TimeEnd *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timeEnd,proto3" json:"timeEnd,omitempty"`
	// Status of the file downlink
	Status FileDownlinkCompletionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=FileDownlinkCompletionStatus" json:"status,omitempty"`
	// FSW source ID
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// Source relative path where this was downlinked from
	SourcePath string `protobuf:"bytes,6,opt,name=sourcePath,proto3" json:"sourcePath,omitempty"`
	// (optional) destination path requested during downlink
	DestinationPath string `protobuf:"bytes,7,opt,name=destinationPath,proto3" json:"destinationPath,omitempty"`
	// Absolute path on the host machine where the raw file is stored
	FilePath string `protobuf:"bytes,8,opt,name=filePath,proto3" json:"filePath,omitempty"`
	// Set of chunks that are missing if this is a partial downlink
	MissingChunks []*FileDownlinkChunk `protobuf:"bytes,9,rep,name=missingChunks,proto3" json:"missingChunks,omitempty"`
	// It's possible sections of the file overlap
	DuplicateChunks []*FileDownlinkChunk `protobuf:"bytes,10,rep,name=duplicateChunks,proto3" json:"duplicateChunks,omitempty"`
	// Size in bytes
	Size uint64 `protobuf:"varint,11,opt,name=size,proto3" json:"size,omitempty"`
	// Additional metadata in the form tag -> json
	Metadata      map[string]string `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownlink) Reset() {
	*x = FileDownlink{}
	mi := &file_bus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownlink) ProtoMessage() {}

func (x *FileDownlink) ProtoReflect() protoreflect.Message {
	mi := &file_bus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownlink.ProtoReflect.Descriptor instead.
func (*FileDownlink) Descriptor() ([]byte, []int) {
	return file_bus_proto_rawDescGZIP(), []int{6}
}

func (x *FileDownlink) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *FileDownlink) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *FileDownlink) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *FileDownlink) GetStatus() FileDownlinkCompletionStatus {
	if x != nil {
		return x.Status
	}
	return FileDownlinkCompletionStatus_DOWNLINK_COMPLETED
}

func (x *FileDownlink) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileDownlink) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *FileDownlink) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *FileDownlink) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileDownlink) GetMissingChunks() []*FileDownlinkChunk {
	if x != nil {
		return x.MissingChunks
	}
	return nil
}

func (x *FileDownlink) GetDuplicateChunks() []*FileDownlinkChunk {
	if x != nil {
		return x.DuplicateChunks
	}
	return nil
}

func (x *FileDownlink) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileDownlink) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_bus_proto protoreflect.FileDescriptor

const file_bus_proto_rawDesc = "" +
	"\n" +
	"\tbus.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\n" +
	"type.proto\x1a\x10dictionary.proto\x1a\n" +
	"time.proto\"i\n" +
	"\tBusFilter\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\x12.\n" +
	"\acontext\x18\x03 \x01(\x0e2\x14.SourceContextFilterR\acontext\"\xdc\x01\n" +
	"\x05Event\x12\x1b\n" +
	"\x03ref\x18\x01 \x01(\v2\t.EventRefR\x03ref\x12\x19\n" +
	"\x04time\x18\x02 \x01(\v2\x05.TimeR\x04time\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\x04args\x18\x04 \x03(\v2\x06.ValueR\x04args\x12$\n" +
	"\x04tags\x18\x05 \x03(\v2\x10.Event.TagsEntryR\x04tags\x1a?\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\x05value\x18\x02 \x01(\v2\x06.ValueR\x05value:\x028\x01\"\xd6\x01\n" +
	"\tTelemetry\x12\x1f\n" +
	"\x03ref\x18\x01 \x01(\v2\r.TelemetryRefR\x03ref\x12\x19\n" +
	"\x04time\x18\x02 \x01(\v2\x05.TimeR\x04time\x12\x1c\n" +
	"\x05value\x18\x03 \x01(\v2\x06.ValueR\x05value\x12.\n" +
	"\x06labels\x18\x04 \x03(\v2\x16.Telemetry.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06\"n\n" +
	"\fSourcedEvent\x12\x1c\n" +
	"\x05event\x18\x01 \x01(\v2\x06.EventR\x05event\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12(\n" +
	"\acontext\x18\x03 \x01(\x0e2\x0e.SourceContextR\acontext\"~\n" +
	"\x10SourcedTelemetry\x12(\n" +
	"\ttelemetry\x18\x01 \x01(\v2\n" +
	".TelemetryR\ttelemetry\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12(\n" +
	"\acontext\x18\x03 \x01(\x0e2\x0e.SourceContextR\acontext\"?\n" +
	"\x11FileDownlinkChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\xc7\x04\n" +
	"\fFileDownlink\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x128\n" +
	"\ttimeStart\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x124\n" +
	"\atimeEnd\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\x125\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1d.FileDownlinkCompletionStatusR\x06status\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"sourcePath\x18\x06 \x01(\tR\n" +
	"sourcePath\x12(\n" +
	"\x0fdestinationPath\x18\a \x01(\tR\x0fdestinationPath\x12\x1a\n" +
	"\bfilePath\x18\b \x01(\tR\bfilePath\x128\n" +
	"\rmissingChunks\x18\t \x03(\v2\x12.FileDownlinkChunkR\rmissingChunks\x12<\n" +
	"\x0fduplicateChunks\x18\n" +
	" \x03(\v2\x12.FileDownlinkChunkR\x0fduplicateChunks\x12\x12\n" +
	"\x04size\x18\v \x01(\x04R\x04size\x127\n" +
	"\bmetadata\x18\f \x03(\v2\x1b.FileDownlink.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*D\n" +
	"\x13SourceContextFilter\x12\x11\n" +
	"\rREALTIME_ONLY\x10\x00\x12\x11\n" +
	"\rRECORDED_ONLY\x10\x01\x12\a\n" +
	"\x03ALL\x10\x02*+\n" +
	"\rSourceContext\x12\f\n" +
	"\bREALTIME\x10\x00\x12\f\n" +
	"\bRECORDED\x10\x01*\x84\x01\n" +
	"\x1cFileDownlinkCompletionStatus\x12\x16\n" +
	"\x12DOWNLINK_COMPLETED\x10\x00\x12\x1d\n" +
	"\x10DOWNLINK_UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x14\n" +
	"\x10DOWNLINK_PARTIAL\x10\x01\x12\x17\n" +
	"\x13DOWNLINK_CRC_FAILED\x10\x02B\x1fZ\x1dgithub.com/nasa/hermes/pkg/pbb\x06proto3"

var (
	file_bus_proto_rawDescOnce sync.Once
	file_bus_proto_rawDescData []byte
)

func file_bus_proto_rawDescGZIP() []byte {
	file_bus_proto_rawDescOnce.Do(func() {
		file_bus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bus_proto_rawDesc), len(file_bus_proto_rawDesc)))
	})
	return file_bus_proto_rawDescData
}

var file_bus_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bus_proto_goTypes = []any{
	(SourceContextFilter)(0),          // 0: SourceContextFilter
	(SourceContext)(0),                // 1: SourceContext
	(FileDownlinkCompletionStatus)(0), // 2: FileDownlinkCompletionStatus
	(*BusFilter)(nil),                 // 3: BusFilter
	(*Event)(nil),                     // 4: Event
	(*Telemetry)(nil),                 // 5: Telemetry
	(*SourcedEvent)(nil),              // 6: SourcedEvent
	(*SourcedTelemetry)(nil),          // 7: SourcedTelemetry
	(*FileDownlinkChunk)(nil),         // 8: FileDownlinkChunk
	(*FileDownlink)(nil),              // 9: FileDownlink
	nil,                               // 10: Event.TagsEntry
	nil,                               // 11: Telemetry.LabelsEntry
	nil,                               // 12: FileDownlink.MetadataEntry
	(*EventRef)(nil),                  // 13: EventRef
	(*Time)(nil),                      // 14: Time
	(*Value)(nil),                     // 15: Value
	(*TelemetryRef)(nil),              // 16: TelemetryRef
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_bus_proto_depIdxs = []int32{
	0,  // 0: BusFilter.context:type_name -> SourceContextFilter
	13, // 1: Event.ref:type_name -> EventRef
	14, // 2: Event.time:type_name -> Time
	15, // 3: Event.args:type_name -> Value
	10, // 4: Event.tags:type_name -> Event.TagsEntry
	16, // 5: Telemetry.ref:type_name -> TelemetryRef
	14, // 6: Telemetry.time:type_name -> Time
	15, // 7: Telemetry.value:type_name -> Value
	11, // 8: Telemetry.labels:type_name -> Telemetry.LabelsEntry
	4,  // 9: SourcedEvent.event:type_name -> Event
	1,  // 10: SourcedEvent.context:type_name -> SourceContext
	5,  // 11: SourcedTelemetry.telemetry:type_name -> Telemetry
	1,  // 12: SourcedTelemetry.context:type_name -> SourceContext
	17, // 13: FileDownlink.timeStart:type_name -> google.protobuf.Timestamp
	17, // 14: FileDownlink.timeEnd:type_name -> google.protobuf.Timestamp
	2,  // 15: FileDownlink.status:type_name -> FileDownlinkCompletionStatus
	8,  // 16: FileDownlink.missingChunks:type_name -> FileDownlinkChunk
	8,  // 17: FileDownlink.duplicateChunks:type_name -> FileDownlinkChunk
	12, // 18: FileDownlink.metadata:type_name -> FileDownlink.MetadataEntry
	15, // 19: Event.TagsEntry.value:type_name -> Value
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_bus_proto_init() }
func file_bus_proto_init() {
	if File_bus_proto != nil {
		return
	}
	file_type_proto_init()
	file_dictionary_proto_init()
	file_time_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bus_proto_rawDesc), len(file_bus_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bus_proto_goTypes,
		DependencyIndexes: file_bus_proto_depIdxs,
		EnumInfos:         file_bus_proto_enumTypes,
		MessageInfos:      file_bus_proto_msgTypes,
	}.Build()
	File_bus_proto = out.File
	file_bus_proto_goTypes = nil
	file_bus_proto_depIdxs = nil
}
