// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: dictionary.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvrSeverity int32

const (
	EvrSeverity_EVR_DIAGNOSTIC    EvrSeverity = 0
	EvrSeverity_EVR_ACTIVITY_LOW  EvrSeverity = 1
	EvrSeverity_EVR_ACTIVITY_HIGH EvrSeverity = 2
	EvrSeverity_EVR_WARNING_LOW   EvrSeverity = 3
	EvrSeverity_EVR_WARNING_HIGH  EvrSeverity = 4
	EvrSeverity_EVR_COMMAND       EvrSeverity = 5
	EvrSeverity_EVR_FATAL         EvrSeverity = 6
)

// Enum value maps for EvrSeverity.
var (
	EvrSeverity_name = map[int32]string{
		0: "EVR_DIAGNOSTIC",
		1: "EVR_ACTIVITY_LOW",
		2: "EVR_ACTIVITY_HIGH",
		3: "EVR_WARNING_LOW",
		4: "EVR_WARNING_HIGH",
		5: "EVR_COMMAND",
		6: "EVR_FATAL",
	}
	EvrSeverity_value = map[string]int32{
		"EVR_DIAGNOSTIC":    0,
		"EVR_ACTIVITY_LOW":  1,
		"EVR_ACTIVITY_HIGH": 2,
		"EVR_WARNING_LOW":   3,
		"EVR_WARNING_HIGH":  4,
		"EVR_COMMAND":       5,
		"EVR_FATAL":         6,
	}
)

func (x EvrSeverity) Enum() *EvrSeverity {
	p := new(EvrSeverity)
	*p = x
	return p
}

func (x EvrSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvrSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_dictionary_proto_enumTypes[0].Descriptor()
}

func (EvrSeverity) Type() protoreflect.EnumType {
	return &file_dictionary_proto_enumTypes[0]
}

func (x EvrSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvrSeverity.Descriptor instead.
func (EvrSeverity) EnumDescriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{0}
}

type ParameterDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// *
	// Component or module that owns this parameter
	Component string `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	// *
	// Name of the parameter
	// Scoped by its component
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Type  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      string `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterDef) Reset() {
	*x = ParameterDef{}
	mi := &file_dictionary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterDef) ProtoMessage() {}

func (x *ParameterDef) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterDef.ProtoReflect.Descriptor instead.
func (*ParameterDef) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{0}
}

func (x *ParameterDef) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ParameterDef) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ParameterDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterDef) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ParameterDef) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CommandDef struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Opcode int32                  `protobuf:"varint,1,opt,name=opcode,proto3" json:"opcode,omitempty"`
	// *
	// Mnemonic command used to identify this command.
	// FSW may or may not include the module name in the mnemonic and its
	// up to the language parsing software to identify the proper command from mnemonic information.
	//
	// This may have varying meaning across missions
	Mnemonic string `protobuf:"bytes,2,opt,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	// *
	// Parent component or module owning this command
	Component string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	// *
	// Command arguments
	Arguments     []*Field `protobuf:"bytes,4,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Metadata      string   `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandDef) Reset() {
	*x = CommandDef{}
	mi := &file_dictionary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDef) ProtoMessage() {}

func (x *CommandDef) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDef.ProtoReflect.Descriptor instead.
func (*CommandDef) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{1}
}

func (x *CommandDef) GetOpcode() int32 {
	if x != nil {
		return x.Opcode
	}
	return 0
}

func (x *CommandDef) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *CommandDef) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *CommandDef) GetArguments() []*Field {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CommandDef) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type EventDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// *
	// Component or module
	Component string `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	// *
	// Name of the EVR.
	// Scoped by its component
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// Log severity usually stored in the FSW event dictionary
	// For the most part this information is not held in the
	// EVR packet since its redundant for ground software.
	Severity EvrSeverity `protobuf:"varint,4,opt,name=severity,proto3,enum=EvrSeverity" json:"severity,omitempty"`
	// *
	// printf format string that will be formatted via sprintf
	FormatString string `protobuf:"bytes,5,opt,name=formatString,proto3" json:"formatString,omitempty"`
	// *
	// Arguments used inside the format string
	Arguments     []*Field `protobuf:"bytes,6,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Metadata      string   `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDef) Reset() {
	*x = EventDef{}
	mi := &file_dictionary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDef) ProtoMessage() {}

func (x *EventDef) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDef.ProtoReflect.Descriptor instead.
func (*EventDef) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{2}
}

func (x *EventDef) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventDef) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *EventDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventDef) GetSeverity() EvrSeverity {
	if x != nil {
		return x.Severity
	}
	return EvrSeverity_EVR_DIAGNOSTIC
}

func (x *EventDef) GetFormatString() string {
	if x != nil {
		return x.FormatString
	}
	return ""
}

func (x *EventDef) GetArguments() []*Field {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *EventDef) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type EventRef struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Component string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Severity  EvrSeverity            `protobuf:"varint,4,opt,name=severity,proto3,enum=EvrSeverity" json:"severity,omitempty"`
	Arguments []string               `protobuf:"bytes,5,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// (optional) dictionary ID this comes from
	Dictionary    string `protobuf:"bytes,10,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRef) Reset() {
	*x = EventRef{}
	mi := &file_dictionary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRef) ProtoMessage() {}

func (x *EventRef) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRef.ProtoReflect.Descriptor instead.
func (*EventRef) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{3}
}

func (x *EventRef) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventRef) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *EventRef) GetSeverity() EvrSeverity {
	if x != nil {
		return x.Severity
	}
	return EvrSeverity_EVR_DIAGNOSTIC
}

func (x *EventRef) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *EventRef) GetDictionary() string {
	if x != nil {
		return x.Dictionary
	}
	return ""
}

type TelemetryDef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Raw ID used for identifying incoming serialized telemetry
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// *
	// Telemetry name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// Component or module that owns this telemetry
	Component string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	// *
	// Serialization type
	Type          *Type  `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Metadata      string `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryDef) Reset() {
	*x = TelemetryDef{}
	mi := &file_dictionary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryDef) ProtoMessage() {}

func (x *TelemetryDef) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryDef.ProtoReflect.Descriptor instead.
func (*TelemetryDef) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryDef) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TelemetryDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TelemetryDef) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *TelemetryDef) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *TelemetryDef) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// Lightweight reference for passing dictionary items through message busses
type TelemetryRef struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Component string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	// (optional) dictionary ID this comes from
	Dictionary    string `protobuf:"bytes,10,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRef) Reset() {
	*x = TelemetryRef{}
	mi := &file_dictionary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRef) ProtoMessage() {}

func (x *TelemetryRef) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRef.ProtoReflect.Descriptor instead.
func (*TelemetryRef) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryRef) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TelemetryRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TelemetryRef) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *TelemetryRef) GetDictionary() string {
	if x != nil {
		return x.Dictionary
	}
	return ""
}

type DictionaryHead struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Type associated with the Fsw.type
	// This will filter the user's selection
	// of dictionaries that can be tracked.
	//
	// This is set by the provider.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// *
	// Name given to dictionary, can be changed by the user
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// (optional) Dictionary/FSW release version
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryHead) Reset() {
	*x = DictionaryHead{}
	mi := &file_dictionary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryHead) ProtoMessage() {}

func (x *DictionaryHead) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryHead.ProtoReflect.Descriptor instead.
func (*DictionaryHead) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{6}
}

func (x *DictionaryHead) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DictionaryHead) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DictionaryHead) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DictionaryNamespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map keys have per-dictionary/mission meaning
	// All items will be constructor into a DualKeyMap with id+key
	Commands   map[string]*CommandDef   `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Events     map[string]*EventDef     `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Telemetry  map[string]*TelemetryDef `protobuf:"bytes,3,rep,name=telemetry,proto3" json:"telemetry,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Parameters map[string]*ParameterDef `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are externally referenced
	// These are resolved on loading
	Types         map[string]*Type `protobuf:"bytes,5,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryNamespace) Reset() {
	*x = DictionaryNamespace{}
	mi := &file_dictionary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryNamespace) ProtoMessage() {}

func (x *DictionaryNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryNamespace.ProtoReflect.Descriptor instead.
func (*DictionaryNamespace) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{7}
}

func (x *DictionaryNamespace) GetCommands() map[string]*CommandDef {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *DictionaryNamespace) GetEvents() map[string]*EventDef {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DictionaryNamespace) GetTelemetry() map[string]*TelemetryDef {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *DictionaryNamespace) GetParameters() map[string]*ParameterDef {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *DictionaryNamespace) GetTypes() map[string]*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

type Dictionary struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Head          *DictionaryHead                 `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Content       map[string]*DictionaryNamespace `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string               `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dictionary) Reset() {
	*x = Dictionary{}
	mi := &file_dictionary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dictionary) ProtoMessage() {}

func (x *Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dictionary.ProtoReflect.Descriptor instead.
func (*Dictionary) Descriptor() ([]byte, []int) {
	return file_dictionary_proto_rawDescGZIP(), []int{8}
}

func (x *Dictionary) GetHead() *DictionaryHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Dictionary) GetContent() map[string]*DictionaryNamespace {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Dictionary) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_dictionary_proto protoreflect.FileDescriptor

const file_dictionary_proto_rawDesc = "" +
	"\n" +
	"\x10dictionary.proto\x1a\n" +
	"type.proto\"\x87\x01\n" +
	"\fParameterDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\x04type\x18\x04 \x01(\v2\x05.TypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"\xa0\x01\n" +
	"\n" +
	"CommandDef\x12\x16\n" +
	"\x06opcode\x18\x01 \x01(\x05R\x06opcode\x12\x1a\n" +
	"\bmnemonic\x18\x02 \x01(\tR\bmnemonic\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12$\n" +
	"\targuments\x18\x04 \x03(\v2\x06.FieldR\targuments\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"\xdc\x01\n" +
	"\bEventDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12(\n" +
	"\bseverity\x18\x04 \x01(\x0e2\f.EvrSeverityR\bseverity\x12\"\n" +
	"\fformatString\x18\x05 \x01(\tR\fformatString\x12$\n" +
	"\targuments\x18\x06 \x03(\v2\x06.FieldR\targuments\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"\xb4\x01\n" +
	"\bEventRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12(\n" +
	"\bseverity\x18\x04 \x01(\x0e2\f.EvrSeverityR\bseverity\x12\x1c\n" +
	"\targuments\x18\x05 \x03(\tR\targuments\x12\x1e\n" +
	"\n" +
	"dictionary\x18\n" +
	" \x01(\tR\n" +
	"dictionary\"\x8d\x01\n" +
	"\fTelemetryDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x19\n" +
	"\x04type\x18\x04 \x01(\v2\x05.TypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadataJ\x04\b\x05\x10\x06\"p\n" +
	"\fTelemetryRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x1e\n" +
	"\n" +
	"dictionary\x18\n" +
	" \x01(\tR\n" +
	"dictionary\"R\n" +
	"\x0eDictionaryHead\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xbb\x05\n" +
	"\x13DictionaryNamespace\x12>\n" +
	"\bcommands\x18\x01 \x03(\v2\".DictionaryNamespace.CommandsEntryR\bcommands\x128\n" +
	"\x06events\x18\x02 \x03(\v2 .DictionaryNamespace.EventsEntryR\x06events\x12A\n" +
	"\ttelemetry\x18\x03 \x03(\v2#.DictionaryNamespace.TelemetryEntryR\ttelemetry\x12D\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2$.DictionaryNamespace.ParametersEntryR\n" +
	"parameters\x125\n" +
	"\x05types\x18\x05 \x03(\v2\x1f.DictionaryNamespace.TypesEntryR\x05types\x1aH\n" +
	"\rCommandsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.CommandDefR\x05value:\x028\x01\x1aD\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.EventDefR\x05value:\x028\x01\x1aK\n" +
	"\x0eTelemetryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.TelemetryDefR\x05value:\x028\x01\x1aL\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.ParameterDefR\x05value:\x028\x01\x1a?\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\v2\x05.TypeR\x05value:\x028\x01\"\xab\x02\n" +
	"\n" +
	"Dictionary\x12#\n" +
	"\x04head\x18\x01 \x01(\v2\x0f.DictionaryHeadR\x04head\x122\n" +
	"\acontent\x18\x02 \x03(\v2\x18.Dictionary.ContentEntryR\acontent\x125\n" +
	"\bmetadata\x18\x03 \x03(\v2\x19.Dictionary.MetadataEntryR\bmetadata\x1aP\n" +
	"\fContentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.DictionaryNamespaceR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x99\x01\n" +
	"\vEvrSeverity\x12\x12\n" +
	"\x0eEVR_DIAGNOSTIC\x10\x00\x12\x14\n" +
	"\x10EVR_ACTIVITY_LOW\x10\x01\x12\x15\n" +
	"\x11EVR_ACTIVITY_HIGH\x10\x02\x12\x13\n" +
	"\x0fEVR_WARNING_LOW\x10\x03\x12\x14\n" +
	"\x10EVR_WARNING_HIGH\x10\x04\x12\x0f\n" +
	"\vEVR_COMMAND\x10\x05\x12\r\n" +
	"\tEVR_FATAL\x10\x06B\x1fZ\x1dgithub.com/nasa/hermes/pkg/pbb\x06proto3"

var (
	file_dictionary_proto_rawDescOnce sync.Once
	file_dictionary_proto_rawDescData []byte
)

func file_dictionary_proto_rawDescGZIP() []byte {
	file_dictionary_proto_rawDescOnce.Do(func() {
		file_dictionary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionary_proto_rawDesc), len(file_dictionary_proto_rawDesc)))
	})
	return file_dictionary_proto_rawDescData
}

var file_dictionary_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dictionary_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_dictionary_proto_goTypes = []any{
	(EvrSeverity)(0),            // 0: EvrSeverity
	(*ParameterDef)(nil),        // 1: ParameterDef
	(*CommandDef)(nil),          // 2: CommandDef
	(*EventDef)(nil),            // 3: EventDef
	(*EventRef)(nil),            // 4: EventRef
	(*TelemetryDef)(nil),        // 5: TelemetryDef
	(*TelemetryRef)(nil),        // 6: TelemetryRef
	(*DictionaryHead)(nil),      // 7: DictionaryHead
	(*DictionaryNamespace)(nil), // 8: DictionaryNamespace
	(*Dictionary)(nil),          // 9: Dictionary
	nil,                         // 10: DictionaryNamespace.CommandsEntry
	nil,                         // 11: DictionaryNamespace.EventsEntry
	nil,                         // 12: DictionaryNamespace.TelemetryEntry
	nil,                         // 13: DictionaryNamespace.ParametersEntry
	nil,                         // 14: DictionaryNamespace.TypesEntry
	nil,                         // 15: Dictionary.ContentEntry
	nil,                         // 16: Dictionary.MetadataEntry
	(*Type)(nil),                // 17: Type
	(*Field)(nil),               // 18: Field
}
var file_dictionary_proto_depIdxs = []int32{
	17, // 0: ParameterDef.type:type_name -> Type
	18, // 1: CommandDef.arguments:type_name -> Field
	0,  // 2: EventDef.severity:type_name -> EvrSeverity
	18, // 3: EventDef.arguments:type_name -> Field
	0,  // 4: EventRef.severity:type_name -> EvrSeverity
	17, // 5: TelemetryDef.type:type_name -> Type
	10, // 6: DictionaryNamespace.commands:type_name -> DictionaryNamespace.CommandsEntry
	11, // 7: DictionaryNamespace.events:type_name -> DictionaryNamespace.EventsEntry
	12, // 8: DictionaryNamespace.telemetry:type_name -> DictionaryNamespace.TelemetryEntry
	13, // 9: DictionaryNamespace.parameters:type_name -> DictionaryNamespace.ParametersEntry
	14, // 10: DictionaryNamespace.types:type_name -> DictionaryNamespace.TypesEntry
	7,  // 11: Dictionary.head:type_name -> DictionaryHead
	15, // 12: Dictionary.content:type_name -> Dictionary.ContentEntry
	16, // 13: Dictionary.metadata:type_name -> Dictionary.MetadataEntry
	2,  // 14: DictionaryNamespace.CommandsEntry.value:type_name -> CommandDef
	3,  // 15: DictionaryNamespace.EventsEntry.value:type_name -> EventDef
	5,  // 16: DictionaryNamespace.TelemetryEntry.value:type_name -> TelemetryDef
	1,  // 17: DictionaryNamespace.ParametersEntry.value:type_name -> ParameterDef
	17, // 18: DictionaryNamespace.TypesEntry.value:type_name -> Type
	8,  // 19: Dictionary.ContentEntry.value:type_name -> DictionaryNamespace
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_dictionary_proto_init() }
func file_dictionary_proto_init() {
	if File_dictionary_proto != nil {
		return
	}
	file_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionary_proto_rawDesc), len(file_dictionary_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionary_proto_goTypes,
		DependencyIndexes: file_dictionary_proto_depIdxs,
		EnumInfos:         file_dictionary_proto_enumTypes,
		MessageInfos:      file_dictionary_proto_msgTypes,
	}.Build()
	File_dictionary_proto = out.File
	file_dictionary_proto_goTypes = nil
	file_dictionary_proto_depIdxs = nil
}
