// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: file.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source path of file (usually trancated for uplink bandwidth reasons)
	SourcePath string `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"`
	// Destination to tell FSW to write file to
	DestinationPath string `protobuf:"bytes,2,opt,name=destination_path,json=destinationPath,proto3" json:"destination_path,omitempty"`
	// File total size
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Additional fields associated with this file uplink
	// This has flight-software specific meaning
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileHeader) Reset() {
	*x = FileHeader{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHeader) ProtoMessage() {}

func (x *FileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHeader.ProtoReflect.Descriptor instead.
func (*FileHeader) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileHeader) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *FileHeader) GetDestinationPath() string {
	if x != nil {
		return x.DestinationPath
	}
	return ""
}

func (x *FileHeader) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileHeader) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UplinkFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*UplinkFileChunk_Header
	//	*UplinkFileChunk_Data
	Value         isUplinkFileChunk_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UplinkFileChunk) Reset() {
	*x = UplinkFileChunk{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UplinkFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UplinkFileChunk) ProtoMessage() {}

func (x *UplinkFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UplinkFileChunk.ProtoReflect.Descriptor instead.
func (*UplinkFileChunk) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *UplinkFileChunk) GetValue() isUplinkFileChunk_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UplinkFileChunk) GetHeader() *FileHeader {
	if x != nil {
		if x, ok := x.Value.(*UplinkFileChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *UplinkFileChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Value.(*UplinkFileChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isUplinkFileChunk_Value interface {
	isUplinkFileChunk_Value()
}

type UplinkFileChunk_Header struct {
	Header *FileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type UplinkFileChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*UplinkFileChunk_Header) isUplinkFileChunk_Value() {}

func (*UplinkFileChunk_Data) isUplinkFileChunk_Value() {}

type DownlinkFileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Md            map[string]string      `protobuf:"bytes,3,rep,name=md,proto3" json:"md,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkFileData) Reset() {
	*x = DownlinkFileData{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkFileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkFileData) ProtoMessage() {}

func (x *DownlinkFileData) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkFileData.ProtoReflect.Descriptor instead.
func (*DownlinkFileData) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *DownlinkFileData) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownlinkFileData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownlinkFileData) GetMd() map[string]string {
	if x != nil {
		return x.Md
	}
	return nil
}

type DownlinkFileMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// JSON data to associate with key
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkFileMetadata) Reset() {
	*x = DownlinkFileMetadata{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkFileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkFileMetadata) ProtoMessage() {}

func (x *DownlinkFileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkFileMetadata.ProtoReflect.Descriptor instead.
func (*DownlinkFileMetadata) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *DownlinkFileMetadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DownlinkFileMetadata) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DownlinkFileValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkFileValidation) Reset() {
	*x = DownlinkFileValidation{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkFileValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkFileValidation) ProtoMessage() {}

func (x *DownlinkFileValidation) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkFileValidation.ProtoReflect.Descriptor instead.
func (*DownlinkFileValidation) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

type DownlinkFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*DownlinkFileChunk_Header
	//	*DownlinkFileChunk_Data
	//	*DownlinkFileChunk_Metadata
	//	*DownlinkFileChunk_Validation
	Value         isDownlinkFileChunk_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkFileChunk) Reset() {
	*x = DownlinkFileChunk{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkFileChunk) ProtoMessage() {}

func (x *DownlinkFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkFileChunk.ProtoReflect.Descriptor instead.
func (*DownlinkFileChunk) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *DownlinkFileChunk) GetValue() isDownlinkFileChunk_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DownlinkFileChunk) GetHeader() *FileHeader {
	if x != nil {
		if x, ok := x.Value.(*DownlinkFileChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *DownlinkFileChunk) GetData() *DownlinkFileData {
	if x != nil {
		if x, ok := x.Value.(*DownlinkFileChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *DownlinkFileChunk) GetMetadata() *DownlinkFileMetadata {
	if x != nil {
		if x, ok := x.Value.(*DownlinkFileChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *DownlinkFileChunk) GetValidation() *DownlinkFileValidation {
	if x != nil {
		if x, ok := x.Value.(*DownlinkFileChunk_Validation); ok {
			return x.Validation
		}
	}
	return nil
}

type isDownlinkFileChunk_Value interface {
	isDownlinkFileChunk_Value()
}

type DownlinkFileChunk_Header struct {
	// The initial message initializing the downlink session.
	// This is the first packet and should be only send once
	Header *FileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type DownlinkFileChunk_Data struct {
	// A chunk of file data given the raw data and that byte
	// offset in the final file
	// Send this after the header and before the validation
	// Should be sent 1 or more times.
	Data *DownlinkFileData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type DownlinkFileChunk_Metadata struct {
	// Mark a metadata event denoting information about the downlink
	// Send this after the header and before the validation
	// Can be sent 0 or more times.
	Metadata *DownlinkFileMetadata `protobuf:"bytes,3,opt,name=metadata,proto3,oneof"`
}

type DownlinkFileChunk_Validation struct {
	// An optional packet to tell the host to validate the final
	// file against an expected hash.
	Validation *DownlinkFileValidation `protobuf:"bytes,4,opt,name=validation,proto3,oneof"`
}

func (*DownlinkFileChunk_Header) isDownlinkFileChunk_Value() {}

func (*DownlinkFileChunk_Data) isDownlinkFileChunk_Value() {}

func (*DownlinkFileChunk_Metadata) isDownlinkFileChunk_Value() {}

func (*DownlinkFileChunk_Validation) isDownlinkFileChunk_Value() {}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\"\xe0\x01\n" +
	"\n" +
	"FileHeader\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12)\n" +
	"\x10destination_path\x18\x02 \x01(\tR\x0fdestinationPath\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x125\n" +
	"\bmetadata\x18\x04 \x03(\v2\x19.FileHeader.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\x0fUplinkFileChunk\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\v.FileHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\a\n" +
	"\x05value\"\xa0\x01\n" +
	"\x10DownlinkFileData\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12)\n" +
	"\x02md\x18\x03 \x03(\v2\x19.DownlinkFileData.MdEntryR\x02md\x1a5\n" +
	"\aMdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x14DownlinkFileMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x18\n" +
	"\x16DownlinkFileValidation\"\xdc\x01\n" +
	"\x11DownlinkFileChunk\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\v.FileHeaderH\x00R\x06header\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x11.DownlinkFileDataH\x00R\x04data\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x15.DownlinkFileMetadataH\x00R\bmetadata\x129\n" +
	"\n" +
	"validation\x18\x04 \x01(\v2\x17.DownlinkFileValidationH\x00R\n" +
	"validationB\a\n" +
	"\x05valueB\x1fZ\x1dgithub.com/nasa/hermes/pkg/pbb\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_file_proto_goTypes = []any{
	(*FileHeader)(nil),             // 0: FileHeader
	(*UplinkFileChunk)(nil),        // 1: UplinkFileChunk
	(*DownlinkFileData)(nil),       // 2: DownlinkFileData
	(*DownlinkFileMetadata)(nil),   // 3: DownlinkFileMetadata
	(*DownlinkFileValidation)(nil), // 4: DownlinkFileValidation
	(*DownlinkFileChunk)(nil),      // 5: DownlinkFileChunk
	nil,                            // 6: FileHeader.MetadataEntry
	nil,                            // 7: DownlinkFileData.MdEntry
}
var file_file_proto_depIdxs = []int32{
	6, // 0: FileHeader.metadata:type_name -> FileHeader.MetadataEntry
	0, // 1: UplinkFileChunk.header:type_name -> FileHeader
	7, // 2: DownlinkFileData.md:type_name -> DownlinkFileData.MdEntry
	0, // 3: DownlinkFileChunk.header:type_name -> FileHeader
	2, // 4: DownlinkFileChunk.data:type_name -> DownlinkFileData
	3, // 5: DownlinkFileChunk.metadata:type_name -> DownlinkFileMetadata
	4, // 6: DownlinkFileChunk.validation:type_name -> DownlinkFileValidation
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	file_file_proto_msgTypes[1].OneofWrappers = []any{
		(*UplinkFileChunk_Header)(nil),
		(*UplinkFileChunk_Data)(nil),
	}
	file_file_proto_msgTypes[5].OneofWrappers = []any{
		(*DownlinkFileChunk_Header)(nil),
		(*DownlinkFileChunk_Data)(nil),
		(*DownlinkFileChunk_Metadata)(nil),
		(*DownlinkFileChunk_Validation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
