// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FswList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           []*Fsw                 `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FswList) Reset() {
	*x = FswList{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FswList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FswList) ProtoMessage() {}

func (x *FswList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FswList.ProtoReflect.Descriptor instead.
func (*FswList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *FswList) GetAll() []*Fsw {
	if x != nil {
		return x.All
	}
	return nil
}

type Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *Reply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SequenceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CommandIndex  int32                  `protobuf:"varint,2,opt,name=command_index,json=commandIndex,proto3" json:"command_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceReply) Reset() {
	*x = SequenceReply{}
	mi := &file_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceReply) ProtoMessage() {}

func (x *SequenceReply) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceReply.ProtoReflect.Descriptor instead.
func (*SequenceReply) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *SequenceReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SequenceReply) GetCommandIndex() int32 {
	if x != nil {
		return x.CommandIndex
	}
	return 0
}

type StatefulProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Profile               `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	State         ProfileState           `protobuf:"varint,2,opt,name=state,proto3,enum=ProfileState" json:"state,omitempty"`
	RuntimeOnly   bool                   `protobuf:"varint,3,opt,name=runtime_only,json=runtimeOnly,proto3" json:"runtime_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatefulProfile) Reset() {
	*x = StatefulProfile{}
	mi := &file_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatefulProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatefulProfile) ProtoMessage() {}

func (x *StatefulProfile) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatefulProfile.ProtoReflect.Descriptor instead.
func (*StatefulProfile) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *StatefulProfile) GetValue() *Profile {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StatefulProfile) GetState() ProfileState {
	if x != nil {
		return x.State
	}
	return ProfileState_PROFILE_IDLE
}

func (x *StatefulProfile) GetRuntimeOnly() bool {
	if x != nil {
		return x.RuntimeOnly
	}
	return false
}

type ProfileList struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	All           map[string]*StatefulProfile `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileList) Reset() {
	*x = ProfileList{}
	mi := &file_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileList) ProtoMessage() {}

func (x *ProfileList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileList.ProtoReflect.Descriptor instead.
func (*ProfileList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileList) GetAll() map[string]*StatefulProfile {
	if x != nil {
		return x.All
	}
	return nil
}

type ProfileProviderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	All           []*ProfileProvider     `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileProviderList) Reset() {
	*x = ProfileProviderList{}
	mi := &file_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileProviderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileProviderList) ProtoMessage() {}

func (x *ProfileProviderList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileProviderList.ProtoReflect.Descriptor instead.
func (*ProfileProviderList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{6}
}

func (x *ProfileProviderList) GetAll() []*ProfileProvider {
	if x != nil {
		return x.All
	}
	return nil
}

type ProfileUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Settings      string                 `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdate) Reset() {
	*x = ProfileUpdate{}
	mi := &file_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdate) ProtoMessage() {}

func (x *ProfileUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdate.ProtoReflect.Descriptor instead.
func (*ProfileUpdate) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{7}
}

func (x *ProfileUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileUpdate) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

type DictionaryList struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	All           map[string]*DictionaryHead `protobuf:"bytes,1,rep,name=all,proto3" json:"all,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictionaryList) Reset() {
	*x = DictionaryList{}
	mi := &file_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictionaryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryList) ProtoMessage() {}

func (x *DictionaryList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryList.ProtoReflect.Descriptor instead.
func (*DictionaryList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{8}
}

func (x *DictionaryList) GetAll() map[string]*DictionaryHead {
	if x != nil {
		return x.All
	}
	return nil
}

type Uplink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uplink session id
	// All packets that are part of a single session should be sent with
	// the same ID. Note that multiple packets are only relevant for file uplink.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Uplink_Cmd
	//	*Uplink_ParseCmd
	//	*Uplink_Seq
	//	*Uplink_ParseSeq
	//	*Uplink_File
	//	*Uplink_Request
	//	*Uplink_Cancel
	//	*Uplink_Final
	Value         isUplink_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uplink) Reset() {
	*x = Uplink{}
	mi := &file_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uplink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uplink) ProtoMessage() {}

func (x *Uplink) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uplink.ProtoReflect.Descriptor instead.
func (*Uplink) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{9}
}

func (x *Uplink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Uplink) GetValue() isUplink_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Uplink) GetCmd() *CommandValue {
	if x != nil {
		if x, ok := x.Value.(*Uplink_Cmd); ok {
			return x.Cmd
		}
	}
	return nil
}

func (x *Uplink) GetParseCmd() *RawCommandValue {
	if x != nil {
		if x, ok := x.Value.(*Uplink_ParseCmd); ok {
			return x.ParseCmd
		}
	}
	return nil
}

func (x *Uplink) GetSeq() *CommandSequence {
	if x != nil {
		if x, ok := x.Value.(*Uplink_Seq); ok {
			return x.Seq
		}
	}
	return nil
}

func (x *Uplink) GetParseSeq() *RawCommandSequence {
	if x != nil {
		if x, ok := x.Value.(*Uplink_ParseSeq); ok {
			return x.ParseSeq
		}
	}
	return nil
}

func (x *Uplink) GetFile() *UplinkFileChunk {
	if x != nil {
		if x, ok := x.Value.(*Uplink_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Uplink) GetRequest() *RequestValue {
	if x != nil {
		if x, ok := x.Value.(*Uplink_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Uplink) GetCancel() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Value.(*Uplink_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *Uplink) GetFinal() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Value.(*Uplink_Final); ok {
			return x.Final
		}
	}
	return nil
}

type isUplink_Value interface {
	isUplink_Value()
}

type Uplink_Cmd struct {
	Cmd *CommandValue `protobuf:"bytes,2,opt,name=cmd,proto3,oneof"`
}

type Uplink_ParseCmd struct {
	ParseCmd *RawCommandValue `protobuf:"bytes,3,opt,name=parse_cmd,json=parseCmd,proto3,oneof"`
}

type Uplink_Seq struct {
	Seq *CommandSequence `protobuf:"bytes,4,opt,name=seq,proto3,oneof"`
}

type Uplink_ParseSeq struct {
	ParseSeq *RawCommandSequence `protobuf:"bytes,5,opt,name=parse_seq,json=parseSeq,proto3,oneof"`
}

type Uplink_File struct {
	File *UplinkFileChunk `protobuf:"bytes,6,opt,name=file,proto3,oneof"`
}

type Uplink_Request struct {
	Request *RequestValue `protobuf:"bytes,7,opt,name=request,proto3,oneof"`
}

type Uplink_Cancel struct {
	// Cancel a previously requested uplink session
	Cancel *emptypb.Empty `protobuf:"bytes,99,opt,name=cancel,proto3,oneof"`
}

type Uplink_Final struct {
	// The final packet marking the end of the uplink session
	// Currently only relevant for file uplink
	Final *emptypb.Empty `protobuf:"bytes,100,opt,name=final,proto3,oneof"`
}

func (*Uplink_Cmd) isUplink_Value() {}

func (*Uplink_ParseCmd) isUplink_Value() {}

func (*Uplink_Seq) isUplink_Value() {}

func (*Uplink_ParseSeq) isUplink_Value() {}

func (*Uplink_File) isUplink_Value() {}

func (*Uplink_Request) isUplink_Value() {}

func (*Uplink_Cancel) isUplink_Value() {}

func (*Uplink_Final) isUplink_Value() {}

type UplinkReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Status:
	//
	//	*UplinkReply_Reply
	//	*UplinkReply_Error
	Status        isUplinkReply_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UplinkReply) Reset() {
	*x = UplinkReply{}
	mi := &file_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UplinkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UplinkReply) ProtoMessage() {}

func (x *UplinkReply) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UplinkReply.ProtoReflect.Descriptor instead.
func (*UplinkReply) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{10}
}

func (x *UplinkReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UplinkReply) GetStatus() isUplinkReply_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UplinkReply) GetReply() []byte {
	if x != nil {
		if x, ok := x.Status.(*UplinkReply_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *UplinkReply) GetError() string {
	if x != nil {
		if x, ok := x.Status.(*UplinkReply_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isUplinkReply_Status interface {
	isUplinkReply_Status()
}

type UplinkReply_Reply struct {
	Reply []byte `protobuf:"bytes,2,opt,name=reply,proto3,oneof"`
}

type UplinkReply_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*UplinkReply_Reply) isUplinkReply_Status() {}

func (*UplinkReply_Error) isUplinkReply_Status() {}

type FswInitialPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Info  *Fsw                   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// Profile name that this FSW should be grouped with
	Profile       string `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FswInitialPacket) Reset() {
	*x = FswInitialPacket{}
	mi := &file_msg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FswInitialPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FswInitialPacket) ProtoMessage() {}

func (x *FswInitialPacket) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FswInitialPacket.ProtoReflect.Descriptor instead.
func (*FswInitialPacket) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{11}
}

func (x *FswInitialPacket) GetInfo() *Fsw {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *FswInitialPacket) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type FswConnectionPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*FswConnectionPacket_Info
	//	*FswConnectionPacket_Reply
	Value         isFswConnectionPacket_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FswConnectionPacket) Reset() {
	*x = FswConnectionPacket{}
	mi := &file_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FswConnectionPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FswConnectionPacket) ProtoMessage() {}

func (x *FswConnectionPacket) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FswConnectionPacket.ProtoReflect.Descriptor instead.
func (*FswConnectionPacket) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{12}
}

func (x *FswConnectionPacket) GetValue() isFswConnectionPacket_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *FswConnectionPacket) GetInfo() *FswInitialPacket {
	if x != nil {
		if x, ok := x.Value.(*FswConnectionPacket_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *FswConnectionPacket) GetReply() *UplinkReply {
	if x != nil {
		if x, ok := x.Value.(*FswConnectionPacket_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

type isFswConnectionPacket_Value interface {
	isFswConnectionPacket_Value()
}

type FswConnectionPacket_Info struct {
	// The initial message to send noting metadata about the FSW connection
	Info *FswInitialPacket `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type FswConnectionPacket_Reply struct {
	// After `info` is sent, all other messages should be replies to Uplink messages
	Reply *UplinkReply `protobuf:"bytes,2,opt,name=reply,proto3,oneof"`
}

func (*FswConnectionPacket_Info) isFswConnectionPacket_Value() {}

func (*FswConnectionPacket_Reply) isFswConnectionPacket_Value() {}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x10dictionary.proto\x1a\tfsw.proto\x1a\rprofile.proto\x1a\n" +
	"file.proto\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\aFswList\x12\x16\n" +
	"\x03all\x18\x01 \x03(\v2\x04.FswR\x03all\"!\n" +
	"\x05Reply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\rSequenceReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rcommand_index\x18\x02 \x01(\x05R\fcommandIndex\"y\n" +
	"\x0fStatefulProfile\x12\x1e\n" +
	"\x05value\x18\x01 \x01(\v2\b.ProfileR\x05value\x12#\n" +
	"\x05state\x18\x02 \x01(\x0e2\r.ProfileStateR\x05state\x12!\n" +
	"\fruntime_only\x18\x03 \x01(\bR\vruntimeOnly\"\x80\x01\n" +
	"\vProfileList\x12'\n" +
	"\x03all\x18\x01 \x03(\v2\x15.ProfileList.AllEntryR\x03all\x1aH\n" +
	"\bAllEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.StatefulProfileR\x05value:\x028\x01\"9\n" +
	"\x13ProfileProviderList\x12\"\n" +
	"\x03all\x18\x01 \x03(\v2\x10.ProfileProviderR\x03all\";\n" +
	"\rProfileUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsettings\x18\x02 \x01(\tR\bsettings\"\x85\x01\n" +
	"\x0eDictionaryList\x12*\n" +
	"\x03all\x18\x01 \x03(\v2\x18.DictionaryList.AllEntryR\x03all\x1aG\n" +
	"\bAllEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.DictionaryHeadR\x05value:\x028\x01\"\x84\x03\n" +
	"\x06Uplink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x03cmd\x18\x02 \x01(\v2\r.CommandValueH\x00R\x03cmd\x12/\n" +
	"\tparse_cmd\x18\x03 \x01(\v2\x10.RawCommandValueH\x00R\bparseCmd\x12$\n" +
	"\x03seq\x18\x04 \x01(\v2\x10.CommandSequenceH\x00R\x03seq\x122\n" +
	"\tparse_seq\x18\x05 \x01(\v2\x13.RawCommandSequenceH\x00R\bparseSeq\x12&\n" +
	"\x04file\x18\x06 \x01(\v2\x10.UplinkFileChunkH\x00R\x04file\x12)\n" +
	"\arequest\x18\a \x01(\v2\r.RequestValueH\x00R\arequest\x120\n" +
	"\x06cancel\x18c \x01(\v2\x16.google.protobuf.EmptyH\x00R\x06cancel\x12.\n" +
	"\x05final\x18d \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05finalB\a\n" +
	"\x05value\"W\n" +
	"\vUplinkReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x05reply\x18\x02 \x01(\fH\x00R\x05reply\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06status\"F\n" +
	"\x10FswInitialPacket\x12\x18\n" +
	"\x04info\x18\x01 \x01(\v2\x04.FswR\x04info\x12\x18\n" +
	"\aprofile\x18\x02 \x01(\tR\aprofile\"m\n" +
	"\x13FswConnectionPacket\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x11.FswInitialPacketH\x00R\x04info\x12$\n" +
	"\x05reply\x18\x02 \x01(\v2\f.UplinkReplyH\x00R\x05replyB\a\n" +
	"\x05valueB\x1fZ\x1dgithub.com/nasa/hermes/pkg/pbb\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_msg_proto_goTypes = []any{
	(*Id)(nil),                  // 0: Id
	(*FswList)(nil),             // 1: FswList
	(*Reply)(nil),               // 2: Reply
	(*SequenceReply)(nil),       // 3: SequenceReply
	(*StatefulProfile)(nil),     // 4: StatefulProfile
	(*ProfileList)(nil),         // 5: ProfileList
	(*ProfileProviderList)(nil), // 6: ProfileProviderList
	(*ProfileUpdate)(nil),       // 7: ProfileUpdate
	(*DictionaryList)(nil),      // 8: DictionaryList
	(*Uplink)(nil),              // 9: Uplink
	(*UplinkReply)(nil),         // 10: UplinkReply
	(*FswInitialPacket)(nil),    // 11: FswInitialPacket
	(*FswConnectionPacket)(nil), // 12: FswConnectionPacket
	nil,                         // 13: ProfileList.AllEntry
	nil,                         // 14: DictionaryList.AllEntry
	(*Fsw)(nil),                 // 15: Fsw
	(*Profile)(nil),             // 16: Profile
	(ProfileState)(0),           // 17: ProfileState
	(*ProfileProvider)(nil),     // 18: ProfileProvider
	(*CommandValue)(nil),        // 19: CommandValue
	(*RawCommandValue)(nil),     // 20: RawCommandValue
	(*CommandSequence)(nil),     // 21: CommandSequence
	(*RawCommandSequence)(nil),  // 22: RawCommandSequence
	(*UplinkFileChunk)(nil),     // 23: UplinkFileChunk
	(*RequestValue)(nil),        // 24: RequestValue
	(*emptypb.Empty)(nil),       // 25: google.protobuf.Empty
	(*DictionaryHead)(nil),      // 26: DictionaryHead
}
var file_msg_proto_depIdxs = []int32{
	15, // 0: FswList.all:type_name -> Fsw
	16, // 1: StatefulProfile.value:type_name -> Profile
	17, // 2: StatefulProfile.state:type_name -> ProfileState
	13, // 3: ProfileList.all:type_name -> ProfileList.AllEntry
	18, // 4: ProfileProviderList.all:type_name -> ProfileProvider
	14, // 5: DictionaryList.all:type_name -> DictionaryList.AllEntry
	19, // 6: Uplink.cmd:type_name -> CommandValue
	20, // 7: Uplink.parse_cmd:type_name -> RawCommandValue
	21, // 8: Uplink.seq:type_name -> CommandSequence
	22, // 9: Uplink.parse_seq:type_name -> RawCommandSequence
	23, // 10: Uplink.file:type_name -> UplinkFileChunk
	24, // 11: Uplink.request:type_name -> RequestValue
	25, // 12: Uplink.cancel:type_name -> google.protobuf.Empty
	25, // 13: Uplink.final:type_name -> google.protobuf.Empty
	15, // 14: FswInitialPacket.info:type_name -> Fsw
	11, // 15: FswConnectionPacket.info:type_name -> FswInitialPacket
	10, // 16: FswConnectionPacket.reply:type_name -> UplinkReply
	4,  // 17: ProfileList.AllEntry.value:type_name -> StatefulProfile
	26, // 18: DictionaryList.AllEntry.value:type_name -> DictionaryHead
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	file_dictionary_proto_init()
	file_fsw_proto_init()
	file_profile_proto_init()
	file_file_proto_init()
	file_msg_proto_msgTypes[9].OneofWrappers = []any{
		(*Uplink_Cmd)(nil),
		(*Uplink_ParseCmd)(nil),
		(*Uplink_Seq)(nil),
		(*Uplink_ParseSeq)(nil),
		(*Uplink_File)(nil),
		(*Uplink_Request)(nil),
		(*Uplink_Cancel)(nil),
		(*Uplink_Final)(nil),
	}
	file_msg_proto_msgTypes[10].OneofWrappers = []any{
		(*UplinkReply_Reply)(nil),
		(*UplinkReply_Error)(nil),
	}
	file_msg_proto_msgTypes[12].OneofWrappers = []any{
		(*FswConnectionPacket_Info)(nil),
		(*FswConnectionPacket_Reply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
