// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntKind int32

const (
	IntKind_INT_U8  IntKind = 0
	IntKind_INT_I8  IntKind = 1
	IntKind_INT_U16 IntKind = 2
	IntKind_INT_I16 IntKind = 3
	IntKind_INT_U32 IntKind = 4
	IntKind_INT_I32 IntKind = 5
	IntKind_INT_U64 IntKind = 6
	IntKind_INT_I64 IntKind = 7
)

// Enum value maps for IntKind.
var (
	IntKind_name = map[int32]string{
		0: "INT_U8",
		1: "INT_I8",
		2: "INT_U16",
		3: "INT_I16",
		4: "INT_U32",
		5: "INT_I32",
		6: "INT_U64",
		7: "INT_I64",
	}
	IntKind_value = map[string]int32{
		"INT_U8":  0,
		"INT_I8":  1,
		"INT_U16": 2,
		"INT_I16": 3,
		"INT_U32": 4,
		"INT_I32": 5,
		"INT_U64": 6,
		"INT_I64": 7,
	}
)

func (x IntKind) Enum() *IntKind {
	p := new(IntKind)
	*p = x
	return p
}

func (x IntKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntKind) Descriptor() protoreflect.EnumDescriptor {
	return file_type_proto_enumTypes[0].Descriptor()
}

func (IntKind) Type() protoreflect.EnumType {
	return &file_type_proto_enumTypes[0]
}

func (x IntKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntKind.Descriptor instead.
func (IntKind) EnumDescriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{0}
}

type NumberKind int32

const (
	NumberKind_NUMBER_U8  NumberKind = 0
	NumberKind_NUMBER_I8  NumberKind = 1
	NumberKind_NUMBER_U16 NumberKind = 2
	NumberKind_NUMBER_I16 NumberKind = 3
	NumberKind_NUMBER_U32 NumberKind = 4
	NumberKind_NUMBER_I32 NumberKind = 5
	NumberKind_NUMBER_U64 NumberKind = 6
	NumberKind_NUMBER_I64 NumberKind = 7
	NumberKind_NUMBER_F32 NumberKind = 8
	NumberKind_NUMBER_F64 NumberKind = 9
)

// Enum value maps for NumberKind.
var (
	NumberKind_name = map[int32]string{
		0: "NUMBER_U8",
		1: "NUMBER_I8",
		2: "NUMBER_U16",
		3: "NUMBER_I16",
		4: "NUMBER_U32",
		5: "NUMBER_I32",
		6: "NUMBER_U64",
		7: "NUMBER_I64",
		8: "NUMBER_F32",
		9: "NUMBER_F64",
	}
	NumberKind_value = map[string]int32{
		"NUMBER_U8":  0,
		"NUMBER_I8":  1,
		"NUMBER_U16": 2,
		"NUMBER_I16": 3,
		"NUMBER_U32": 4,
		"NUMBER_I32": 5,
		"NUMBER_U64": 6,
		"NUMBER_I64": 7,
		"NUMBER_F32": 8,
		"NUMBER_F64": 9,
	}
)

func (x NumberKind) Enum() *NumberKind {
	p := new(NumberKind)
	*p = x
	return p
}

func (x NumberKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumberKind) Descriptor() protoreflect.EnumDescriptor {
	return file_type_proto_enumTypes[1].Descriptor()
}

func (NumberKind) Type() protoreflect.EnumType {
	return &file_type_proto_enumTypes[1]
}

func (x NumberKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumberKind.Descriptor instead.
func (NumberKind) EnumDescriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{1}
}

type UIntKind int32

const (
	UIntKind_UINT_U8  UIntKind = 0
	UIntKind_UINT_U16 UIntKind = 1
	UIntKind_UINT_U32 UIntKind = 2
	UIntKind_UINT_U64 UIntKind = 3
)

// Enum value maps for UIntKind.
var (
	UIntKind_name = map[int32]string{
		0: "UINT_U8",
		1: "UINT_U16",
		2: "UINT_U32",
		3: "UINT_U64",
	}
	UIntKind_value = map[string]int32{
		"UINT_U8":  0,
		"UINT_U16": 1,
		"UINT_U32": 2,
		"UINT_U64": 3,
	}
)

func (x UIntKind) Enum() *UIntKind {
	p := new(UIntKind)
	*p = x
	return p
}

func (x UIntKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UIntKind) Descriptor() protoreflect.EnumDescriptor {
	return file_type_proto_enumTypes[2].Descriptor()
}

func (UIntKind) Type() protoreflect.EnumType {
	return &file_type_proto_enumTypes[2]
}

func (x UIntKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UIntKind.Descriptor instead.
func (UIntKind) EnumDescriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{2}
}

type SIntKind int32

const (
	SIntKind_SINT_I8  SIntKind = 0
	SIntKind_SINT_I16 SIntKind = 1
	SIntKind_SINT_I32 SIntKind = 2
	SIntKind_SINT_I64 SIntKind = 3
)

// Enum value maps for SIntKind.
var (
	SIntKind_name = map[int32]string{
		0: "SINT_I8",
		1: "SINT_I16",
		2: "SINT_I32",
		3: "SINT_I64",
	}
	SIntKind_value = map[string]int32{
		"SINT_I8":  0,
		"SINT_I16": 1,
		"SINT_I32": 2,
		"SINT_I64": 3,
	}
)

func (x SIntKind) Enum() *SIntKind {
	p := new(SIntKind)
	*p = x
	return p
}

func (x SIntKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SIntKind) Descriptor() protoreflect.EnumDescriptor {
	return file_type_proto_enumTypes[3].Descriptor()
}

func (SIntKind) Type() protoreflect.EnumType {
	return &file_type_proto_enumTypes[3]
}

func (x SIntKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SIntKind.Descriptor instead.
func (SIntKind) EnumDescriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{3}
}

type FloatKind int32

const (
	FloatKind_F_F32 FloatKind = 0
	FloatKind_F_F64 FloatKind = 1
)

// Enum value maps for FloatKind.
var (
	FloatKind_name = map[int32]string{
		0: "F_F32",
		1: "F_F64",
	}
	FloatKind_value = map[string]int32{
		"F_F32": 0,
		"F_F64": 1,
	}
)

func (x FloatKind) Enum() *FloatKind {
	p := new(FloatKind)
	*p = x
	return p
}

func (x FloatKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FloatKind) Descriptor() protoreflect.EnumDescriptor {
	return file_type_proto_enumTypes[4].Descriptor()
}

func (FloatKind) Type() protoreflect.EnumType {
	return &file_type_proto_enumTypes[4]
}

func (x FloatKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FloatKind.Descriptor instead.
func (FloatKind) EnumDescriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{4}
}

type ReferenceKind int32

const (
	ReferenceKind_REF_ENUM    ReferenceKind = 0
	ReferenceKind_REF_BITMASK ReferenceKind = 1
	ReferenceKind_REF_OBJECT  ReferenceKind = 2
	ReferenceKind_REF_ARRAY   ReferenceKind = 3
	ReferenceKind_REF_BYTES   ReferenceKind = 4
)

// Enum value maps for ReferenceKind.
var (
	ReferenceKind_name = map[int32]string{
		0: "REF_ENUM",
		1: "REF_BITMASK",
		2: "REF_OBJECT",
		3: "REF_ARRAY",
		4: "REF_BYTES",
	}
	ReferenceKind_value = map[string]int32{
		"REF_ENUM":    0,
		"REF_BITMASK": 1,
		"REF_OBJECT":  2,
		"REF_ARRAY":   3,
		"REF_BYTES":   4,
	}
)

func (x ReferenceKind) Enum() *ReferenceKind {
	p := new(ReferenceKind)
	*p = x
	return p
}

func (x ReferenceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferenceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_type_proto_enumTypes[5].Descriptor()
}

func (ReferenceKind) Type() protoreflect.EnumType {
	return &file_type_proto_enumTypes[5]
}

func (x ReferenceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferenceKind.Descriptor instead.
func (ReferenceKind) EnumDescriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{5}
}

type BooleanType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncodeType    UIntKind               `protobuf:"varint,1,opt,name=encode_type,json=encodeType,proto3,enum=hermes.UIntKind" json:"encode_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanType) Reset() {
	*x = BooleanType{}
	mi := &file_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanType) ProtoMessage() {}

func (x *BooleanType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanType.ProtoReflect.Descriptor instead.
func (*BooleanType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{0}
}

func (x *BooleanType) GetEncodeType() UIntKind {
	if x != nil {
		return x.EncodeType
	}
	return UIntKind_UINT_U8
}

type IntType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  IntKind                `protobuf:"varint,1,opt,name=kind,proto3,enum=hermes.IntKind" json:"kind,omitempty"`
	// *
	// Lower bound on valid values
	Min int64 `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	// *
	// Upper bound on valid values
	Max           int64 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntType) Reset() {
	*x = IntType{}
	mi := &file_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntType) ProtoMessage() {}

func (x *IntType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntType.ProtoReflect.Descriptor instead.
func (*IntType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{1}
}

func (x *IntType) GetKind() IntKind {
	if x != nil {
		return x.Kind
	}
	return IntKind_INT_U8
}

func (x *IntType) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *IntType) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type FloatType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  FloatKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=hermes.FloatKind" json:"kind,omitempty"`
	// *
	// Lower bound on valid values
	Min float64 `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	// *
	// Upper bound on valid values
	Max           float64 `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FloatType) Reset() {
	*x = FloatType{}
	mi := &file_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FloatType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatType) ProtoMessage() {}

func (x *FloatType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatType.ProtoReflect.Descriptor instead.
func (*FloatType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{2}
}

func (x *FloatType) GetKind() FloatKind {
	if x != nil {
		return x.Kind
	}
	return FloatKind_F_F32
}

func (x *FloatType) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *FloatType) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type StringType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Type to serialize length of string with.
	//
	// When encoding strings, they will be prefixed by their
	// length using this type. If the length does not fit within
	// this type's representable size, it will throw an error.
	LengthType UIntKind `protobuf:"varint,1,opt,name=length_type,json=lengthType,proto3,enum=hermes.UIntKind" json:"length_type,omitempty"`
	// *
	// Optional check for maximum length
	MaxLength     uint32 `protobuf:"varint,2,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringType) Reset() {
	*x = StringType{}
	mi := &file_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringType) ProtoMessage() {}

func (x *StringType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringType.ProtoReflect.Descriptor instead.
func (*StringType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{3}
}

func (x *StringType) GetLengthType() UIntKind {
	if x != nil {
		return x.LengthType
	}
	return UIntKind_UINT_U8
}

func (x *StringType) GetMaxLength() uint32 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

type EnumItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumItem) Reset() {
	*x = EnumItem{}
	mi := &file_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumItem) ProtoMessage() {}

func (x *EnumItem) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumItem.ProtoReflect.Descriptor instead.
func (*EnumItem) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{4}
}

func (x *EnumItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *EnumItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumItem) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type EnumType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Name of the enum
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// Type to serialize enum with.
	// Use this on a per-enum basis. By default it will be I32. If this is
	// specified in the reference type it will override this.
	//
	// You can also override this behavior programmatically by overriding
	// `Serializable.writeEnum`.
	EncodeType IntKind `protobuf:"varint,2,opt,name=encode_type,json=encodeType,proto3,enum=hermes.IntKind" json:"encode_type,omitempty"`
	// *
	// Members of the enum and their mapping to its
	// numeric value.
	Items         []*EnumItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumType) Reset() {
	*x = EnumType{}
	mi := &file_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumType) ProtoMessage() {}

func (x *EnumType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumType.ProtoReflect.Descriptor instead.
func (*EnumType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{5}
}

func (x *EnumType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumType) GetEncodeType() IntKind {
	if x != nil {
		return x.EncodeType
	}
	return IntKind_INT_U8
}

func (x *EnumType) GetItems() []*EnumItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BoundedArraySize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           uint32                 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           uint32                 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundedArraySize) Reset() {
	*x = BoundedArraySize{}
	mi := &file_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundedArraySize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundedArraySize) ProtoMessage() {}

func (x *BoundedArraySize) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundedArraySize.ProtoReflect.Descriptor instead.
func (*BoundedArraySize) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{6}
}

func (x *BoundedArraySize) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *BoundedArraySize) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ArrayType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Name of the array if this is a typedef instead of
	// an inline array.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// Element type
	ElType *Type `protobuf:"bytes,2,opt,name=el_type,json=elType,proto3" json:"el_type,omitempty"`
	// *
	// Either `number` for static array, or a 2-tuple for
	// a range of sizes (or undefined for unbounded).
	//
	// Static arrays do not prefix their encodings with sizes
	// since encoders and decoders both agree on their length
	// ahead of time.
	//
	// # Dynamically sized arrays will prefix their size with
	//
	// Types that are valid to be assigned to Size:
	//
	//	*ArrayType_Static
	//	*ArrayType_Dynamic
	Size isArrayType_Size `protobuf_oneof:"size"`
	// *
	// Serialization type to use for dynamic array's prefixed length.
	// > Ignored on statically sized arrays.
	//
	// Default: {@link TypeKind.u32}
	LengthType    UIntKind `protobuf:"varint,5,opt,name=length_type,json=lengthType,proto3,enum=hermes.UIntKind" json:"length_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayType) Reset() {
	*x = ArrayType{}
	mi := &file_type_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayType) ProtoMessage() {}

func (x *ArrayType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayType.ProtoReflect.Descriptor instead.
func (*ArrayType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{7}
}

func (x *ArrayType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArrayType) GetElType() *Type {
	if x != nil {
		return x.ElType
	}
	return nil
}

func (x *ArrayType) GetSize() isArrayType_Size {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *ArrayType) GetStatic() uint32 {
	if x != nil {
		if x, ok := x.Size.(*ArrayType_Static); ok {
			return x.Static
		}
	}
	return 0
}

func (x *ArrayType) GetDynamic() *BoundedArraySize {
	if x != nil {
		if x, ok := x.Size.(*ArrayType_Dynamic); ok {
			return x.Dynamic
		}
	}
	return nil
}

func (x *ArrayType) GetLengthType() UIntKind {
	if x != nil {
		return x.LengthType
	}
	return UIntKind_UINT_U8
}

type isArrayType_Size interface {
	isArrayType_Size()
}

type ArrayType_Static struct {
	Static uint32 `protobuf:"varint,3,opt,name=static,proto3,oneof"`
}

type ArrayType_Dynamic struct {
	Dynamic *BoundedArraySize `protobuf:"bytes,4,opt,name=dynamic,proto3,oneof"`
}

func (*ArrayType_Static) isArrayType_Size() {}

func (*ArrayType_Dynamic) isArrayType_Size() {}

// *
// Homogeneous array of numeric primitives, stored as raw bytes
// In Python this decodes the array using NumPy
// In JS/TS this decodes the array using DataView or TypedArray
type BytesType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Name of the bytes array if this is a typedef instead of
	// an inline array.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Primtive type of each element in this array
	Kind NumberKind `protobuf:"varint,2,opt,name=kind,proto3,enum=hermes.NumberKind" json:"kind,omitempty"`
	// *
	// Serialization type to use for dynamic array's prefixed length.
	// > Ignored on statically sized arrays.
	//
	// Default: {@link TypeKind.u32}
	//
	// Types that are valid to be assigned to Size:
	//
	//	*BytesType_Static
	//	*BytesType_Dynamic
	Size isBytesType_Size `protobuf_oneof:"size"`
	// *
	// Serialization type to use for dynamic array's prefixed length.
	// > Ignored on statically sized arrays.
	//
	// Default: {@link TypeKind.u32}
	LengthType    UIntKind `protobuf:"varint,5,opt,name=length_type,json=lengthType,proto3,enum=hermes.UIntKind" json:"length_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesType) Reset() {
	*x = BytesType{}
	mi := &file_type_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesType) ProtoMessage() {}

func (x *BytesType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesType.ProtoReflect.Descriptor instead.
func (*BytesType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{8}
}

func (x *BytesType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BytesType) GetKind() NumberKind {
	if x != nil {
		return x.Kind
	}
	return NumberKind_NUMBER_U8
}

func (x *BytesType) GetSize() isBytesType_Size {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *BytesType) GetStatic() uint32 {
	if x != nil {
		if x, ok := x.Size.(*BytesType_Static); ok {
			return x.Static
		}
	}
	return 0
}

func (x *BytesType) GetDynamic() *BoundedArraySize {
	if x != nil {
		if x, ok := x.Size.(*BytesType_Dynamic); ok {
			return x.Dynamic
		}
	}
	return nil
}

func (x *BytesType) GetLengthType() UIntKind {
	if x != nil {
		return x.LengthType
	}
	return UIntKind_UINT_U8
}

type isBytesType_Size interface {
	isBytesType_Size()
}

type BytesType_Static struct {
	Static uint32 `protobuf:"varint,3,opt,name=static,proto3,oneof"`
}

type BytesType_Dynamic struct {
	Dynamic *BoundedArraySize `protobuf:"bytes,4,opt,name=dynamic,proto3,oneof"`
}

func (*BytesType_Static) isBytesType_Size() {}

func (*BytesType_Dynamic) isBytesType_Size() {}

type Field struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type     *Type                  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Metadata string                 `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Optional field for specifying constant value associated with
	// this field. This is when generating field/struct types via a program
	// live and some fields come prefilled.
	Value         *Value `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_type_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{9}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Field) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Field) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type ObjectType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Name of the object/struct
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// *
	// Fields/members inside object. Ordered in order of serialization.
	Fields        []*Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectType) Reset() {
	*x = ObjectType{}
	mi := &file_type_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectType) ProtoMessage() {}

func (x *ObjectType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectType.ProtoReflect.Descriptor instead.
func (*ObjectType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{10}
}

func (x *ObjectType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectType) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ReferenceType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Name of the type
	Name          string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          ReferenceKind `protobuf:"varint,2,opt,name=kind,proto3,enum=hermes.ReferenceKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceType) Reset() {
	*x = ReferenceType{}
	mi := &file_type_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceType) ProtoMessage() {}

func (x *ReferenceType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceType.ProtoReflect.Descriptor instead.
func (*ReferenceType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{11}
}

func (x *ReferenceType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReferenceType) GetKind() ReferenceKind {
	if x != nil {
		return x.Kind
	}
	return ReferenceKind_REF_ENUM
}

type VoidType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Size in bytes of this struct pad
	Size          uint32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoidType) Reset() {
	*x = VoidType{}
	mi := &file_type_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoidType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidType) ProtoMessage() {}

func (x *VoidType) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidType.ProtoReflect.Descriptor instead.
func (*VoidType) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{12}
}

func (x *VoidType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Type struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Type_Ref
	//	*Type_Bool
	//	*Type_Int
	//	*Type_Float
	//	*Type_String_
	//	*Type_Enum
	//	*Type_Bitmask
	//	*Type_Object
	//	*Type_Array
	//	*Type_Bytes
	//	*Type_Void
	Value         isType_Value `protobuf_oneof:"value"`
	Metadata      string       `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_type_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{13}
}

func (x *Type) GetValue() isType_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Type) GetRef() *ReferenceType {
	if x != nil {
		if x, ok := x.Value.(*Type_Ref); ok {
			return x.Ref
		}
	}
	return nil
}

func (x *Type) GetBool() *BooleanType {
	if x != nil {
		if x, ok := x.Value.(*Type_Bool); ok {
			return x.Bool
		}
	}
	return nil
}

func (x *Type) GetInt() *IntType {
	if x != nil {
		if x, ok := x.Value.(*Type_Int); ok {
			return x.Int
		}
	}
	return nil
}

func (x *Type) GetFloat() *FloatType {
	if x != nil {
		if x, ok := x.Value.(*Type_Float); ok {
			return x.Float
		}
	}
	return nil
}

func (x *Type) GetString_() *StringType {
	if x != nil {
		if x, ok := x.Value.(*Type_String_); ok {
			return x.String_
		}
	}
	return nil
}

func (x *Type) GetEnum() *EnumType {
	if x != nil {
		if x, ok := x.Value.(*Type_Enum); ok {
			return x.Enum
		}
	}
	return nil
}

func (x *Type) GetBitmask() *EnumType {
	if x != nil {
		if x, ok := x.Value.(*Type_Bitmask); ok {
			return x.Bitmask
		}
	}
	return nil
}

func (x *Type) GetObject() *ObjectType {
	if x != nil {
		if x, ok := x.Value.(*Type_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *Type) GetArray() *ArrayType {
	if x != nil {
		if x, ok := x.Value.(*Type_Array); ok {
			return x.Array
		}
	}
	return nil
}

func (x *Type) GetBytes() *BytesType {
	if x != nil {
		if x, ok := x.Value.(*Type_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *Type) GetVoid() *VoidType {
	if x != nil {
		if x, ok := x.Value.(*Type_Void); ok {
			return x.Void
		}
	}
	return nil
}

func (x *Type) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type isType_Value interface {
	isType_Value()
}

type Type_Ref struct {
	// This type is special and will be preprocessed upon loading
	Ref *ReferenceType `protobuf:"bytes,1,opt,name=ref,proto3,oneof"`
}

type Type_Bool struct {
	Bool *BooleanType `protobuf:"bytes,2,opt,name=bool,proto3,oneof"`
}

type Type_Int struct {
	Int *IntType `protobuf:"bytes,3,opt,name=int,proto3,oneof"`
}

type Type_Float struct {
	Float *FloatType `protobuf:"bytes,4,opt,name=float,proto3,oneof"`
}

type Type_String_ struct {
	String_ *StringType `protobuf:"bytes,5,opt,name=string,proto3,oneof"`
}

type Type_Enum struct {
	Enum *EnumType `protobuf:"bytes,6,opt,name=enum,proto3,oneof"`
}

type Type_Bitmask struct {
	Bitmask *EnumType `protobuf:"bytes,7,opt,name=bitmask,proto3,oneof"`
}

type Type_Object struct {
	Object *ObjectType `protobuf:"bytes,8,opt,name=object,proto3,oneof"`
}

type Type_Array struct {
	Array *ArrayType `protobuf:"bytes,9,opt,name=array,proto3,oneof"`
}

type Type_Bytes struct {
	Bytes *BytesType `protobuf:"bytes,10,opt,name=bytes,proto3,oneof"`
}

type Type_Void struct {
	Void *VoidType `protobuf:"bytes,11,opt,name=void,proto3,oneof"`
}

func (*Type_Ref) isType_Value() {}

func (*Type_Bool) isType_Value() {}

func (*Type_Int) isType_Value() {}

func (*Type_Float) isType_Value() {}

func (*Type_String_) isType_Value() {}

func (*Type_Enum) isType_Value() {}

func (*Type_Bitmask) isType_Value() {}

func (*Type_Object) isType_Value() {}

func (*Type_Array) isType_Value() {}

func (*Type_Bytes) isType_Value() {}

func (*Type_Void) isType_Value() {}

type ObjectValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	O             map[string]*Value      `protobuf:"bytes,1,rep,name=o,proto3" json:"o,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectValue) Reset() {
	*x = ObjectValue{}
	mi := &file_type_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectValue) ProtoMessage() {}

func (x *ObjectValue) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectValue.ProtoReflect.Descriptor instead.
func (*ObjectValue) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{14}
}

func (x *ObjectValue) GetO() map[string]*Value {
	if x != nil {
		return x.O
	}
	return nil
}

type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []*Value               `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_type_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{15}
}

func (x *ArrayValue) GetValue() []*Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type BytesValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of primitive elements
	Kind NumberKind `protobuf:"varint,1,opt,name=kind,proto3,enum=hermes.NumberKind" json:"kind,omitempty"`
	// Byte order, default = false
	BigEndian bool `protobuf:"varint,2,opt,name=big_endian,json=bigEndian,proto3" json:"big_endian,omitempty"`
	// Raw value in given byte order
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BytesValue) Reset() {
	*x = BytesValue{}
	mi := &file_type_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BytesValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesValue) ProtoMessage() {}

func (x *BytesValue) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesValue.ProtoReflect.Descriptor instead.
func (*BytesValue) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{16}
}

func (x *BytesValue) GetKind() NumberKind {
	if x != nil {
		return x.Kind
	}
	return NumberKind_NUMBER_U8
}

func (x *BytesValue) GetBigEndian() bool {
	if x != nil {
		return x.BigEndian
	}
	return false
}

func (x *BytesValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type EnumValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           int64                  `protobuf:"varint,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Formatted     string                 `protobuf:"bytes,2,opt,name=formatted,proto3" json:"formatted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	mi := &file_type_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{17}
}

func (x *EnumValue) GetRaw() int64 {
	if x != nil {
		return x.Raw
	}
	return 0
}

func (x *EnumValue) GetFormatted() string {
	if x != nil {
		return x.Formatted
	}
	return ""
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_I
	//	*Value_U
	//	*Value_F
	//	*Value_B
	//	*Value_S
	//	*Value_E
	//	*Value_O
	//	*Value_A
	//	*Value_R
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_type_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{18}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetI() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_I); ok {
			return x.I
		}
	}
	return 0
}

func (x *Value) GetU() uint64 {
	if x != nil {
		if x, ok := x.Value.(*Value_U); ok {
			return x.U
		}
	}
	return 0
}

func (x *Value) GetF() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_F); ok {
			return x.F
		}
	}
	return 0
}

func (x *Value) GetB() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_B); ok {
			return x.B
		}
	}
	return false
}

func (x *Value) GetS() string {
	if x != nil {
		if x, ok := x.Value.(*Value_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *Value) GetE() *EnumValue {
	if x != nil {
		if x, ok := x.Value.(*Value_E); ok {
			return x.E
		}
	}
	return nil
}

func (x *Value) GetO() *ObjectValue {
	if x != nil {
		if x, ok := x.Value.(*Value_O); ok {
			return x.O
		}
	}
	return nil
}

func (x *Value) GetA() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*Value_A); ok {
			return x.A
		}
	}
	return nil
}

func (x *Value) GetR() *BytesValue {
	if x != nil {
		if x, ok := x.Value.(*Value_R); ok {
			return x.R
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_I struct {
	// i8, i16, i32, i64
	I int64 `protobuf:"zigzag64,1,opt,name=i,proto3,oneof"`
}

type Value_U struct {
	// u8, u16, u32, u64
	U uint64 `protobuf:"varint,2,opt,name=u,proto3,oneof"`
}

type Value_F struct {
	// f32, f64
	F float64 `protobuf:"fixed64,3,opt,name=f,proto3,oneof"`
}

type Value_B struct {
	// bool
	B bool `protobuf:"varint,4,opt,name=b,proto3,oneof"`
}

type Value_S struct {
	// string
	S string `protobuf:"bytes,5,opt,name=s,proto3,oneof"`
}

type Value_E struct {
	// enum, bitmask
	E *EnumValue `protobuf:"bytes,6,opt,name=e,proto3,oneof"`
}

type Value_O struct {
	// object
	O *ObjectValue `protobuf:"bytes,7,opt,name=o,proto3,oneof"`
}

type Value_A struct {
	// array
	A *ArrayValue `protobuf:"bytes,8,opt,name=a,proto3,oneof"`
}

type Value_R struct {
	// bytes
	R *BytesValue `protobuf:"bytes,9,opt,name=r,proto3,oneof"`
}

func (*Value_I) isValue_Value() {}

func (*Value_U) isValue_Value() {}

func (*Value_F) isValue_Value() {}

func (*Value_B) isValue_Value() {}

func (*Value_S) isValue_Value() {}

func (*Value_E) isValue_Value() {}

func (*Value_O) isValue_Value() {}

func (*Value_A) isValue_Value() {}

func (*Value_R) isValue_Value() {}

var File_type_proto protoreflect.FileDescriptor

const file_type_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"type.proto\x12\x06hermes\"@\n" +
	"\vBooleanType\x121\n" +
	"\vencode_type\x18\x01 \x01(\x0e2\x10.hermes.UIntKindR\n" +
	"encodeType\"R\n" +
	"\aIntType\x12#\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x0f.hermes.IntKindR\x04kind\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x03R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x03R\x03max\"V\n" +
	"\tFloatType\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.hermes.FloatKindR\x04kind\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x01R\x03max\"^\n" +
	"\n" +
	"StringType\x121\n" +
	"\vlength_type\x18\x01 \x01(\x0e2\x10.hermes.UIntKindR\n" +
	"lengthType\x12\x1d\n" +
	"\n" +
	"max_length\x18\x02 \x01(\rR\tmaxLength\"P\n" +
	"\bEnumItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"x\n" +
	"\bEnumType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\vencode_type\x18\x02 \x01(\x0e2\x0f.hermes.IntKindR\n" +
	"encodeType\x12&\n" +
	"\x05items\x18\x03 \x03(\v2\x10.hermes.EnumItemR\x05items\"6\n" +
	"\x10BoundedArraySize\x12\x10\n" +
	"\x03min\x18\x01 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\rR\x03max\"\xd1\x01\n" +
	"\tArrayType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\ael_type\x18\x02 \x01(\v2\f.hermes.TypeR\x06elType\x12\x18\n" +
	"\x06static\x18\x03 \x01(\rH\x00R\x06static\x124\n" +
	"\adynamic\x18\x04 \x01(\v2\x18.hermes.BoundedArraySizeH\x00R\adynamic\x121\n" +
	"\vlength_type\x18\x05 \x01(\x0e2\x10.hermes.UIntKindR\n" +
	"lengthTypeB\x06\n" +
	"\x04size\"\xd2\x01\n" +
	"\tBytesType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x12.hermes.NumberKindR\x04kind\x12\x18\n" +
	"\x06static\x18\x03 \x01(\rH\x00R\x06static\x124\n" +
	"\adynamic\x18\x04 \x01(\v2\x18.hermes.BoundedArraySizeH\x00R\adynamic\x121\n" +
	"\vlength_type\x18\x05 \x01(\x0e2\x10.hermes.UIntKindR\n" +
	"lengthTypeB\x06\n" +
	"\x04size\"~\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\x04type\x18\x02 \x01(\v2\f.hermes.TypeR\x04type\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12#\n" +
	"\x05value\x18\x04 \x01(\v2\r.hermes.ValueR\x05value\"G\n" +
	"\n" +
	"ObjectType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x06fields\x18\x02 \x03(\v2\r.hermes.FieldR\x06fields\"N\n" +
	"\rReferenceType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.hermes.ReferenceKindR\x04kind\"\x1e\n" +
	"\bVoidType\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\"\x81\x04\n" +
	"\x04Type\x12)\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.hermes.ReferenceTypeH\x00R\x03ref\x12)\n" +
	"\x04bool\x18\x02 \x01(\v2\x13.hermes.BooleanTypeH\x00R\x04bool\x12#\n" +
	"\x03int\x18\x03 \x01(\v2\x0f.hermes.IntTypeH\x00R\x03int\x12)\n" +
	"\x05float\x18\x04 \x01(\v2\x11.hermes.FloatTypeH\x00R\x05float\x12,\n" +
	"\x06string\x18\x05 \x01(\v2\x12.hermes.StringTypeH\x00R\x06string\x12&\n" +
	"\x04enum\x18\x06 \x01(\v2\x10.hermes.EnumTypeH\x00R\x04enum\x12,\n" +
	"\abitmask\x18\a \x01(\v2\x10.hermes.EnumTypeH\x00R\abitmask\x12,\n" +
	"\x06object\x18\b \x01(\v2\x12.hermes.ObjectTypeH\x00R\x06object\x12)\n" +
	"\x05array\x18\t \x01(\v2\x11.hermes.ArrayTypeH\x00R\x05array\x12)\n" +
	"\x05bytes\x18\n" +
	" \x01(\v2\x11.hermes.BytesTypeH\x00R\x05bytes\x12&\n" +
	"\x04void\x18\v \x01(\v2\x10.hermes.VoidTypeH\x00R\x04void\x12\x1a\n" +
	"\bmetadata\x18\f \x01(\tR\bmetadataB\a\n" +
	"\x05value\"|\n" +
	"\vObjectValue\x12(\n" +
	"\x01o\x18\x01 \x03(\v2\x1a.hermes.ObjectValue.OEntryR\x01o\x1aC\n" +
	"\x06OEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.hermes.ValueR\x05value:\x028\x01\"1\n" +
	"\n" +
	"ArrayValue\x12#\n" +
	"\x05value\x18\x01 \x03(\v2\r.hermes.ValueR\x05value\"i\n" +
	"\n" +
	"BytesValue\x12&\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x12.hermes.NumberKindR\x04kind\x12\x1d\n" +
	"\n" +
	"big_endian\x18\x02 \x01(\bR\tbigEndian\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\";\n" +
	"\tEnumValue\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\x03R\x03raw\x12\x1c\n" +
	"\tformatted\x18\x02 \x01(\tR\tformatted\"\xf0\x01\n" +
	"\x05Value\x12\x0e\n" +
	"\x01i\x18\x01 \x01(\x12H\x00R\x01i\x12\x0e\n" +
	"\x01u\x18\x02 \x01(\x04H\x00R\x01u\x12\x0e\n" +
	"\x01f\x18\x03 \x01(\x01H\x00R\x01f\x12\x0e\n" +
	"\x01b\x18\x04 \x01(\bH\x00R\x01b\x12\x0e\n" +
	"\x01s\x18\x05 \x01(\tH\x00R\x01s\x12!\n" +
	"\x01e\x18\x06 \x01(\v2\x11.hermes.EnumValueH\x00R\x01e\x12#\n" +
	"\x01o\x18\a \x01(\v2\x13.hermes.ObjectValueH\x00R\x01o\x12\"\n" +
	"\x01a\x18\b \x01(\v2\x12.hermes.ArrayValueH\x00R\x01a\x12\"\n" +
	"\x01r\x18\t \x01(\v2\x12.hermes.BytesValueH\x00R\x01rB\a\n" +
	"\x05value*o\n" +
	"\aIntKind\x12\n" +
	"\n" +
	"\x06INT_U8\x10\x00\x12\n" +
	"\n" +
	"\x06INT_I8\x10\x01\x12\v\n" +
	"\aINT_U16\x10\x02\x12\v\n" +
	"\aINT_I16\x10\x03\x12\v\n" +
	"\aINT_U32\x10\x04\x12\v\n" +
	"\aINT_I32\x10\x05\x12\v\n" +
	"\aINT_U64\x10\x06\x12\v\n" +
	"\aINT_I64\x10\a*\xaa\x01\n" +
	"\n" +
	"NumberKind\x12\r\n" +
	"\tNUMBER_U8\x10\x00\x12\r\n" +
	"\tNUMBER_I8\x10\x01\x12\x0e\n" +
	"\n" +
	"NUMBER_U16\x10\x02\x12\x0e\n" +
	"\n" +
	"NUMBER_I16\x10\x03\x12\x0e\n" +
	"\n" +
	"NUMBER_U32\x10\x04\x12\x0e\n" +
	"\n" +
	"NUMBER_I32\x10\x05\x12\x0e\n" +
	"\n" +
	"NUMBER_U64\x10\x06\x12\x0e\n" +
	"\n" +
	"NUMBER_I64\x10\a\x12\x0e\n" +
	"\n" +
	"NUMBER_F32\x10\b\x12\x0e\n" +
	"\n" +
	"NUMBER_F64\x10\t*A\n" +
	"\bUIntKind\x12\v\n" +
	"\aUINT_U8\x10\x00\x12\f\n" +
	"\bUINT_U16\x10\x01\x12\f\n" +
	"\bUINT_U32\x10\x02\x12\f\n" +
	"\bUINT_U64\x10\x03*A\n" +
	"\bSIntKind\x12\v\n" +
	"\aSINT_I8\x10\x00\x12\f\n" +
	"\bSINT_I16\x10\x01\x12\f\n" +
	"\bSINT_I32\x10\x02\x12\f\n" +
	"\bSINT_I64\x10\x03*!\n" +
	"\tFloatKind\x12\t\n" +
	"\x05F_F32\x10\x00\x12\t\n" +
	"\x05F_F64\x10\x01*\\\n" +
	"\rReferenceKind\x12\f\n" +
	"\bREF_ENUM\x10\x00\x12\x0f\n" +
	"\vREF_BITMASK\x10\x01\x12\x0e\n" +
	"\n" +
	"REF_OBJECT\x10\x02\x12\r\n" +
	"\tREF_ARRAY\x10\x03\x12\r\n" +
	"\tREF_BYTES\x10\x04B\x1fZ\x1dgithub.com/nasa/hermes/pkg/pbb\x06proto3"

var (
	file_type_proto_rawDescOnce sync.Once
	file_type_proto_rawDescData []byte
)

func file_type_proto_rawDescGZIP() []byte {
	file_type_proto_rawDescOnce.Do(func() {
		file_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)))
	})
	return file_type_proto_rawDescData
}

var file_type_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_type_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_type_proto_goTypes = []any{
	(IntKind)(0),             // 0: hermes.IntKind
	(NumberKind)(0),          // 1: hermes.NumberKind
	(UIntKind)(0),            // 2: hermes.UIntKind
	(SIntKind)(0),            // 3: hermes.SIntKind
	(FloatKind)(0),           // 4: hermes.FloatKind
	(ReferenceKind)(0),       // 5: hermes.ReferenceKind
	(*BooleanType)(nil),      // 6: hermes.BooleanType
	(*IntType)(nil),          // 7: hermes.IntType
	(*FloatType)(nil),        // 8: hermes.FloatType
	(*StringType)(nil),       // 9: hermes.StringType
	(*EnumItem)(nil),         // 10: hermes.EnumItem
	(*EnumType)(nil),         // 11: hermes.EnumType
	(*BoundedArraySize)(nil), // 12: hermes.BoundedArraySize
	(*ArrayType)(nil),        // 13: hermes.ArrayType
	(*BytesType)(nil),        // 14: hermes.BytesType
	(*Field)(nil),            // 15: hermes.Field
	(*ObjectType)(nil),       // 16: hermes.ObjectType
	(*ReferenceType)(nil),    // 17: hermes.ReferenceType
	(*VoidType)(nil),         // 18: hermes.VoidType
	(*Type)(nil),             // 19: hermes.Type
	(*ObjectValue)(nil),      // 20: hermes.ObjectValue
	(*ArrayValue)(nil),       // 21: hermes.ArrayValue
	(*BytesValue)(nil),       // 22: hermes.BytesValue
	(*EnumValue)(nil),        // 23: hermes.EnumValue
	(*Value)(nil),            // 24: hermes.Value
	nil,                      // 25: hermes.ObjectValue.OEntry
}
var file_type_proto_depIdxs = []int32{
	2,  // 0: hermes.BooleanType.encode_type:type_name -> hermes.UIntKind
	0,  // 1: hermes.IntType.kind:type_name -> hermes.IntKind
	4,  // 2: hermes.FloatType.kind:type_name -> hermes.FloatKind
	2,  // 3: hermes.StringType.length_type:type_name -> hermes.UIntKind
	0,  // 4: hermes.EnumType.encode_type:type_name -> hermes.IntKind
	10, // 5: hermes.EnumType.items:type_name -> hermes.EnumItem
	19, // 6: hermes.ArrayType.el_type:type_name -> hermes.Type
	12, // 7: hermes.ArrayType.dynamic:type_name -> hermes.BoundedArraySize
	2,  // 8: hermes.ArrayType.length_type:type_name -> hermes.UIntKind
	1,  // 9: hermes.BytesType.kind:type_name -> hermes.NumberKind
	12, // 10: hermes.BytesType.dynamic:type_name -> hermes.BoundedArraySize
	2,  // 11: hermes.BytesType.length_type:type_name -> hermes.UIntKind
	19, // 12: hermes.Field.type:type_name -> hermes.Type
	24, // 13: hermes.Field.value:type_name -> hermes.Value
	15, // 14: hermes.ObjectType.fields:type_name -> hermes.Field
	5,  // 15: hermes.ReferenceType.kind:type_name -> hermes.ReferenceKind
	17, // 16: hermes.Type.ref:type_name -> hermes.ReferenceType
	6,  // 17: hermes.Type.bool:type_name -> hermes.BooleanType
	7,  // 18: hermes.Type.int:type_name -> hermes.IntType
	8,  // 19: hermes.Type.float:type_name -> hermes.FloatType
	9,  // 20: hermes.Type.string:type_name -> hermes.StringType
	11, // 21: hermes.Type.enum:type_name -> hermes.EnumType
	11, // 22: hermes.Type.bitmask:type_name -> hermes.EnumType
	16, // 23: hermes.Type.object:type_name -> hermes.ObjectType
	13, // 24: hermes.Type.array:type_name -> hermes.ArrayType
	14, // 25: hermes.Type.bytes:type_name -> hermes.BytesType
	18, // 26: hermes.Type.void:type_name -> hermes.VoidType
	25, // 27: hermes.ObjectValue.o:type_name -> hermes.ObjectValue.OEntry
	24, // 28: hermes.ArrayValue.value:type_name -> hermes.Value
	1,  // 29: hermes.BytesValue.kind:type_name -> hermes.NumberKind
	23, // 30: hermes.Value.e:type_name -> hermes.EnumValue
	20, // 31: hermes.Value.o:type_name -> hermes.ObjectValue
	21, // 32: hermes.Value.a:type_name -> hermes.ArrayValue
	22, // 33: hermes.Value.r:type_name -> hermes.BytesValue
	24, // 34: hermes.ObjectValue.OEntry.value:type_name -> hermes.Value
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_type_proto_init() }
func file_type_proto_init() {
	if File_type_proto != nil {
		return
	}
	file_type_proto_msgTypes[7].OneofWrappers = []any{
		(*ArrayType_Static)(nil),
		(*ArrayType_Dynamic)(nil),
	}
	file_type_proto_msgTypes[8].OneofWrappers = []any{
		(*BytesType_Static)(nil),
		(*BytesType_Dynamic)(nil),
	}
	file_type_proto_msgTypes[13].OneofWrappers = []any{
		(*Type_Ref)(nil),
		(*Type_Bool)(nil),
		(*Type_Int)(nil),
		(*Type_Float)(nil),
		(*Type_String_)(nil),
		(*Type_Enum)(nil),
		(*Type_Bitmask)(nil),
		(*Type_Object)(nil),
		(*Type_Array)(nil),
		(*Type_Bytes)(nil),
		(*Type_Void)(nil),
	}
	file_type_proto_msgTypes[18].OneofWrappers = []any{
		(*Value_I)(nil),
		(*Value_U)(nil),
		(*Value_F)(nil),
		(*Value_B)(nil),
		(*Value_S)(nil),
		(*Value_E)(nil),
		(*Value_O)(nil),
		(*Value_A)(nil),
		(*Value_R)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_type_proto_goTypes,
		DependencyIndexes: file_type_proto_depIdxs,
		EnumInfos:         file_type_proto_enumTypes,
		MessageInfos:      file_type_proto_msgTypes,
	}.Build()
	File_type_proto = out.File
	file_type_proto_goTypes = nil
	file_type_proto_depIdxs = nil
}
