name: F Prime Integration Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  nightly:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      fprime-tag: nightly

