name: F Prime Integration Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  nightly:
    uses: ./.github/workflows/template-test-integration.yml
    with:
      fprime-tag: nightly
  v4_1_1:
    uses: ./.github/workflows/template-test-integration.yml
    with:
      fprime-tag: v4.1.1
  v4_0_0:
    # Disable 4.0 since CCSDS constants are not in the dictionary
    # v4.1+ is supported on CCSDS protocol
    # TODO(tumbar) Create a v4 build with fprime protocol
    if: false
    uses: ./.github/workflows/template-test-integration.yml
    with:
      fprime-tag: v4.0.0
